<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Estudios de casos y controles – Tipos de Estudios Estadísticos</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06-estudios-ecologicos.html" rel="next">
<link href="./04-estudios-cohortes.html" rel="prev">
<link href="./img/logos/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-3419ea62b3ca2d77d3d547f86109e84e.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-eaeb381c6b7494c50009502241a4985c.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-b050db56f2b97c639b7ebc2cf71c06d7.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-5e50218c20039713403b52e69b91eb5d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="5&nbsp; Estudios de casos y controles – Tipos de Estudios Estadísticos">
<meta property="og:description" content="">
<meta property="og:image" content="05-estudios-casos-controles_files/figure-html/forest-plot-or-1.png">
<meta property="og:site_name" content="Tipos de Estudios Estadísticos">
<meta name="twitter:title" content="5&nbsp; Estudios de casos y controles – Tipos de Estudios Estadísticos">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="05-estudios-casos-controles_files/figure-html/forest-plot-or-1.png">
<meta name="twitter:site" content="@aprendeconalf">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating quarto-dark"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = true;
    const darkModeDefault = authorPrefersDark;
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./02-estudios-descriptivos.html">Diseños de estudio</a></li><li class="breadcrumb-item"><a href="./05-estudios-casos-controles.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Estudios de casos y controles</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./img/logos/aprendeconalf.png" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="./img/logos/aprendeconalf.png" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Tipos de Estudios Estadísticos</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://aprendeconalf.es" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-house-fill"></i></a>
    <a href="https://github.com/asalber/estadistica-tipos-estudios" title="Ejecutar el código" class="quarto-navigation-tool px-1" aria-label="Ejecutar el código"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./estadistica-tipos-estudios.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./estadistica-tipos-estudios.epub">
              <i class="bi bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
      </ul>
    </div>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-1" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-1">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo oscuro"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-introduccion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción a los tipos de estudios estadísticos</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Diseños de estudio</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-estudios-descriptivos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Estudios descriptivos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-estudios-transversales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Estudios transversales</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-estudios-cohortes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Estudios de cohortes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-estudios-casos-controles.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Estudios de casos y controles</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-estudios-ecologicos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Estudios ecológicos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-estudios-experimentales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Estudios experimentales</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-estudios-cuasiexperimentales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Estudios cuasiexperimentales</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-encuestas-muestreo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Encuestas y diseño de muestreo</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Selección del contraste estadístico</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-seleccion-contraste.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Selección del contraste estadístico</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-contrastes-una-poblacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Contrastes para una población</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-contrastes-dos-poblaciones-independientes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Contrastes para dos poblaciones independientes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-contrastes-dos-poblaciones-pareadas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Contrastes para dos poblaciones pareadas</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-contrastes-mas-dos-poblaciones-independientes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Contrastes para más de dos poblaciones independientes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-contrastes-medidas-repetidas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Contrastes para más de dos poblaciones relacionadas (medidas repetidas)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-relacion-entre-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Relación y predicción entre dos variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Indice de contenidos</h2>
   
  <ul>
  <li><a href="#definición-y-características" id="toc-definición-y-características" class="nav-link active" data-scroll-target="#definición-y-características"><span class="header-section-number">5.1</span> Definición y características</a></li>
  <li><a href="#ventajas-e-inconvenientes" id="toc-ventajas-e-inconvenientes" class="nav-link" data-scroll-target="#ventajas-e-inconvenientes"><span class="header-section-number">5.2</span> Ventajas e inconvenientes</a></li>
  <li><a href="#medidas-propias-de-este-diseño" id="toc-medidas-propias-de-este-diseño" class="nav-link" data-scroll-target="#medidas-propias-de-este-diseño"><span class="header-section-number">5.3</span> Medidas propias de este diseño</a></li>
  <li><a href="#realización-con-r" id="toc-realización-con-r" class="nav-link" data-scroll-target="#realización-con-r"><span class="header-section-number">5.4</span> Realización con R</a></li>
  <li><a href="#casos-y-controles-apareados" id="toc-casos-y-controles-apareados" class="nav-link" data-scroll-target="#casos-y-controles-apareados"><span class="header-section-number">5.5</span> Casos y controles apareados</a></li>
  <li><a href="#cuándo-utilizar-este-diseño" id="toc-cuándo-utilizar-este-diseño" class="nav-link" data-scroll-target="#cuándo-utilizar-este-diseño"><span class="header-section-number">5.6</span> Cuándo utilizar este diseño</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/asalber/estadistica-tipos-estudios/edit/main/05-estudios-casos-controles.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li><li><a href="https://github.com/asalber/estadistica-tipos-estudios/issues/new" class="toc-action"><i class="bi empty"></i>Informar de un problema</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./02-estudios-descriptivos.html">Diseños de estudio</a></li><li class="breadcrumb-item"><a href="./05-estudios-casos-controles.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Estudios de casos y controles</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Estudios de casos y controles</span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Código</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Enseñar el código</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Esconder el código</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">Ver el código</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>El estudio de casos y controles es un diseño observacional y analítico que, a diferencia del <a href="./04-estudios-cohortes.html">estudio de cohortes</a>, recorre el tiempo en sentido inverso: en lugar de partir de la exposición y esperar a que aparezca el resultado, se parte del resultado, ya ocurrido, y se indaga hacia atrás en busca de la exposición pasada. Por este motivo se trata, casi siempre, de un diseño retrospectivo (véase el <a href="./01-introduccion.html">capítulo de introducción</a> para la distinción entre los criterios de clasificación de los estudios). Se seleccionan dos grupos de individuos definidos por su estado respecto al resultado (los <em>casos</em>, que presentan la enfermedad o el evento de interés, y los <em>controles</em>, que no lo presentan) y se compara la frecuencia con la que unos y otros estuvieron expuestos en el pasado al factor de estudio.</p>
<section id="definición-y-características" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="definición-y-características"><span class="header-section-number">5.1</span> Definición y características</h2>
<div id="def-casoscontroles-estudio-casos-controles" class="theorem definition">
<p><span class="theorem-title"><strong>Definición 5.1 (Estudio de casos y controles)</strong></span> Un <em>estudio de casos y controles</em> es un estudio observacional, analítico y habitualmente retrospectivo en el que se seleccionan dos grupos de individuos según la presencia (<em>casos</em>) o ausencia (<em>controles</em>) del resultado de interés, y se compara retrospectivamente la proporción de expuestos al factor de estudio en cada uno de los dos grupos.</p>
</div>
<p>El diseño se articula en torno a dos decisiones críticas, de las que depende en buena medida la validez del estudio:</p>
<ul>
<li><strong>Selección de los casos.</strong> Deben definirse con criterios diagnósticos claros y explícitos, de forma que no haya ambigüedad sobre quién es o no un caso. Es preferible utilizar casos <em>incidentes</em> (de nueva aparición) frente a casos <em>prevalentes</em> (ya existentes en el momento del estudio), porque estos últimos pueden reflejar factores asociados a la supervivencia con la enfermedad más que a su aparición.</li>
<li><strong>Selección de los controles.</strong> Deben proceder de la misma población de la que surgen los casos (la llamada <em>población base</em> o <em>population at risk</em>), de modo que, si hubieran desarrollado la enfermedad, habrían sido incluidos como casos. Un control mal elegido —que no sea representativo de esa población base— es la fuente de sesgo más frecuente y más difícil de corregir en este tipo de estudios.</li>
</ul>
<p>Una consecuencia importante de este diseño es que <strong>no permite calcular directamente ni la incidencia ni la prevalencia</strong> de la enfermedad. El motivo es que el número de casos y de controles no surge de muestrear aleatoriamente la población y observar cuántos enferman, sino que lo fija de antemano el propio investigador (por ejemplo, todos los casos disponibles en un hospital durante un periodo, junto con el doble de controles). Al no respetarse la proporción real de enfermos y sanos en la población, cualquier medida que dependa de esa proporción —como el riesgo relativo o la incidencia acumulada— queda distorsionada. Como se verá más adelante, esta limitación es precisamente la que obliga a recurrir a la <em>odds ratio</em> como medida de asociación propia de este diseño.</p>
</section>
<section id="ventajas-e-inconvenientes" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="ventajas-e-inconvenientes"><span class="header-section-number">5.2</span> Ventajas e inconvenientes</h2>
<p><strong>Ventajas:</strong></p>
<ul>
<li>Son estudios rápidos y baratos de realizar, ya que no requieren seguimiento de los individuos en el tiempo.</li>
<li>Son especialmente adecuados para el estudio de enfermedades raras, porque parten de un número fijo de casos ya identificados en lugar de esperar a que aparezcan en una cohorte.</li>
<li>Resultan también apropiados cuando el periodo de latencia entre la exposición y la enfermedad es muy largo, ya que evitan años de seguimiento.</li>
<li>Permiten estudiar simultáneamente varias exposiciones o factores de riesgo distintos para un mismo resultado.</li>
</ul>
<p><strong>Inconvenientes:</strong></p>
<ul>
<li>Son susceptibles al <strong>sesgo de memoria</strong> (<em>recall bias</em>): los casos, al haber sufrido la enfermedad, tienden a recordar y declarar con más detalle exposiciones pasadas que los controles.</li>
<li>Son susceptibles al <strong>sesgo de selección de controles</strong>, si estos no son verdaderamente representativos de la población base de la que proceden los casos.</li>
<li>No permiten calcular directamente la incidencia ni la prevalencia de la enfermedad, como se ha explicado.</li>
<li>La secuencia temporal entre exposición y resultado, al reconstruirse retrospectivamente, puede ser difícil de establecer con certeza en algunos casos.</li>
</ul>
</section>
<section id="medidas-propias-de-este-diseño" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="medidas-propias-de-este-diseño"><span class="header-section-number">5.3</span> Medidas propias de este diseño</h2>
<p>Como la incidencia no puede calcularse en este diseño, no es posible obtener el riesgo relativo tal y como se define en un <a href="./04-estudios-cohortes.html">estudio de cohortes</a>. La medida de asociación propia de los estudios de casos y controles es la <em>razón de momios</em> u <em>Odds Ratio</em> (OR), que compara la <em>odds</em> (el momio) de haber estado expuesto entre los casos con la de haber estado expuesto entre los controles.</p>
<p>Partiendo de una tabla de contingencia <span class="math inline">\(2\times 2\)</span> que cruza la exposición con la condición de caso o control,</p>
<p><span class="math display">\[
\begin{array}{lrrr}
\hline
&amp; \mbox{Casos} &amp; \mbox{Controles} &amp; \mbox{Total}\\
\hline
\mbox{Expuestos} &amp; a &amp; b &amp; a+b\\
\mbox{No expuestos} &amp; c &amp; d &amp; c+d\\
\hline
\mbox{Total} &amp; a+c &amp; b+d &amp; n\\
\hline
\end{array}
\]</span></p>
<div id="def-casoscontroles-odds-ratio" class="theorem definition">
<p><span class="theorem-title"><strong>Definición 5.2 (Odds ratio)</strong></span> La <em>odds</em> (o momio) de exposición entre los casos es el cociente entre el número de casos expuestos y el número de casos no expuestos,</p>
<p><span class="math display">\[\mbox{Odds}_{\mbox{casos}} = \frac{a}{c},\]</span></p>
<p>y la odds de exposición entre los controles es el cociente entre el número de controles expuestos y el número de controles no expuestos,</p>
<p><span class="math display">\[\mbox{Odds}_{\mbox{controles}} = \frac{b}{d}.\]</span></p>
<p>La <em>Odds Ratio</em> (OR) se define como el cociente entre ambas odds,</p>
<p><span class="math display">\[OR = \frac{\mbox{Odds}_{\mbox{casos}}}{\mbox{Odds}_{\mbox{controles}}} = \frac{a/c}{b/d} = \frac{a\cdot d}{b\cdot c}.\]</span></p>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importante
</div>
</div>
<div class="callout-body-container callout-body">
<p>Al ser un cociente de dos cantidades positivas, la odds ratio verifica</p>
<p><span class="math display">\[OR &gt; 0,\]</span></p>
<p>y <span class="math inline">\(OR=1\)</span> indica ausencia de asociación entre la exposición y el resultado, ya que en ese caso la odds de exposición es idéntica en casos y en controles.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Interpretación">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Interpretación
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Si <span class="math inline">\(OR=1\)</span>, la exposición no está asociada con la enfermedad.</li>
<li>Si <span class="math inline">\(OR&gt;1\)</span>, la exposición está asociada positivamente con la enfermedad: los expuestos tienen una odds mayor de ser casos, por lo que la exposición se comporta como un <strong>factor de riesgo</strong>.</li>
<li>Si <span class="math inline">\(OR&lt;1\)</span>, la exposición está asociada negativamente con la enfermedad: los expuestos tienen una odds menor de ser casos, por lo que la exposición se comporta como un <strong>factor protector</strong>.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Relación con el riesgo relativo">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Relación con el riesgo relativo
</div>
</div>
<div class="callout-body-container callout-body">
<p>En un <a href="./04-estudios-cohortes.html">estudio de cohortes</a> la medida natural de asociación es el riesgo relativo (RR), que compara directamente las incidencias (probabilidades) de enfermar entre expuestos y no expuestos. En un estudio de casos y controles no es posible calcular incidencias, por lo que el RR no puede obtenerse directamente. Sin embargo, cuando la enfermedad estudiada es <strong>poco frecuente</strong> en la población (el llamado <em>supuesto de enfermedad rara</em>, por ejemplo con una prevalencia inferior al 10%), la probabilidad de enfermar es muy pequeña tanto en expuestos como en no expuestos, de modo que la odds de enfermar (probabilidad entre 1 menos probabilidad) se aproxima mucho a la propia probabilidad. En estas condiciones puede demostrarse que la odds ratio calculada en el estudio de casos y controles constituye una buena aproximación del riesgo relativo poblacional, <span class="math inline">\(OR \approx RR\)</span>, lo que permite interpretarla de forma similar aunque los diseños sean muy distintos.</p>
</div>
</div>
<p>La incertidumbre muestral de la OR se cuantifica mediante su intervalo de confianza. Como la distribución de la OR es muy asimétrica, el intervalo se construye habitualmente sobre su logaritmo, que se aproxima mejor a una distribución normal.</p>
<div id="def-casoscontroles-ic-odds-ratio" class="theorem definition">
<p><span class="theorem-title"><strong>Definición 5.3 (Intervalo de confianza de la odds ratio (método de Woolf))</strong></span> El error estándar del logaritmo de la odds ratio se estima como</p>
<p><span class="math display">\[SE(\ln OR) = \sqrt{\frac{1}{a}+\frac{1}{b}+\frac{1}{c}+\frac{1}{d}},\]</span></p>
<p>y el intervalo de confianza al <span class="math inline">\((1-\alpha)\cdot 100\%\)</span> para la OR, conocido como método de Woolf, se obtiene deshaciendo el logaritmo tras construir el intervalo en escala logarítmica,</p>
<p><span class="math display">\[IC_{(1-\alpha)\cdot100\%} = \exp\left(\ln(OR) \pm z_{1-\alpha/2}\sqrt{\frac{1}{a}+\frac{1}{b}+\frac{1}{c}+\frac{1}{d}}\right).\]</span></p>
<p>Para un nivel de confianza del 95%, <span class="math inline">\(z_{0.975}=1.96\)</span>.</p>
</div>
<div id="exm-casoscontroles-odds-ratio" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 5.1</strong></span> Se quiere estudiar la asociación entre el consumo habitual de tabaco y la aparición de cáncer de pulmón mediante un estudio de casos y controles. Se seleccionan 100 casos (pacientes recién diagnosticados de cáncer de pulmón) y 200 controles (pacientes sin cáncer de pulmón, similares en edad y sexo), y se les pregunta retrospectivamente si han sido fumadores habituales. Los resultados se resumen en la siguiente tabla:</p>
<p><span class="math display">\[
\begin{array}{lrrr}
\hline
&amp; \mbox{Casos} &amp; \mbox{Controles} &amp; \mbox{Total}\\
\hline
\mbox{Fumadores} &amp; 70 &amp; 80 &amp; 150\\
\mbox{No fumadores} &amp; 30 &amp; 120 &amp; 150\\
\hline
\mbox{Total} &amp; 100 &amp; 200 &amp; 300\\
\hline
\end{array}
\]</span></p>
<p>Con <span class="math inline">\(a=70\)</span>, <span class="math inline">\(b=80\)</span>, <span class="math inline">\(c=30\)</span> y <span class="math inline">\(d=120\)</span>, la odds ratio es</p>
<p><span class="math display">\[OR = \frac{a\cdot d}{b\cdot c} = \frac{70\cdot 120}{80\cdot 30} = \frac{8400}{2400} = 3.5.\]</span></p>
<p>Es decir, la odds de haber fumado es 3.5 veces mayor entre los casos (pacientes con cáncer de pulmón) que entre los controles, lo que sugiere que el tabaco se comporta como un factor de riesgo para esta enfermedad. Como se trata de una enfermedad poco frecuente en la población general, esta OR puede interpretarse aproximadamente como el riesgo relativo.</p>
<p>Para calcular el intervalo de confianza al 95%, se obtiene primero el error estándar del logaritmo de la OR,</p>
<p><span class="math display">\[SE(\ln OR) = \sqrt{\frac{1}{70}+\frac{1}{80}+\frac{1}{30}+\frac{1}{120}} = \sqrt{0.0143+0.0125+0.0333+0.0083} = \sqrt{0.0684} = 0.2615,\]</span></p>
<p>y como <span class="math inline">\(\ln(3.5) = 1.2528\)</span>, el intervalo en escala logarítmica es</p>
<p><span class="math display">\[1.2528 \pm 1.96\cdot 0.2615 = 1.2528 \pm 0.5125 = (0.7403,\ 1.7653),\]</span></p>
<p>que, deshaciendo el logaritmo, da el intervalo de confianza para la OR</p>
<p><span class="math display">\[IC_{95\%} = (e^{0.7403},\ e^{1.7653}) = (2.10,\ 5.84).\]</span></p>
<p>Como el intervalo no contiene el valor 1, la asociación entre tabaco y cáncer de pulmón es estadísticamente significativa al 95% de confianza.</p>
</div>
</section>
<section id="realización-con-r" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="realización-con-r"><span class="header-section-number">5.4</span> Realización con R</h2>
<p>El siguiente código reproduce en R el ejemplo anterior, calculando la OR y su intervalo de confianza al 95% a partir de la tabla <span class="math inline">\(2\times 2\)</span> para comprobar que coincide con el cálculo manual.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabla 2x2: filas = expuestos/no expuestos, columnas = casos/controles</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>tabla <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">70</span>, <span class="dv">80</span>, <span class="dv">30</span>, <span class="dv">120</span>),</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">dimnames =</span> <span class="fu">list</span>(</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">Exposicion =</span> <span class="fu">c</span>(<span class="st">"Fumador"</span>, <span class="st">"No fumador"</span>),</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">Grupo =</span> <span class="fu">c</span>(<span class="st">"Casos"</span>, <span class="st">"Controles"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>                ))</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>tabla</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            Grupo
Exposicion   Casos Controles
  Fumador       70        80
  No fumador    30       120</code></pre>
</div>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> tabla[<span class="st">"Fumador"</span>, <span class="st">"Casos"</span>]</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> tabla[<span class="st">"Fumador"</span>, <span class="st">"Controles"</span>]</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>c_ <span class="ot">&lt;-</span> tabla[<span class="st">"No fumador"</span>, <span class="st">"Casos"</span>]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> tabla[<span class="st">"No fumador"</span>, <span class="st">"Controles"</span>]</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Odds ratio</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>or <span class="ot">&lt;-</span> (a <span class="sc">*</span> d) <span class="sc">/</span> (b <span class="sc">*</span> c_)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Error estándar del logaritmo de la OR (método de Woolf)</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>se_log_or <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="dv">1</span> <span class="sc">/</span> a <span class="sc">+</span> <span class="dv">1</span> <span class="sc">/</span> b <span class="sc">+</span> <span class="dv">1</span> <span class="sc">/</span> c_ <span class="sc">+</span> <span class="dv">1</span> <span class="sc">/</span> d)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Intervalo de confianza al 95%</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>ic_inferior <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">log</span>(or) <span class="sc">-</span> z <span class="sc">*</span> se_log_or)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>ic_superior <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">log</span>(or) <span class="sc">+</span> z <span class="sc">*</span> se_log_or)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>resultado <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">medida =</span> <span class="st">"Odds Ratio"</span>,</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">estimacion =</span> or,</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">ic_95_inferior =</span> ic_inferior,</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">ic_95_superior =</span> ic_superior</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>resultado</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  medida     estimacion ic_95_inferior ic_95_superior
  &lt;chr&gt;           &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;
1 Odds Ratio        3.5           2.10           5.84</code></pre>
</div>
</div>
<p>El resultado coincide con el obtenido a mano: <span class="math inline">\(OR=3.5\)</span> con un intervalo de confianza al 95% de <span class="math inline">\((2.10,\ 5.84)\)</span>.</p>
<p>Una forma habitual de representar gráficamente una odds ratio junto con su intervalo de confianza es el llamado <em>forest plot</em>, que muestra la estimación puntual y su incertidumbre en relación con la línea de referencia <span class="math inline">\(OR=1\)</span> (ausencia de asociación).</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(resultado, <span class="fu">aes</span>(<span class="at">x =</span> or, <span class="at">y =</span> medida)) <span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">1</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"grey40"</span>) <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbarh</span>(<span class="fu">aes</span>(<span class="at">xmin =</span> ic_95_inferior, <span class="at">xmax =</span> ic_95_superior), <span class="at">height =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>() <span class="sc">+</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Odds Ratio (escala logarítmica)"</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="cn">NULL</span>,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Tabaco y cáncer de pulmón"</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05-estudios-casos-controles_files/figure-html/forest-plot-or-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Odds ratio del consumo de tabaco y su intervalo de confianza al 95%.</figcaption>
</figure>
</div>
</div>
</div>
<p>El punto se sitúa claramente a la derecha de la línea de referencia <span class="math inline">\(OR=1\)</span>, y todo el intervalo de confianza queda también por encima de ella, lo que confirma gráficamente que el consumo de tabaco está asociado de forma significativa con un mayor riesgo de cáncer de pulmón en esta muestra.</p>
</section>
<section id="casos-y-controles-apareados" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="casos-y-controles-apareados"><span class="header-section-number">5.5</span> Casos y controles apareados</h2>
<p>En ocasiones, cada caso se <em>aparea</em> (<em>matching</em>) con uno o varios controles que comparten con él ciertas características que se sabe o se sospecha que actúan como factores de confusión, como la edad, el sexo o el centro de reclutamiento. El objetivo del apareamiento es asegurar que casos y controles sean lo más comparables posible en esas variables, de forma que cualquier diferencia observada en la exposición sea más difícilmente atribuible a ellas. Por ejemplo, a cada caso de 55 años se le podrían asignar dos controles también de 55 años y del mismo sexo.</p>
<p>El apareamiento tiene, sin embargo, un coste analítico: la tabla <span class="math inline">\(2\times 2\)</span> simple ya no resulta válida para comparar los grupos, porque las observaciones dejan de ser independientes (cada caso está ligado a su control o controles concretos). El análisis de datos apareados requiere métodos estadísticos específicos, como el <strong>test de McNemar</strong> para el caso de un control por caso, o la regresión logística condicional cuando hay varios controles por caso, que quedan fuera del alcance de este capítulo introductorio.</p>
</section>
<section id="cuándo-utilizar-este-diseño" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="cuándo-utilizar-este-diseño"><span class="header-section-number">5.6</span> Cuándo utilizar este diseño</h2>
<p>El estudio de casos y controles es la opción de elección cuando la enfermedad o el evento de interés es raro, cuando su periodo de latencia es muy largo, o cuando se dispone de poco tiempo y presupuesto para completar la investigación. También resulta muy útil como paso exploratorio para generar hipótesis sobre múltiples posibles exposiciones a la vez, antes de invertir en un diseño más costoso. Cuando, por el contrario, es la <strong>exposición</strong> la que resulta rara en la población (y no la enfermedad), suele ser preferible recurrir a un <a href="./04-estudios-cohortes.html">estudio de cohortes</a>, que garantiza un número suficiente de expuestos y permite además calcular directamente incidencias y riesgos relativos. En la práctica, ambos diseños se consideran complementarios dentro de la investigación epidemiológica observacional.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./04-estudios-cohortes.html" class="pagination-link" aria-label="Estudios de cohortes">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Estudios de cohortes</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./06-estudios-ecologicos.html" class="pagination-link" aria-label="Estudios ecológicos">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Estudios ecológicos</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Ejecutar el código</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> Estudios de casos y controles</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="an">lang:</span><span class="co"> es</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="in">```{r setup, include=FALSE}</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">message =</span> <span class="cn">FALSE</span>, <span class="at">warning =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>El estudio de casos y controles es un diseño observacional y analítico que, a diferencia del <span class="co">[</span><span class="ot">estudio de cohortes</span><span class="co">](04-estudios-cohortes.qmd)</span>, recorre el tiempo en sentido inverso: en lugar de partir de la exposición y esperar a que aparezca el resultado, se parte del resultado, ya ocurrido, y se indaga hacia atrás en busca de la exposición pasada. Por este motivo se trata, casi siempre, de un diseño retrospectivo (véase el <span class="co">[</span><span class="ot">capítulo de introducción</span><span class="co">](01-introduccion.qmd)</span> para la distinción entre los criterios de clasificación de los estudios). Se seleccionan dos grupos de individuos definidos por su estado respecto al resultado (los _casos_, que presentan la enfermedad o el evento de interés, y los _controles_, que no lo presentan) y se compara la frecuencia con la que unos y otros estuvieron expuestos en el pasado al factor de estudio.</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="fu">## Definición y características</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>:::{#def-casoscontroles-estudio-casos-controles}</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a><span class="fu">## Estudio de casos y controles</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>Un _estudio de casos y controles_ es un estudio observacional, analítico y habitualmente retrospectivo en el que se seleccionan dos grupos de individuos según la presencia (_casos_) o ausencia (_controles_) del resultado de interés, y se compara retrospectivamente la proporción de expuestos al factor de estudio en cada uno de los dos grupos.</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>El diseño se articula en torno a dos decisiones críticas, de las que depende en buena medida la validez del estudio:</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Selección de los casos.** Deben definirse con criterios diagnósticos claros y explícitos, de forma que no haya ambigüedad sobre quién es o no un caso. Es preferible utilizar casos _incidentes_ (de nueva aparición) frente a casos _prevalentes_ (ya existentes en el momento del estudio), porque estos últimos pueden reflejar factores asociados a la supervivencia con la enfermedad más que a su aparición.</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Selección de los controles.** Deben proceder de la misma población de la que surgen los casos (la llamada _población base_ o _population at risk_), de modo que, si hubieran desarrollado la enfermedad, habrían sido incluidos como casos. Un control mal elegido —que no sea representativo de esa población base— es la fuente de sesgo más frecuente y más difícil de corregir en este tipo de estudios.</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>Una consecuencia importante de este diseño es que **no permite calcular directamente ni la incidencia ni la prevalencia** de la enfermedad. El motivo es que el número de casos y de controles no surge de muestrear aleatoriamente la población y observar cuántos enferman, sino que lo fija de antemano el propio investigador (por ejemplo, todos los casos disponibles en un hospital durante un periodo, junto con el doble de controles). Al no respetarse la proporción real de enfermos y sanos en la población, cualquier medida que dependa de esa proporción —como el riesgo relativo o la incidencia acumulada— queda distorsionada. Como se verá más adelante, esta limitación es precisamente la que obliga a recurrir a la _odds ratio_ como medida de asociación propia de este diseño.</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a><span class="fu">## Ventajas e inconvenientes</span></span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>**Ventajas:**</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Son estudios rápidos y baratos de realizar, ya que no requieren seguimiento de los individuos en el tiempo.</span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Son especialmente adecuados para el estudio de enfermedades raras, porque parten de un número fijo de casos ya identificados en lugar de esperar a que aparezcan en una cohorte.</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Resultan también apropiados cuando el periodo de latencia entre la exposición y la enfermedad es muy largo, ya que evitan años de seguimiento.</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Permiten estudiar simultáneamente varias exposiciones o factores de riesgo distintos para un mismo resultado.</span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>**Inconvenientes:**</span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Son susceptibles al **sesgo de memoria** (_recall bias_): los casos, al haber sufrido la enfermedad, tienden a recordar y declarar con más detalle exposiciones pasadas que los controles.</span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Son susceptibles al **sesgo de selección de controles**, si estos no son verdaderamente representativos de la población base de la que proceden los casos.</span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>No permiten calcular directamente la incidencia ni la prevalencia de la enfermedad, como se ha explicado.</span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>La secuencia temporal entre exposición y resultado, al reconstruirse retrospectivamente, puede ser difícil de establecer con certeza en algunos casos.</span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a><span class="fu">## Medidas propias de este diseño</span></span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a>Como la incidencia no puede calcularse en este diseño, no es posible obtener el riesgo relativo tal y como se define en un <span class="co">[</span><span class="ot">estudio de cohortes</span><span class="co">](04-estudios-cohortes.qmd)</span>. La medida de asociación propia de los estudios de casos y controles es la _razón de momios_ u _Odds Ratio_ (OR), que compara la _odds_ (el momio) de haber estado expuesto entre los casos con la de haber estado expuesto entre los controles.</span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a>Partiendo de una tabla de contingencia $2\times 2$ que cruza la exposición con la condición de caso o control,</span>
<span id="cb6-48"><a href="#cb6-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-49"><a href="#cb6-49" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-50"><a href="#cb6-50" aria-hidden="true" tabindex="-1"></a>\begin{array}{lrrr}</span>
<span id="cb6-51"><a href="#cb6-51" aria-hidden="true" tabindex="-1"></a>\hline</span>
<span id="cb6-52"><a href="#cb6-52" aria-hidden="true" tabindex="-1"></a> &amp; \mbox{Casos} &amp; \mbox{Controles} &amp; \mbox{Total}<span class="sc">\\</span></span>
<span id="cb6-53"><a href="#cb6-53" aria-hidden="true" tabindex="-1"></a>\hline</span>
<span id="cb6-54"><a href="#cb6-54" aria-hidden="true" tabindex="-1"></a>\mbox{Expuestos} &amp; a &amp; b &amp; a+b<span class="sc">\\</span></span>
<span id="cb6-55"><a href="#cb6-55" aria-hidden="true" tabindex="-1"></a>\mbox{No expuestos} &amp; c &amp; d &amp; c+d<span class="sc">\\</span></span>
<span id="cb6-56"><a href="#cb6-56" aria-hidden="true" tabindex="-1"></a>\hline</span>
<span id="cb6-57"><a href="#cb6-57" aria-hidden="true" tabindex="-1"></a>\mbox{Total} &amp; a+c &amp; b+d &amp; n<span class="sc">\\</span></span>
<span id="cb6-58"><a href="#cb6-58" aria-hidden="true" tabindex="-1"></a>\hline</span>
<span id="cb6-59"><a href="#cb6-59" aria-hidden="true" tabindex="-1"></a>\end{array}</span>
<span id="cb6-60"><a href="#cb6-60" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-61"><a href="#cb6-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-62"><a href="#cb6-62" aria-hidden="true" tabindex="-1"></a>:::{#def-casoscontroles-odds-ratio}</span>
<span id="cb6-63"><a href="#cb6-63" aria-hidden="true" tabindex="-1"></a><span class="fu">## Odds ratio</span></span>
<span id="cb6-64"><a href="#cb6-64" aria-hidden="true" tabindex="-1"></a>La _odds_ (o momio) de exposición entre los casos es el cociente entre el número de casos expuestos y el número de casos no expuestos,</span>
<span id="cb6-65"><a href="#cb6-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-66"><a href="#cb6-66" aria-hidden="true" tabindex="-1"></a>$$\mbox{Odds}_{\mbox{casos}} = \frac{a}{c},$$</span>
<span id="cb6-67"><a href="#cb6-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-68"><a href="#cb6-68" aria-hidden="true" tabindex="-1"></a>y la odds de exposición entre los controles es el cociente entre el número de controles expuestos y el número de controles no expuestos,</span>
<span id="cb6-69"><a href="#cb6-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-70"><a href="#cb6-70" aria-hidden="true" tabindex="-1"></a>$$\mbox{Odds}_{\mbox{controles}} = \frac{b}{d}.$$</span>
<span id="cb6-71"><a href="#cb6-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-72"><a href="#cb6-72" aria-hidden="true" tabindex="-1"></a>La _Odds Ratio_ (OR) se define como el cociente entre ambas odds,</span>
<span id="cb6-73"><a href="#cb6-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-74"><a href="#cb6-74" aria-hidden="true" tabindex="-1"></a>$$OR = \frac{\mbox{Odds}_{\mbox{casos}}}{\mbox{Odds}_{\mbox{controles}}} = \frac{a/c}{b/d} = \frac{a\cdot d}{b\cdot c}.$$</span>
<span id="cb6-75"><a href="#cb6-75" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb6-76"><a href="#cb6-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-77"><a href="#cb6-77" aria-hidden="true" tabindex="-1"></a>:::{.callout-important}</span>
<span id="cb6-78"><a href="#cb6-78" aria-hidden="true" tabindex="-1"></a>Al ser un cociente de dos cantidades positivas, la odds ratio verifica</span>
<span id="cb6-79"><a href="#cb6-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-80"><a href="#cb6-80" aria-hidden="true" tabindex="-1"></a>$$OR &gt; 0,$$</span>
<span id="cb6-81"><a href="#cb6-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-82"><a href="#cb6-82" aria-hidden="true" tabindex="-1"></a>y $OR=1$ indica ausencia de asociación entre la exposición y el resultado, ya que en ese caso la odds de exposición es idéntica en casos y en controles.</span>
<span id="cb6-83"><a href="#cb6-83" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb6-84"><a href="#cb6-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-85"><a href="#cb6-85" aria-hidden="true" tabindex="-1"></a>:::{.callout-note title=Interpretación}</span>
<span id="cb6-86"><a href="#cb6-86" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Si $OR=1$, la exposición no está asociada con la enfermedad.</span>
<span id="cb6-87"><a href="#cb6-87" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Si $OR&gt;1$, la exposición está asociada positivamente con la enfermedad: los expuestos tienen una odds mayor de ser casos, por lo que la exposición se comporta como un **factor de riesgo**.</span>
<span id="cb6-88"><a href="#cb6-88" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Si $OR&lt;1$, la exposición está asociada negativamente con la enfermedad: los expuestos tienen una odds menor de ser casos, por lo que la exposición se comporta como un **factor protector**.</span>
<span id="cb6-89"><a href="#cb6-89" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb6-90"><a href="#cb6-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-91"><a href="#cb6-91" aria-hidden="true" tabindex="-1"></a>:::{.callout-note title="Relación con el riesgo relativo"}</span>
<span id="cb6-92"><a href="#cb6-92" aria-hidden="true" tabindex="-1"></a>En un <span class="co">[</span><span class="ot">estudio de cohortes</span><span class="co">](04-estudios-cohortes.qmd)</span> la medida natural de asociación es el riesgo relativo (RR), que compara directamente las incidencias (probabilidades) de enfermar entre expuestos y no expuestos. En un estudio de casos y controles no es posible calcular incidencias, por lo que el RR no puede obtenerse directamente. Sin embargo, cuando la enfermedad estudiada es **poco frecuente** en la población (el llamado _supuesto de enfermedad rara_, por ejemplo con una prevalencia inferior al 10%), la probabilidad de enfermar es muy pequeña tanto en expuestos como en no expuestos, de modo que la odds de enfermar (probabilidad entre 1 menos probabilidad) se aproxima mucho a la propia probabilidad. En estas condiciones puede demostrarse que la odds ratio calculada en el estudio de casos y controles constituye una buena aproximación del riesgo relativo poblacional, $OR \approx RR$, lo que permite interpretarla de forma similar aunque los diseños sean muy distintos.</span>
<span id="cb6-93"><a href="#cb6-93" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb6-94"><a href="#cb6-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-95"><a href="#cb6-95" aria-hidden="true" tabindex="-1"></a>La incertidumbre muestral de la OR se cuantifica mediante su intervalo de confianza. Como la distribución de la OR es muy asimétrica, el intervalo se construye habitualmente sobre su logaritmo, que se aproxima mejor a una distribución normal.</span>
<span id="cb6-96"><a href="#cb6-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-97"><a href="#cb6-97" aria-hidden="true" tabindex="-1"></a>:::{#def-casoscontroles-ic-odds-ratio}</span>
<span id="cb6-98"><a href="#cb6-98" aria-hidden="true" tabindex="-1"></a><span class="fu">## Intervalo de confianza de la odds ratio (método de Woolf)</span></span>
<span id="cb6-99"><a href="#cb6-99" aria-hidden="true" tabindex="-1"></a>El error estándar del logaritmo de la odds ratio se estima como</span>
<span id="cb6-100"><a href="#cb6-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-101"><a href="#cb6-101" aria-hidden="true" tabindex="-1"></a>$$SE(\ln OR) = \sqrt{\frac{1}{a}+\frac{1}{b}+\frac{1}{c}+\frac{1}{d}},$$</span>
<span id="cb6-102"><a href="#cb6-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-103"><a href="#cb6-103" aria-hidden="true" tabindex="-1"></a>y el intervalo de confianza al $(1-\alpha)\cdot 100\%$ para la OR, conocido como método de Woolf, se obtiene deshaciendo el logaritmo tras construir el intervalo en escala logarítmica,</span>
<span id="cb6-104"><a href="#cb6-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-105"><a href="#cb6-105" aria-hidden="true" tabindex="-1"></a>$$IC_{(1-\alpha)\cdot100\%} = \exp\left(\ln(OR) \pm z_{1-\alpha/2}\sqrt{\frac{1}{a}+\frac{1}{b}+\frac{1}{c}+\frac{1}{d}}\right).$$</span>
<span id="cb6-106"><a href="#cb6-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-107"><a href="#cb6-107" aria-hidden="true" tabindex="-1"></a>Para un nivel de confianza del 95%, $z_{0.975}=1.96$.</span>
<span id="cb6-108"><a href="#cb6-108" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb6-109"><a href="#cb6-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-110"><a href="#cb6-110" aria-hidden="true" tabindex="-1"></a>:::{#exm-casoscontroles-odds-ratio}</span>
<span id="cb6-111"><a href="#cb6-111" aria-hidden="true" tabindex="-1"></a>Se quiere estudiar la asociación entre el consumo habitual de tabaco y la aparición de cáncer de pulmón mediante un estudio de casos y controles. Se seleccionan 100 casos (pacientes recién diagnosticados de cáncer de pulmón) y 200 controles (pacientes sin cáncer de pulmón, similares en edad y sexo), y se les pregunta retrospectivamente si han sido fumadores habituales. Los resultados se resumen en la siguiente tabla:</span>
<span id="cb6-112"><a href="#cb6-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-113"><a href="#cb6-113" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-114"><a href="#cb6-114" aria-hidden="true" tabindex="-1"></a>\begin{array}{lrrr}</span>
<span id="cb6-115"><a href="#cb6-115" aria-hidden="true" tabindex="-1"></a>\hline</span>
<span id="cb6-116"><a href="#cb6-116" aria-hidden="true" tabindex="-1"></a> &amp; \mbox{Casos} &amp; \mbox{Controles} &amp; \mbox{Total}<span class="sc">\\</span></span>
<span id="cb6-117"><a href="#cb6-117" aria-hidden="true" tabindex="-1"></a>\hline</span>
<span id="cb6-118"><a href="#cb6-118" aria-hidden="true" tabindex="-1"></a>\mbox{Fumadores} &amp; 70 &amp; 80 &amp; 150<span class="sc">\\</span></span>
<span id="cb6-119"><a href="#cb6-119" aria-hidden="true" tabindex="-1"></a>\mbox{No fumadores} &amp; 30 &amp; 120 &amp; 150<span class="sc">\\</span></span>
<span id="cb6-120"><a href="#cb6-120" aria-hidden="true" tabindex="-1"></a>\hline</span>
<span id="cb6-121"><a href="#cb6-121" aria-hidden="true" tabindex="-1"></a>\mbox{Total} &amp; 100 &amp; 200 &amp; 300<span class="sc">\\</span></span>
<span id="cb6-122"><a href="#cb6-122" aria-hidden="true" tabindex="-1"></a>\hline</span>
<span id="cb6-123"><a href="#cb6-123" aria-hidden="true" tabindex="-1"></a>\end{array}</span>
<span id="cb6-124"><a href="#cb6-124" aria-hidden="true" tabindex="-1"></a>$$</span>
<span id="cb6-125"><a href="#cb6-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-126"><a href="#cb6-126" aria-hidden="true" tabindex="-1"></a>Con $a=70$, $b=80$, $c=30$ y $d=120$, la odds ratio es</span>
<span id="cb6-127"><a href="#cb6-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-128"><a href="#cb6-128" aria-hidden="true" tabindex="-1"></a>$$OR = \frac{a\cdot d}{b\cdot c} = \frac{70\cdot 120}{80\cdot 30} = \frac{8400}{2400} = 3.5.$$</span>
<span id="cb6-129"><a href="#cb6-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-130"><a href="#cb6-130" aria-hidden="true" tabindex="-1"></a>Es decir, la odds de haber fumado es 3.5 veces mayor entre los casos (pacientes con cáncer de pulmón) que entre los controles, lo que sugiere que el tabaco se comporta como un factor de riesgo para esta enfermedad. Como se trata de una enfermedad poco frecuente en la población general, esta OR puede interpretarse aproximadamente como el riesgo relativo.</span>
<span id="cb6-131"><a href="#cb6-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-132"><a href="#cb6-132" aria-hidden="true" tabindex="-1"></a>Para calcular el intervalo de confianza al 95%, se obtiene primero el error estándar del logaritmo de la OR,</span>
<span id="cb6-133"><a href="#cb6-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-134"><a href="#cb6-134" aria-hidden="true" tabindex="-1"></a>$$SE(\ln OR) = \sqrt{\frac{1}{70}+\frac{1}{80}+\frac{1}{30}+\frac{1}{120}} = \sqrt{0.0143+0.0125+0.0333+0.0083} = \sqrt{0.0684} = 0.2615,$$</span>
<span id="cb6-135"><a href="#cb6-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-136"><a href="#cb6-136" aria-hidden="true" tabindex="-1"></a>y como $\ln(3.5) = 1.2528$, el intervalo en escala logarítmica es</span>
<span id="cb6-137"><a href="#cb6-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-138"><a href="#cb6-138" aria-hidden="true" tabindex="-1"></a>$$1.2528 \pm 1.96\cdot 0.2615 = 1.2528 \pm 0.5125 = (0.7403,\ 1.7653),$$</span>
<span id="cb6-139"><a href="#cb6-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-140"><a href="#cb6-140" aria-hidden="true" tabindex="-1"></a>que, deshaciendo el logaritmo, da el intervalo de confianza para la OR</span>
<span id="cb6-141"><a href="#cb6-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-142"><a href="#cb6-142" aria-hidden="true" tabindex="-1"></a>$$IC_{95\%} = (e^{0.7403},\ e^{1.7653}) = (2.10,\ 5.84).$$</span>
<span id="cb6-143"><a href="#cb6-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-144"><a href="#cb6-144" aria-hidden="true" tabindex="-1"></a>Como el intervalo no contiene el valor 1, la asociación entre tabaco y cáncer de pulmón es estadísticamente significativa al 95% de confianza.</span>
<span id="cb6-145"><a href="#cb6-145" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb6-146"><a href="#cb6-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-147"><a href="#cb6-147" aria-hidden="true" tabindex="-1"></a><span class="fu">## Realización con R</span></span>
<span id="cb6-148"><a href="#cb6-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-149"><a href="#cb6-149" aria-hidden="true" tabindex="-1"></a>El siguiente código reproduce en R el ejemplo anterior, calculando la OR y su intervalo de confianza al 95% a partir de la tabla $2\times 2$ para comprobar que coincide con el cálculo manual.</span>
<span id="cb6-150"><a href="#cb6-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-153"><a href="#cb6-153" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-154"><a href="#cb6-154" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabla 2x2: filas = expuestos/no expuestos, columnas = casos/controles</span></span>
<span id="cb6-155"><a href="#cb6-155" aria-hidden="true" tabindex="-1"></a>tabla <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">70</span>, <span class="dv">80</span>, <span class="dv">30</span>, <span class="dv">120</span>),</span>
<span id="cb6-156"><a href="#cb6-156" aria-hidden="true" tabindex="-1"></a>                <span class="at">nrow =</span> <span class="dv">2</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>,</span>
<span id="cb6-157"><a href="#cb6-157" aria-hidden="true" tabindex="-1"></a>                <span class="at">dimnames =</span> <span class="fu">list</span>(</span>
<span id="cb6-158"><a href="#cb6-158" aria-hidden="true" tabindex="-1"></a>                  <span class="at">Exposicion =</span> <span class="fu">c</span>(<span class="st">"Fumador"</span>, <span class="st">"No fumador"</span>),</span>
<span id="cb6-159"><a href="#cb6-159" aria-hidden="true" tabindex="-1"></a>                  <span class="at">Grupo =</span> <span class="fu">c</span>(<span class="st">"Casos"</span>, <span class="st">"Controles"</span>)</span>
<span id="cb6-160"><a href="#cb6-160" aria-hidden="true" tabindex="-1"></a>                ))</span>
<span id="cb6-161"><a href="#cb6-161" aria-hidden="true" tabindex="-1"></a>tabla</span>
<span id="cb6-162"><a href="#cb6-162" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-163"><a href="#cb6-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-166"><a href="#cb6-166" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-167"><a href="#cb6-167" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> tabla[<span class="st">"Fumador"</span>, <span class="st">"Casos"</span>]</span>
<span id="cb6-168"><a href="#cb6-168" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> tabla[<span class="st">"Fumador"</span>, <span class="st">"Controles"</span>]</span>
<span id="cb6-169"><a href="#cb6-169" aria-hidden="true" tabindex="-1"></a>c_ <span class="ot">&lt;-</span> tabla[<span class="st">"No fumador"</span>, <span class="st">"Casos"</span>]</span>
<span id="cb6-170"><a href="#cb6-170" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> tabla[<span class="st">"No fumador"</span>, <span class="st">"Controles"</span>]</span>
<span id="cb6-171"><a href="#cb6-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-172"><a href="#cb6-172" aria-hidden="true" tabindex="-1"></a><span class="co"># Odds ratio</span></span>
<span id="cb6-173"><a href="#cb6-173" aria-hidden="true" tabindex="-1"></a>or <span class="ot">&lt;-</span> (a <span class="sc">*</span> d) <span class="sc">/</span> (b <span class="sc">*</span> c_)</span>
<span id="cb6-174"><a href="#cb6-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-175"><a href="#cb6-175" aria-hidden="true" tabindex="-1"></a><span class="co"># Error estándar del logaritmo de la OR (método de Woolf)</span></span>
<span id="cb6-176"><a href="#cb6-176" aria-hidden="true" tabindex="-1"></a>se_log_or <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="dv">1</span> <span class="sc">/</span> a <span class="sc">+</span> <span class="dv">1</span> <span class="sc">/</span> b <span class="sc">+</span> <span class="dv">1</span> <span class="sc">/</span> c_ <span class="sc">+</span> <span class="dv">1</span> <span class="sc">/</span> d)</span>
<span id="cb6-177"><a href="#cb6-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-178"><a href="#cb6-178" aria-hidden="true" tabindex="-1"></a><span class="co"># Intervalo de confianza al 95%</span></span>
<span id="cb6-179"><a href="#cb6-179" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="fl">0.975</span>)</span>
<span id="cb6-180"><a href="#cb6-180" aria-hidden="true" tabindex="-1"></a>ic_inferior <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">log</span>(or) <span class="sc">-</span> z <span class="sc">*</span> se_log_or)</span>
<span id="cb6-181"><a href="#cb6-181" aria-hidden="true" tabindex="-1"></a>ic_superior <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">log</span>(or) <span class="sc">+</span> z <span class="sc">*</span> se_log_or)</span>
<span id="cb6-182"><a href="#cb6-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-183"><a href="#cb6-183" aria-hidden="true" tabindex="-1"></a>resultado <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb6-184"><a href="#cb6-184" aria-hidden="true" tabindex="-1"></a>  <span class="at">medida =</span> <span class="st">"Odds Ratio"</span>,</span>
<span id="cb6-185"><a href="#cb6-185" aria-hidden="true" tabindex="-1"></a>  <span class="at">estimacion =</span> or,</span>
<span id="cb6-186"><a href="#cb6-186" aria-hidden="true" tabindex="-1"></a>  <span class="at">ic_95_inferior =</span> ic_inferior,</span>
<span id="cb6-187"><a href="#cb6-187" aria-hidden="true" tabindex="-1"></a>  <span class="at">ic_95_superior =</span> ic_superior</span>
<span id="cb6-188"><a href="#cb6-188" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-189"><a href="#cb6-189" aria-hidden="true" tabindex="-1"></a>resultado</span>
<span id="cb6-190"><a href="#cb6-190" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-191"><a href="#cb6-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-192"><a href="#cb6-192" aria-hidden="true" tabindex="-1"></a>El resultado coincide con el obtenido a mano: $OR=3.5$ con un intervalo de confianza al 95% de $(2.10,\ 5.84)$.</span>
<span id="cb6-193"><a href="#cb6-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-194"><a href="#cb6-194" aria-hidden="true" tabindex="-1"></a>Una forma habitual de representar gráficamente una odds ratio junto con su intervalo de confianza es el llamado _forest plot_, que muestra la estimación puntual y su incertidumbre en relación con la línea de referencia $OR=1$ (ausencia de asociación).</span>
<span id="cb6-195"><a href="#cb6-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-196"><a href="#cb6-196" aria-hidden="true" tabindex="-1"></a><span class="in">```{r forest-plot-or, fig.cap="Odds ratio del consumo de tabaco y su intervalo de confianza al 95%."}</span></span>
<span id="cb6-197"><a href="#cb6-197" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(resultado, <span class="fu">aes</span>(<span class="at">x =</span> or, <span class="at">y =</span> medida)) <span class="sc">+</span></span>
<span id="cb6-198"><a href="#cb6-198" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">1</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"grey40"</span>) <span class="sc">+</span></span>
<span id="cb6-199"><a href="#cb6-199" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbarh</span>(<span class="fu">aes</span>(<span class="at">xmin =</span> ic_95_inferior, <span class="at">xmax =</span> ic_95_superior), <span class="at">height =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb6-200"><a href="#cb6-200" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb6-201"><a href="#cb6-201" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>() <span class="sc">+</span></span>
<span id="cb6-202"><a href="#cb6-202" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb6-203"><a href="#cb6-203" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Odds Ratio (escala logarítmica)"</span>,</span>
<span id="cb6-204"><a href="#cb6-204" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="cn">NULL</span>,</span>
<span id="cb6-205"><a href="#cb6-205" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Tabaco y cáncer de pulmón"</span></span>
<span id="cb6-206"><a href="#cb6-206" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb6-207"><a href="#cb6-207" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb6-208"><a href="#cb6-208" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-209"><a href="#cb6-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-210"><a href="#cb6-210" aria-hidden="true" tabindex="-1"></a>El punto se sitúa claramente a la derecha de la línea de referencia $OR=1$, y todo el intervalo de confianza queda también por encima de ella, lo que confirma gráficamente que el consumo de tabaco está asociado de forma significativa con un mayor riesgo de cáncer de pulmón en esta muestra.</span>
<span id="cb6-211"><a href="#cb6-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-212"><a href="#cb6-212" aria-hidden="true" tabindex="-1"></a><span class="fu">## Casos y controles apareados</span></span>
<span id="cb6-213"><a href="#cb6-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-214"><a href="#cb6-214" aria-hidden="true" tabindex="-1"></a>En ocasiones, cada caso se _aparea_ (_matching_) con uno o varios controles que comparten con él ciertas características que se sabe o se sospecha que actúan como factores de confusión, como la edad, el sexo o el centro de reclutamiento. El objetivo del apareamiento es asegurar que casos y controles sean lo más comparables posible en esas variables, de forma que cualquier diferencia observada en la exposición sea más difícilmente atribuible a ellas. Por ejemplo, a cada caso de 55 años se le podrían asignar dos controles también de 55 años y del mismo sexo.</span>
<span id="cb6-215"><a href="#cb6-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-216"><a href="#cb6-216" aria-hidden="true" tabindex="-1"></a>El apareamiento tiene, sin embargo, un coste analítico: la tabla $2\times 2$ simple ya no resulta válida para comparar los grupos, porque las observaciones dejan de ser independientes (cada caso está ligado a su control o controles concretos). El análisis de datos apareados requiere métodos estadísticos específicos, como el **test de McNemar** para el caso de un control por caso, o la regresión logística condicional cuando hay varios controles por caso, que quedan fuera del alcance de este capítulo introductorio.</span>
<span id="cb6-217"><a href="#cb6-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-218"><a href="#cb6-218" aria-hidden="true" tabindex="-1"></a><span class="fu">## Cuándo utilizar este diseño</span></span>
<span id="cb6-219"><a href="#cb6-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-220"><a href="#cb6-220" aria-hidden="true" tabindex="-1"></a>El estudio de casos y controles es la opción de elección cuando la enfermedad o el evento de interés es raro, cuando su periodo de latencia es muy largo, o cuando se dispone de poco tiempo y presupuesto para completar la investigación. También resulta muy útil como paso exploratorio para generar hipótesis sobre múltiples posibles exposiciones a la vez, antes de invertir en un diseño más costoso. Cuando, por el contrario, es la **exposición** la que resulta rara en la población (y no la enfermedad), suele ser preferible recurrir a un <span class="co">[</span><span class="ot">estudio de cohortes</span><span class="co">](04-estudios-cohortes.qmd)</span>, que garantiza un número suficiente de expuestos y permite además calcular directamente incidencias y riesgos relativos. En la práctica, ambos diseños se consideran complementarios dentro de la investigación epidemiológica observacional.</span>
</code></pre></div><button title="Copiar al portapapeles" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/asalber/estadistica-tipos-estudios/edit/main/05-estudios-casos-controles.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li><li><a href="https://github.com/asalber/estadistica-tipos-estudios/issues/new" class="toc-action"><i class="bi empty"></i>Informar de un problema</a></li></ul></div></div></div></footer></body></html>