<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>9&nbsp; Encuestas y diseño de muestreo – Tipos de Estudios Estadísticos</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./10-seleccion-contraste.html" rel="next">
<link href="./08-estudios-cuasiexperimentales.html" rel="prev">
<link href="./img/logos/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-3419ea62b3ca2d77d3d547f86109e84e.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-eaeb381c6b7494c50009502241a4985c.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-b050db56f2b97c639b7ebc2cf71c06d7.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-5e50218c20039713403b52e69b91eb5d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="9&nbsp; Encuestas y diseño de muestreo – Tipos de Estudios Estadísticos">
<meta property="og:description" content="">
<meta property="og:image" content="09-encuestas-muestreo_files/figure-html/grafico-tamano-muestral-1.png">
<meta property="og:site_name" content="Tipos de Estudios Estadísticos">
<meta name="twitter:title" content="9&nbsp; Encuestas y diseño de muestreo – Tipos de Estudios Estadísticos">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="09-encuestas-muestreo_files/figure-html/grafico-tamano-muestral-1.png">
<meta name="twitter:site" content="@aprendeconalf">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating quarto-dark"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = true;
    const darkModeDefault = authorPrefersDark;
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./02-estudios-descriptivos.html">Diseños de estudio</a></li><li class="breadcrumb-item"><a href="./09-encuestas-muestreo.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Encuestas y diseño de muestreo</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./img/logos/aprendeconalf.png" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="./img/logos/aprendeconalf.png" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Tipos de Estudios Estadísticos</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://aprendeconalf.es" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-house-fill"></i></a>
    <a href="https://github.com/asalber/estadistica-tipos-estudios" title="Ejecutar el código" class="quarto-navigation-tool px-1" aria-label="Ejecutar el código"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./estadistica-tipos-estudios.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./estadistica-tipos-estudios.epub">
              <i class="bi bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
      </ul>
    </div>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-1" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-1">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo oscuro"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-introduccion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción a los tipos de estudios estadísticos</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Diseños de estudio</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-estudios-descriptivos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Estudios descriptivos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-estudios-transversales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Estudios transversales</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-estudios-cohortes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Estudios de cohortes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-estudios-casos-controles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Estudios de casos y controles</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-estudios-ecologicos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Estudios ecológicos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-estudios-experimentales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Estudios experimentales</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-estudios-cuasiexperimentales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Estudios cuasiexperimentales</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-encuestas-muestreo.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Encuestas y diseño de muestreo</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Selección del contraste estadístico</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-seleccion-contraste.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Selección del contraste estadístico</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-contrastes-una-poblacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Contrastes para una población</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-contrastes-dos-poblaciones-independientes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Contrastes para dos poblaciones independientes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-contrastes-dos-poblaciones-pareadas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Contrastes para dos poblaciones pareadas</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-contrastes-mas-dos-poblaciones-independientes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Contrastes para más de dos poblaciones independientes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-contrastes-medidas-repetidas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Contrastes para más de dos poblaciones relacionadas (medidas repetidas)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-relacion-entre-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Relación y predicción entre dos variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Indice de contenidos</h2>
   
  <ul>
  <li><a href="#definición-y-características" id="toc-definición-y-características" class="nav-link active" data-scroll-target="#definición-y-características"><span class="header-section-number">9.1</span> Definición y características</a>
  <ul class="collapse">
  <li><a href="#muestreo-aleatorio-simple-mas" id="toc-muestreo-aleatorio-simple-mas" class="nav-link" data-scroll-target="#muestreo-aleatorio-simple-mas"><span class="header-section-number">9.1.1</span> Muestreo aleatorio simple (MAS)</a></li>
  <li><a href="#muestreo-estratificado" id="toc-muestreo-estratificado" class="nav-link" data-scroll-target="#muestreo-estratificado"><span class="header-section-number">9.1.2</span> Muestreo estratificado</a></li>
  <li><a href="#muestreo-por-conglomerados" id="toc-muestreo-por-conglomerados" class="nav-link" data-scroll-target="#muestreo-por-conglomerados"><span class="header-section-number">9.1.3</span> Muestreo por conglomerados</a></li>
  <li><a href="#muestreo-sistemático" id="toc-muestreo-sistemático" class="nav-link" data-scroll-target="#muestreo-sistemático"><span class="header-section-number">9.1.4</span> Muestreo sistemático</a></li>
  </ul></li>
  <li><a href="#ventajas-e-inconvenientes" id="toc-ventajas-e-inconvenientes" class="nav-link" data-scroll-target="#ventajas-e-inconvenientes"><span class="header-section-number">9.2</span> Ventajas e inconvenientes</a></li>
  <li><a href="#medidas-propias-de-este-diseño" id="toc-medidas-propias-de-este-diseño" class="nav-link" data-scroll-target="#medidas-propias-de-este-diseño"><span class="header-section-number">9.3</span> Medidas propias de este diseño</a>
  <ul class="collapse">
  <li><a href="#error-de-muestreo" id="toc-error-de-muestreo" class="nav-link" data-scroll-target="#error-de-muestreo"><span class="header-section-number">9.3.1</span> Error de muestreo</a></li>
  <li><a href="#tamaño-muestral-necesario" id="toc-tamaño-muestral-necesario" class="nav-link" data-scroll-target="#tamaño-muestral-necesario"><span class="header-section-number">9.3.2</span> Tamaño muestral necesario</a></li>
  </ul></li>
  <li><a href="#realización-con-r" id="toc-realización-con-r" class="nav-link" data-scroll-target="#realización-con-r"><span class="header-section-number">9.4</span> Realización con R</a>
  <ul class="collapse">
  <li><a href="#cálculo-del-tamaño-muestral-necesario" id="toc-cálculo-del-tamaño-muestral-necesario" class="nav-link" data-scroll-target="#cálculo-del-tamaño-muestral-necesario"><span class="header-section-number">9.4.1</span> Cálculo del tamaño muestral necesario</a></li>
  <li><a href="#comparación-entre-muestreo-aleatorio-simple-y-muestreo-estratificado" id="toc-comparación-entre-muestreo-aleatorio-simple-y-muestreo-estratificado" class="nav-link" data-scroll-target="#comparación-entre-muestreo-aleatorio-simple-y-muestreo-estratificado"><span class="header-section-number">9.4.2</span> Comparación entre muestreo aleatorio simple y muestreo estratificado</a></li>
  </ul></li>
  <li><a href="#cuándo-utilizar-este-diseño" id="toc-cuándo-utilizar-este-diseño" class="nav-link" data-scroll-target="#cuándo-utilizar-este-diseño"><span class="header-section-number">9.5</span> Cuándo utilizar este diseño</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/asalber/estadistica-tipos-estudios/edit/main/09-encuestas-muestreo.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li><li><a href="https://github.com/asalber/estadistica-tipos-estudios/issues/new" class="toc-action"><i class="bi empty"></i>Informar de un problema</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./02-estudios-descriptivos.html">Diseños de estudio</a></li><li class="breadcrumb-item"><a href="./09-encuestas-muestreo.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Encuestas y diseño de muestreo</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Encuestas y diseño de muestreo</span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Código</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Enseñar el código</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Esconder el código</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">Ver el código</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Como se adelantó en el <a href="./01-introduccion.html">capítulo de introducción</a>, la encuesta es probablemente el instrumento de recogida de datos más extendido en estadística aplicada: consiste en seleccionar una muestra de individuos de una población y medir sobre ellos, mediante un cuestionario u otro procedimiento de observación, una o varias variables de interés (opiniones, hábitos, características sociodemográficas, intención de voto, etc.). En la mayoría de los casos comparte con el <a href="./03-estudios-transversales.html">estudio transversal</a> la misma lógica temporal, ya que las variables se registran en un único momento, sobre una muestra tomada de la población general sin condicionar la selección a ninguna exposición o resultado previo. Sin embargo, mientras que en los capítulos anteriores el foco estaba en el tipo de diseño observacional o experimental, en este capítulo el foco se traslada a una cuestión transversal a todos ellos y crítica para la validez de cualquier estudio: <strong>cómo se selecciona la muestra</strong> a partir de la cual se pretende estimar o inferir características de toda la población.</p>
<section id="definición-y-características" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="definición-y-características"><span class="header-section-number">9.1</span> Definición y características</h2>
<div id="def-encuestas-encuesta-estadistica" class="theorem definition">
<p><span class="theorem-title"><strong>Definición 9.1 (Encuesta estadística)</strong></span> Una <em>encuesta estadística</em> es un procedimiento de investigación que consiste en seleccionar una muestra de individuos de una población, mediante un método de muestreo determinado, y recoger información sobre ellos (habitualmente a través de un cuestionario) con el fin de estimar características, opiniones o comportamientos de la población de la que proceden.</p>
</div>
<p>La validez de las conclusiones de una encuesta depende, en gran medida, de que la muestra seleccionada sea representativa de la población objetivo. Esto exige, en primer lugar, disponer de un marco muestral adecuado.</p>
<div id="def-encuestas-marco-muestral" class="theorem definition">
<p><span class="theorem-title"><strong>Definición 9.2 (Marco muestral)</strong></span> El <em>marco muestral</em> (en inglés, <em>sampling frame</em>) es el listado, registro o procedimiento que permite identificar y acceder a todos los elementos de la población objetivo, de manera que cada uno de ellos pueda ser seleccionado para formar parte de la muestra.</p>
</div>
<p>Un marco muestral incompleto o desactualizado (por ejemplo, un censo de población antiguo, o un listado telefónico que excluye a quienes solo disponen de móvil) introduce un sesgo de cobertura, ya que ciertos segmentos de la población tienen probabilidad nula o muy baja de ser seleccionados, con independencia de lo riguroso que sea el método de muestreo empleado posteriormente.</p>
<p>Cuando se dispone de un marco muestral adecuado, existen varios diseños de <strong>muestreo probabilístico</strong>, en los que cada elemento de la población tiene una probabilidad conocida (y no nula) de ser seleccionado, lo que permite calcular la precisión de las estimaciones y generalizarlas a la población con garantías estadísticas. Los principales son los siguientes.</p>
<section id="muestreo-aleatorio-simple-mas" class="level3" data-number="9.1.1">
<h3 data-number="9.1.1" class="anchored" data-anchor-id="muestreo-aleatorio-simple-mas"><span class="header-section-number">9.1.1</span> Muestreo aleatorio simple (MAS)</h3>
<p>En el <em>muestreo aleatorio simple</em> cada elemento de la población tiene la misma probabilidad de ser seleccionado, y la selección de cada individuo es independiente de la de los demás. Es el diseño de referencia, el más sencillo de analizar, pero exige disponer de un marco muestral completo y puede resultar poco eficiente cuando la población es muy heterogénea o está muy dispersa geográficamente.</p>
</section>
<section id="muestreo-estratificado" class="level3" data-number="9.1.2">
<h3 data-number="9.1.2" class="anchored" data-anchor-id="muestreo-estratificado"><span class="header-section-number">9.1.2</span> Muestreo estratificado</h3>
<p>En el <em>muestreo estratificado</em> la población se divide previamente en subgrupos o <strong>estratos</strong>, internamente lo más homogéneos posible respecto a la variable de interés y heterogéneos entre sí (por ejemplo, comunidades autónomas, tramos de edad o tipo de centro educativo), y dentro de cada estrato se selecciona una muestra aleatoria simple de manera independiente. Cuando el tamaño de la muestra en cada estrato se reparte en proporción al peso de dicho estrato en la población, se habla de <strong>afijación proporcional</strong>. Al garantizar la presencia de todos los estratos en la proporción adecuada, este diseño suele producir estimaciones más precisas que el muestreo aleatorio simple, para un mismo tamaño de muestra, siempre que los estratos sean realmente homogéneos internamente.</p>
</section>
<section id="muestreo-por-conglomerados" class="level3" data-number="9.1.3">
<h3 data-number="9.1.3" class="anchored" data-anchor-id="muestreo-por-conglomerados"><span class="header-section-number">9.1.3</span> Muestreo por conglomerados</h3>
<p>En el <em>muestreo por conglomerados</em> (o <em>por clusters</em>) la población se divide en grupos naturales o preexistentes (conglomerados), como colegios, manzanas de una ciudad o centros de salud, y en lugar de seleccionar individuos se seleccionan aleatoriamente algunos conglomerados completos, incluyendo a todos sus miembros en la muestra (o, en su versión bietápica, seleccionando después una submuestra dentro de cada conglomerado elegido). Resulta especialmente útil cuando no existe un marco muestral de individuos pero sí de conglomerados, y reduce mucho el coste logístico al concentrar el trabajo de campo en unas pocas zonas. A cambio, suele perder precisión respecto al muestreo aleatorio simple, ya que los individuos de un mismo conglomerado tienden a parecerse entre sí.</p>
</section>
<section id="muestreo-sistemático" class="level3" data-number="9.1.4">
<h3 data-number="9.1.4" class="anchored" data-anchor-id="muestreo-sistemático"><span class="header-section-number">9.1.4</span> Muestreo sistemático</h3>
<p>En el <em>muestreo sistemático</em> se ordena el marco muestral (por ejemplo, un listado de <span class="math inline">\(N\)</span> individuos), se calcula un intervalo de selección <span class="math inline">\(k = N/n\)</span> (siendo <span class="math inline">\(n\)</span> el tamaño de muestra deseado), se elige aleatoriamente un punto de partida entre <span class="math inline">\(1\)</span> y <span class="math inline">\(k\)</span>, y a partir de él se selecciona cada <span class="math inline">\(k\)</span>-ésimo elemento de la lista. Es fácil de aplicar y, cuando el listado no sigue ningún patrón periódico relacionado con la variable de interés, suele proporcionar resultados muy similares a los del muestreo aleatorio simple.</p>
<p>Además de estos diseños probabilísticos, existen métodos de <strong>muestreo no probabilístico</strong>, como el muestreo por conveniencia (se selecciona a los individuos más accesibles) o el muestreo en bola de nieve (los participantes reclutan a su vez a otros participantes). Estos métodos son más rápidos y baratos, pero al no conocerse la probabilidad de selección de cada individuo no permiten calcular la precisión de las estimaciones ni generalizar los resultados a la población con garantías estadísticas, por lo que su uso queda habitualmente restringido a estudios exploratorios o poblaciones muy difíciles de acceder.</p>
</section>
</section>
<section id="ventajas-e-inconvenientes" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="ventajas-e-inconvenientes"><span class="header-section-number">9.2</span> Ventajas e inconvenientes</h2>
<ul>
<li><strong>Muestreo aleatorio simple</strong>: es el más sencillo de diseñar y analizar, pero exige un marco muestral completo de individuos y puede resultar poco eficiente (mayor error para el mismo tamaño de muestra) cuando la población es heterogénea.</li>
<li><strong>Muestreo estratificado</strong>: mejora la precisión frente al muestreo aleatorio simple cuando existen variables (estratos) fuertemente relacionadas con la variable de interés, y garantiza representación de todos los grupos relevantes; a cambio, requiere conocer de antemano el valor de la variable de estratificación para toda la población, lo que no siempre es posible.</li>
<li><strong>Muestreo por conglomerados</strong>: es el más económico y logísticamente viable cuando la población está muy dispersa o no existe un marco muestral de individuos, pero suele ser el menos preciso, ya que los elementos de un mismo conglomerado tienden a ser parecidos entre sí (baja variabilidad interna, alta variabilidad entre conglomerados).</li>
<li><strong>Muestreo sistemático</strong>: es muy fácil de implementar sobre un listado ordenado y suele comportarse como el muestreo aleatorio simple, pero puede introducir sesgos graves si el listado presenta algún patrón periódico que coincida con el intervalo de selección <span class="math inline">\(k\)</span>.</li>
<li><strong>Muestreo no probabilístico</strong>: es el más rápido y barato, y en ocasiones la única opción viable (por ejemplo, para poblaciones ocultas o de difícil acceso), pero no permite cuantificar el error de muestreo ni generalizar los resultados a la población con garantías estadísticas.</li>
</ul>
</section>
<section id="medidas-propias-de-este-diseño" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="medidas-propias-de-este-diseño"><span class="header-section-number">9.3</span> Medidas propias de este diseño</h2>
<p>Además de las medidas descriptivas habituales (proporciones, medias, etc.), calculadas ahora ponderando por el diseño muestral empleado, dos cantidades son especialmente características del diseño de encuestas: el error de muestreo de una estimación y el tamaño muestral necesario para lograr una precisión determinada.</p>
<section id="error-de-muestreo" class="level3" data-number="9.3.1">
<h3 data-number="9.3.1" class="anchored" data-anchor-id="error-de-muestreo"><span class="header-section-number">9.3.1</span> Error de muestreo</h3>
<div id="def-encuestas-error-muestreo" class="theorem definition">
<p><span class="theorem-title"><strong>Definición 9.3 (Error de muestreo)</strong></span> Dada una muestra aleatoria simple de tamaño <span class="math inline">\(n\)</span> en la que se ha observado una proporción muestral <span class="math inline">\(\hat p\)</span> de individuos que presentan una determinada característica, el <em>error de muestreo</em> (o margen de error) de <span class="math inline">\(\hat p\)</span> para un nivel de confianza <span class="math inline">\(1-\alpha\)</span> se define como</p>
<p><span class="math display">\[e = z_{\alpha/2}\sqrt{\frac{\hat p(1-\hat p)}{n}}\]</span></p>
<p>donde <span class="math inline">\(z_{\alpha/2}\)</span> es el valor crítico de la distribución normal estándar que deja una probabilidad <span class="math inline">\(\alpha/2\)</span> a su derecha.</p>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importante
</div>
</div>
<div class="callout-body-container callout-body">
<p>El error de muestreo es siempre un número no negativo,</p>
<p><span class="math display">\[e \geq 0,\]</span></p>
<p>y disminuye a medida que aumenta el tamaño de muestra <span class="math inline">\(n\)</span>, concretamente en proporción a <span class="math inline">\(1/\sqrt{n}\)</span>: para reducir el error a la mitad es necesario cuadruplicar el tamaño de muestra.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Interpretación">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Interpretación
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>El error de muestreo cuantifica cuánto puede diferir, con la confianza especificada, la proporción muestral <span class="math inline">\(\hat p\)</span> de la verdadera proporción poblacional <span class="math inline">\(p\)</span>, exclusivamente por el hecho de trabajar con una muestra y no con toda la población.</li>
<li>El intervalo <span class="math inline">\((\hat p - e,\ \hat p + e)\)</span> es precisamente el intervalo de confianza al nivel <span class="math inline">\(1-\alpha\)</span> para la proporción poblacional <span class="math inline">\(p\)</span>.</li>
<li>El error de muestreo no recoge otras fuentes de error ajenas al azar, como el sesgo de no respuesta, el sesgo de cobertura del marco muestral o los errores de medición del cuestionario, que pueden ser tanto o más importantes que el propio error de muestreo.</li>
</ul>
</div>
</div>
</section>
<section id="tamaño-muestral-necesario" class="level3" data-number="9.3.2">
<h3 data-number="9.3.2" class="anchored" data-anchor-id="tamaño-muestral-necesario"><span class="header-section-number">9.3.2</span> Tamaño muestral necesario</h3>
<p>En la práctica, la pregunta habitual no es “¿qué error tiene mi muestra?” sino la inversa: “¿qué tamaño de muestra necesito para que el error no supere un determinado valor?”. Despejando <span class="math inline">\(n\)</span> de la fórmula del error de muestreo se obtiene la siguiente expresión.</p>
<div id="def-encuestas-tamano-muestral" class="theorem definition">
<p><span class="theorem-title"><strong>Definición 9.4 (Tamaño muestral necesario)</strong></span> Para estimar una proporción poblacional <span class="math inline">\(p\)</span> con un error de muestreo máximo <span class="math inline">\(e\)</span> y un nivel de confianza <span class="math inline">\(1-\alpha\)</span>, el tamaño de muestra necesario, suponiendo muestreo aleatorio simple sobre una población de tamaño muy superior a la muestra, es</p>
<p><span class="math display">\[n = \frac{z_{\alpha/2}^2\, p(1-p)}{e^2}\]</span></p>
<p>donde <span class="math inline">\(p\)</span> es un valor aproximado (de un estudio previo o piloto) de la proporción que se quiere estimar; si no se dispone de tal valor, se toma <span class="math inline">\(p=0.5\)</span>, ya que es el valor que maximiza <span class="math inline">\(p(1-p)\)</span> y por tanto produce el tamaño de muestra más conservador (el mayor posible).</p>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importante
</div>
</div>
<div class="callout-body-container callout-body">
<p>Cuando la población tiene un tamaño finito y conocido <span class="math inline">\(N\)</span> que no es muy superior al tamaño de muestra calculado, puede aplicarse el <em>factor de corrección para poblaciones finitas</em>,</p>
<p><span class="math display">\[n_{ajustado} = \frac{n}{1+\dfrac{n-1}{N}},\]</span></p>
<p>que reduce ligeramente el tamaño de muestra necesario. En la práctica, cuando <span class="math inline">\(N\)</span> es grande frente a <span class="math inline">\(n\)</span> (por ejemplo, encuestas sobre la población de un país o una ciudad grande), esta corrección apenas tiene efecto y suele omitirse.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Interpretación">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Interpretación
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>El tamaño muestral necesario aumenta con el nivel de confianza exigido (mayor <span class="math inline">\(z_{\alpha/2}\)</span>) y disminuye rápidamente al relajar la precisión exigida (mayor <span class="math inline">\(e\)</span>), ya que <span class="math inline">\(n\)</span> depende del cuadrado de <span class="math inline">\(e\)</span> en el denominador.</li>
<li>El tamaño muestral necesario es máximo cuando <span class="math inline">\(p=0.5\)</span> y disminuye a medida que <span class="math inline">\(p\)</span> se aleja de <span class="math inline">\(0.5\)</span> hacia <span class="math inline">\(0\)</span> o hacia <span class="math inline">\(1\)</span>, ya que fenómenos muy raros o muy comunes son, en cierto sentido, más fáciles de acotar con precisión.</li>
<li>Esta fórmula corresponde al muestreo aleatorio simple; en diseños estratificados, por conglomerados o sistemáticos, el tamaño necesario puede ser menor o mayor, en función de si el diseño mejora o empeora la precisión respecto al muestreo aleatorio simple.</li>
</ul>
</div>
</div>
<div id="exm-encuestas-tamano-muestral" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 9.1</strong></span> Se quiere diseñar una encuesta para estimar la proporción de la población de una ciudad que está a favor de un determinado proyecto urbanístico, con un error de muestreo máximo de <span class="math inline">\(e=0.03\)</span> (tres puntos porcentuales) y un nivel de confianza del <span class="math inline">\(95\%\)</span> (<span class="math inline">\(\alpha=0.05\)</span>, por lo que <span class="math inline">\(z_{\alpha/2}=1.96\)</span>). Al no disponer de información previa sobre la proporción real, se toma el valor más conservador, <span class="math inline">\(p=0.5\)</span>. El tamaño de muestra necesario es</p>
<p><span class="math display">\[n = \frac{z_{\alpha/2}^2\, p(1-p)}{e^2} = \frac{1.96^2 \times 0.5 \times 0.5}{0.03^2} = \frac{0.9604}{0.0009} \approx 1067.1.\]</span></p>
<p>Redondeando hacia arriba, se necesitaría una muestra de <span class="math inline">\(n=1068\)</span> individuos para garantizar, con una confianza del <span class="math inline">\(95\%\)</span>, que la proporción estimada no se aleje de la verdadera proporción poblacional en más de tres puntos porcentuales.</p>
</div>
</section>
</section>
<section id="realización-con-r" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="realización-con-r"><span class="header-section-number">9.4</span> Realización con R</h2>
<section id="cálculo-del-tamaño-muestral-necesario" class="level3" data-number="9.4.1">
<h3 data-number="9.4.1" class="anchored" data-anchor-id="cálculo-del-tamaño-muestral-necesario"><span class="header-section-number">9.4.1</span> Cálculo del tamaño muestral necesario</h3>
<p>En primer lugar se reproduce en R el cálculo manual del <a href="#exm-encuestas-tamano-muestral" class="quarto-xref">Ejemplo&nbsp;<span>9.1</span></a>, obteniendo el valor crítico <span class="math inline">\(z_{\alpha/2}\)</span> con <code>qnorm()</code> y aplicando directamente la fórmula del tamaño muestral:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>calcular_n <span class="ot">&lt;-</span> <span class="cf">function</span>(e, <span class="at">confianza =</span> <span class="fl">0.95</span>, <span class="at">p =</span> <span class="fl">0.5</span>) {</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  alpha <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> confianza</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  z <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="dv">1</span> <span class="sc">-</span> alpha <span class="sc">/</span> <span class="dv">2</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> (z<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> p <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p)) <span class="sc">/</span> e<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ceiling</span>(n)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>n_necesario <span class="ot">&lt;-</span> <span class="fu">calcular_n</span>(<span class="at">e =</span> <span class="fl">0.03</span>, <span class="at">confianza =</span> <span class="fl">0.95</span>, <span class="at">p =</span> <span class="fl">0.5</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>n_necesario</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1068</code></pre>
</div>
</div>
<p>El resultado, 1068 individuos, coincide con el obtenido a mano. A continuación se representa cómo varía el tamaño de muestra necesario en función del error de muestreo admitido, para un nivel de confianza del 95%:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>errores <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">e =</span> <span class="fu">seq</span>(<span class="fl">0.01</span>, <span class="fl">0.10</span>, <span class="at">by =</span> <span class="fl">0.005</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">n =</span> <span class="fu">map_dbl</span>(e, <span class="sc">~</span> <span class="fu">calcular_n</span>(.x, <span class="at">confianza =</span> <span class="fl">0.95</span>, <span class="at">p =</span> <span class="fl">0.5</span>)))</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(errores, <span class="fu">aes</span>(<span class="at">x =</span> e, <span class="at">y =</span> n)) <span class="sc">+</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>()) <span class="sc">+</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">comma_format</span>()) <span class="sc">+</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Error de muestreo admitido"</span>,</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Tamaño de muestra necesario"</span>,</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Relación entre precisión exigida y tamaño de muestra"</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09-encuestas-muestreo_files/figure-html/grafico-tamano-muestral-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Tamaño de muestra necesario en función del error de muestreo admitido (confianza del 95%, p = 0.5).</figcaption>
</figure>
</div>
</div>
</div>
<p>Como cabía esperar, el tamaño de muestra necesario crece muy rápidamente a medida que se exige un error de muestreo menor, debido a la relación cuadrática entre ambas cantidades.</p>
</section>
<section id="comparación-entre-muestreo-aleatorio-simple-y-muestreo-estratificado" class="level3" data-number="9.4.2">
<h3 data-number="9.4.2" class="anchored" data-anchor-id="comparación-entre-muestreo-aleatorio-simple-y-muestreo-estratificado"><span class="header-section-number">9.4.2</span> Comparación entre muestreo aleatorio simple y muestreo estratificado</h3>
<p>Para comparar la precisión del muestreo aleatorio simple (MAS) frente al muestreo estratificado, se simula una “población” de <span class="math inline">\(N=4000\)</span> personas repartidas en 4 regiones, con una opinión binaria (a favor / en contra de una medida) cuya prevalencia varía sustancialmente de una región a otra, de forma que la región constituye un buen criterio de estratificación:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">4000</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>poblacion <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">id =</span> <span class="dv">1</span><span class="sc">:</span>N,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">region =</span> <span class="fu">sample</span>(</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(<span class="st">"Norte"</span>, <span class="st">"Sur"</span>, <span class="st">"Este"</span>, <span class="st">"Oeste"</span>),</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> N,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">replace =</span> <span class="cn">TRUE</span>,</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">prob =</span> <span class="fu">c</span>(<span class="fl">0.30</span>, <span class="fl">0.25</span>, <span class="fl">0.25</span>, <span class="fl">0.20</span>)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="co"># La probabilidad de estar a favor depende fuertemente de la región</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>prob_favor <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">Norte =</span> <span class="fl">0.75</span>, <span class="at">Sur =</span> <span class="fl">0.30</span>, <span class="at">Este =</span> <span class="fl">0.55</span>, <span class="at">Oeste =</span> <span class="fl">0.40</span>)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>poblacion <span class="ot">&lt;-</span> poblacion <span class="sc">|&gt;</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_favor =</span> prob_favor[region],</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">opinion =</span> <span class="fu">rbinom</span>(N, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> p_favor),</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">opinion =</span> <span class="fu">factor</span>(opinion, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"En contra"</span>, <span class="st">"A favor"</span>))</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>poblacion</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4,000 × 4
      id region p_favor opinion  
   &lt;int&gt; &lt;chr&gt;    &lt;dbl&gt; &lt;fct&gt;    
 1     1 Sur       0.3  En contra
 2     2 Sur       0.3  En contra
 3     3 Norte     0.75 A favor  
 4     4 Norte     0.75 A favor  
 5     5 Sur       0.3  En contra
 6     6 Norte     0.75 A favor  
 7     7 Este      0.55 A favor  
 8     8 Oeste     0.4  A favor  
 9     9 Norte     0.75 A favor  
10    10 Sur       0.3  A favor  
# ℹ 3,990 more rows</code></pre>
</div>
</div>
<p>La proporción real de personas a favor en el conjunto de la población (el parámetro que se desea estimar) es:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>p_poblacional <span class="ot">&lt;-</span> <span class="fu">mean</span>(poblacion<span class="sc">$</span>opinion <span class="sc">==</span> <span class="st">"A favor"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>p_poblacional</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.51325</code></pre>
</div>
</div>
<p>A partir de esta población se extrae, en primer lugar, una muestra aleatoria simple de <span class="math inline">\(n=1068\)</span> individuos:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>muestra_mas <span class="ot">&lt;-</span> poblacion <span class="sc">|&gt;</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n =</span> n_necesario)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>p_mas <span class="ot">&lt;-</span> <span class="fu">mean</span>(muestra_mas<span class="sc">$</span>opinion <span class="sc">==</span> <span class="st">"A favor"</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>p_mas</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5065543</code></pre>
</div>
</div>
<p>A continuación se extrae una muestra estratificada por región, con afijación proporcional, del mismo tamaño total aproximado: se calcula la proporción que representa cada región en la población y se selecciona ese mismo porcentaje dentro de cada estrato:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>prop_muestral <span class="ot">&lt;-</span> n_necesario <span class="sc">/</span> N</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>muestra_estratificada <span class="ot">&lt;-</span> poblacion <span class="sc">|&gt;</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(region) <span class="sc">|&gt;</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">prop =</span> prop_muestral) <span class="sc">|&gt;</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(muestra_estratificada)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1067</code></pre>
</div>
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>p_estratificado <span class="ot">&lt;-</span> <span class="fu">mean</span>(muestra_estratificada<span class="sc">$</span>opinion <span class="sc">==</span> <span class="st">"A favor"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>p_estratificado</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.5126523</code></pre>
</div>
</div>
<p>Se comprueba que la muestra estratificada respeta, aproximadamente, el peso de cada región en la población:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>muestra_estratificada <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(region) <span class="sc">|&gt;</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">proporcion_muestra =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  region     n proporcion_muestra
  &lt;chr&gt;  &lt;int&gt;              &lt;dbl&gt;
1 Este     268              0.251
2 Norte    322              0.302
3 Oeste    205              0.192
4 Sur      272              0.255</code></pre>
</div>
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>poblacion <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(region) <span class="sc">|&gt;</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">proporcion_poblacion =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  region     n proporcion_poblacion
  &lt;chr&gt;  &lt;int&gt;                &lt;dbl&gt;
1 Este    1004                0.251
2 Norte   1207                0.302
3 Oeste    769                0.192
4 Sur     1020                0.255</code></pre>
</div>
</div>
<p>Por último, se comparan gráficamente las tres proporciones: la real de la población y las estimadas por cada uno de los dos métodos de muestreo.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>comparacion <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">metodo =</span> <span class="fu">c</span>(<span class="st">"Población"</span>, <span class="st">"MAS"</span>, <span class="st">"Estratificado"</span>),</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">proporcion =</span> <span class="fu">c</span>(p_poblacional, p_mas, p_estratificado)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">metodo =</span> <span class="fu">factor</span>(metodo, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Población"</span>, <span class="st">"MAS"</span>, <span class="st">"Estratificado"</span>)))</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(comparacion, <span class="fu">aes</span>(<span class="at">x =</span> metodo, <span class="at">y =</span> proporcion, <span class="at">fill =</span> metodo)) <span class="sc">+</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> p_poblacional, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"gray30"</span>) <span class="sc">+</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>()) <span class="sc">+</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set2"</span>) <span class="sc">+</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Proporción a favor"</span>,</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Estimación de la proporción según el diseño de muestreo"</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09-encuestas-muestreo_files/figure-html/grafico-comparacion-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Proporción de personas a favor de la medida: valor poblacional real frente a las estimaciones por muestreo aleatorio simple y por muestreo estratificado.</figcaption>
</figure>
</div>
</div>
</div>
<p>En esta simulación, la proporción real de personas a favor en la población es del 51.3%, mientras que la muestra aleatoria simple estima un 50.7% y la muestra estratificada un 51.3%. Dado que la región está fuertemente relacionada con la opinión (los estratos son internamente bastante homogéneos) y que la afijación proporcional garantiza que cada región esté representada en su peso exacto, cabe esperar que, en promedio y a lo largo de repeticiones del muestreo, la estimación estratificada se aproxime más a la proporción poblacional que la del muestreo aleatorio simple, cuya composición por regiones puede variar de una muestra a otra por puro azar. Este es precisamente el motivo por el que, siempre que se disponga de una variable de estratificación adecuada, el muestreo estratificado suele preferirse al muestreo aleatorio simple en las encuestas reales.</p>
</section>
</section>
<section id="cuándo-utilizar-este-diseño" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="cuándo-utilizar-este-diseño"><span class="header-section-number">9.5</span> Cuándo utilizar este diseño</h2>
<p>El diseño de muestreo no es un tipo de estudio alternativo a los descritos en los capítulos anteriores, sino una dimensión transversal a todos ellos: tanto un <a href="./02-estudios-descriptivos.html">estudio descriptivo</a> como un <a href="./03-estudios-transversales.html">estudio transversal</a>, un <a href="./04-estudios-cohortes.html">estudio de cohortes</a> o un ensayo <a href="./07-estudios-experimentales.html">experimental</a> necesitan seleccionar en algún momento una muestra de la población, y la calidad de ese muestreo condiciona directamente la validez de las conclusiones que se extraigan. Conviene prestar especial atención al diseño muestral, y en particular optar por el muestreo estratificado o por conglomerados frente al muestreo aleatorio simple, cuando la población es muy heterogénea, cuando existen variables conocidas fuertemente relacionadas con el fenómeno de interés, o cuando el coste de acceder a los individuos varía mucho según su localización o su pertenencia a un determinado grupo. Un cálculo previo del tamaño muestral necesario, en función de la precisión exigida y de los recursos disponibles, es también un paso imprescindible en la planificación de cualquier estudio, se trate de una encuesta de opinión, un estudio epidemiológico o un ensayo clínico. En definitiva, ningún análisis estadístico posterior, por sofisticado que sea, puede compensar una muestra mal seleccionada: la calidad del diseño muestral es, junto con el propio diseño del estudio, uno de los pilares sobre los que se sostiene la validez de cualquier investigación estadística.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./08-estudios-cuasiexperimentales.html" class="pagination-link" aria-label="Estudios cuasiexperimentales">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Estudios cuasiexperimentales</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./10-seleccion-contraste.html" class="pagination-link" aria-label="Selección del contraste estadístico">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Selección del contraste estadístico</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Ejecutar el código</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> Encuestas y diseño de muestreo</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="an">lang:</span><span class="co"> es</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="in">```{r setup, include=FALSE}</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">message =</span> <span class="cn">FALSE</span>, <span class="at">warning =</span> <span class="cn">FALSE</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>Como se adelantó en el <span class="co">[</span><span class="ot">capítulo de introducción</span><span class="co">](01-introduccion.qmd)</span>, la encuesta es probablemente el instrumento de recogida de datos más extendido en estadística aplicada: consiste en seleccionar una muestra de individuos de una población y medir sobre ellos, mediante un cuestionario u otro procedimiento de observación, una o varias variables de interés (opiniones, hábitos, características sociodemográficas, intención de voto, etc.). En la mayoría de los casos comparte con el <span class="co">[</span><span class="ot">estudio transversal</span><span class="co">](03-estudios-transversales.qmd)</span> la misma lógica temporal, ya que las variables se registran en un único momento, sobre una muestra tomada de la población general sin condicionar la selección a ninguna exposición o resultado previo. Sin embargo, mientras que en los capítulos anteriores el foco estaba en el tipo de diseño observacional o experimental, en este capítulo el foco se traslada a una cuestión transversal a todos ellos y crítica para la validez de cualquier estudio: **cómo se selecciona la muestra** a partir de la cual se pretende estimar o inferir características de toda la población.</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="fu">## Definición y características</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>:::{#def-encuestas-encuesta-estadistica}</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a><span class="fu">## Encuesta estadística</span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>Una _encuesta estadística_ es un procedimiento de investigación que consiste en seleccionar una muestra de individuos de una población, mediante un método de muestreo determinado, y recoger información sobre ellos (habitualmente a través de un cuestionario) con el fin de estimar características, opiniones o comportamientos de la población de la que proceden.</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>La validez de las conclusiones de una encuesta depende, en gran medida, de que la muestra seleccionada sea representativa de la población objetivo. Esto exige, en primer lugar, disponer de un marco muestral adecuado.</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a>:::{#def-encuestas-marco-muestral}</span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a><span class="fu">## Marco muestral</span></span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a>El _marco muestral_ (en inglés, _sampling frame_) es el listado, registro o procedimiento que permite identificar y acceder a todos los elementos de la población objetivo, de manera que cada uno de ellos pueda ser seleccionado para formar parte de la muestra.</span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-27"><a href="#cb19-27" aria-hidden="true" tabindex="-1"></a>Un marco muestral incompleto o desactualizado (por ejemplo, un censo de población antiguo, o un listado telefónico que excluye a quienes solo disponen de móvil) introduce un sesgo de cobertura, ya que ciertos segmentos de la población tienen probabilidad nula o muy baja de ser seleccionados, con independencia de lo riguroso que sea el método de muestreo empleado posteriormente.</span>
<span id="cb19-28"><a href="#cb19-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-29"><a href="#cb19-29" aria-hidden="true" tabindex="-1"></a>Cuando se dispone de un marco muestral adecuado, existen varios diseños de **muestreo probabilístico**, en los que cada elemento de la población tiene una probabilidad conocida (y no nula) de ser seleccionado, lo que permite calcular la precisión de las estimaciones y generalizarlas a la población con garantías estadísticas. Los principales son los siguientes.</span>
<span id="cb19-30"><a href="#cb19-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-31"><a href="#cb19-31" aria-hidden="true" tabindex="-1"></a><span class="fu">### Muestreo aleatorio simple (MAS)</span></span>
<span id="cb19-32"><a href="#cb19-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-33"><a href="#cb19-33" aria-hidden="true" tabindex="-1"></a>En el _muestreo aleatorio simple_ cada elemento de la población tiene la misma probabilidad de ser seleccionado, y la selección de cada individuo es independiente de la de los demás. Es el diseño de referencia, el más sencillo de analizar, pero exige disponer de un marco muestral completo y puede resultar poco eficiente cuando la población es muy heterogénea o está muy dispersa geográficamente.</span>
<span id="cb19-34"><a href="#cb19-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-35"><a href="#cb19-35" aria-hidden="true" tabindex="-1"></a><span class="fu">### Muestreo estratificado</span></span>
<span id="cb19-36"><a href="#cb19-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-37"><a href="#cb19-37" aria-hidden="true" tabindex="-1"></a>En el _muestreo estratificado_ la población se divide previamente en subgrupos o **estratos**, internamente lo más homogéneos posible respecto a la variable de interés y heterogéneos entre sí (por ejemplo, comunidades autónomas, tramos de edad o tipo de centro educativo), y dentro de cada estrato se selecciona una muestra aleatoria simple de manera independiente. Cuando el tamaño de la muestra en cada estrato se reparte en proporción al peso de dicho estrato en la población, se habla de **afijación proporcional**. Al garantizar la presencia de todos los estratos en la proporción adecuada, este diseño suele producir estimaciones más precisas que el muestreo aleatorio simple, para un mismo tamaño de muestra, siempre que los estratos sean realmente homogéneos internamente.</span>
<span id="cb19-38"><a href="#cb19-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-39"><a href="#cb19-39" aria-hidden="true" tabindex="-1"></a><span class="fu">### Muestreo por conglomerados</span></span>
<span id="cb19-40"><a href="#cb19-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-41"><a href="#cb19-41" aria-hidden="true" tabindex="-1"></a>En el _muestreo por conglomerados_ (o _por clusters_) la población se divide en grupos naturales o preexistentes (conglomerados), como colegios, manzanas de una ciudad o centros de salud, y en lugar de seleccionar individuos se seleccionan aleatoriamente algunos conglomerados completos, incluyendo a todos sus miembros en la muestra (o, en su versión bietápica, seleccionando después una submuestra dentro de cada conglomerado elegido). Resulta especialmente útil cuando no existe un marco muestral de individuos pero sí de conglomerados, y reduce mucho el coste logístico al concentrar el trabajo de campo en unas pocas zonas. A cambio, suele perder precisión respecto al muestreo aleatorio simple, ya que los individuos de un mismo conglomerado tienden a parecerse entre sí.</span>
<span id="cb19-42"><a href="#cb19-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-43"><a href="#cb19-43" aria-hidden="true" tabindex="-1"></a><span class="fu">### Muestreo sistemático</span></span>
<span id="cb19-44"><a href="#cb19-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-45"><a href="#cb19-45" aria-hidden="true" tabindex="-1"></a>En el _muestreo sistemático_ se ordena el marco muestral (por ejemplo, un listado de $N$ individuos), se calcula un intervalo de selección $k = N/n$ (siendo $n$ el tamaño de muestra deseado), se elige aleatoriamente un punto de partida entre $1$ y $k$, y a partir de él se selecciona cada $k$-ésimo elemento de la lista. Es fácil de aplicar y, cuando el listado no sigue ningún patrón periódico relacionado con la variable de interés, suele proporcionar resultados muy similares a los del muestreo aleatorio simple.</span>
<span id="cb19-46"><a href="#cb19-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-47"><a href="#cb19-47" aria-hidden="true" tabindex="-1"></a>Además de estos diseños probabilísticos, existen métodos de **muestreo no probabilístico**, como el muestreo por conveniencia (se selecciona a los individuos más accesibles) o el muestreo en bola de nieve (los participantes reclutan a su vez a otros participantes). Estos métodos son más rápidos y baratos, pero al no conocerse la probabilidad de selección de cada individuo no permiten calcular la precisión de las estimaciones ni generalizar los resultados a la población con garantías estadísticas, por lo que su uso queda habitualmente restringido a estudios exploratorios o poblaciones muy difíciles de acceder.</span>
<span id="cb19-48"><a href="#cb19-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-49"><a href="#cb19-49" aria-hidden="true" tabindex="-1"></a><span class="fu">## Ventajas e inconvenientes</span></span>
<span id="cb19-50"><a href="#cb19-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-51"><a href="#cb19-51" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Muestreo aleatorio simple**: es el más sencillo de diseñar y analizar, pero exige un marco muestral completo de individuos y puede resultar poco eficiente (mayor error para el mismo tamaño de muestra) cuando la población es heterogénea.</span>
<span id="cb19-52"><a href="#cb19-52" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Muestreo estratificado**: mejora la precisión frente al muestreo aleatorio simple cuando existen variables (estratos) fuertemente relacionadas con la variable de interés, y garantiza representación de todos los grupos relevantes; a cambio, requiere conocer de antemano el valor de la variable de estratificación para toda la población, lo que no siempre es posible.</span>
<span id="cb19-53"><a href="#cb19-53" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Muestreo por conglomerados**: es el más económico y logísticamente viable cuando la población está muy dispersa o no existe un marco muestral de individuos, pero suele ser el menos preciso, ya que los elementos de un mismo conglomerado tienden a ser parecidos entre sí (baja variabilidad interna, alta variabilidad entre conglomerados).</span>
<span id="cb19-54"><a href="#cb19-54" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Muestreo sistemático**: es muy fácil de implementar sobre un listado ordenado y suele comportarse como el muestreo aleatorio simple, pero puede introducir sesgos graves si el listado presenta algún patrón periódico que coincida con el intervalo de selección $k$.</span>
<span id="cb19-55"><a href="#cb19-55" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Muestreo no probabilístico**: es el más rápido y barato, y en ocasiones la única opción viable (por ejemplo, para poblaciones ocultas o de difícil acceso), pero no permite cuantificar el error de muestreo ni generalizar los resultados a la población con garantías estadísticas.</span>
<span id="cb19-56"><a href="#cb19-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-57"><a href="#cb19-57" aria-hidden="true" tabindex="-1"></a><span class="fu">## Medidas propias de este diseño</span></span>
<span id="cb19-58"><a href="#cb19-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-59"><a href="#cb19-59" aria-hidden="true" tabindex="-1"></a>Además de las medidas descriptivas habituales (proporciones, medias, etc.), calculadas ahora ponderando por el diseño muestral empleado, dos cantidades son especialmente características del diseño de encuestas: el error de muestreo de una estimación y el tamaño muestral necesario para lograr una precisión determinada.</span>
<span id="cb19-60"><a href="#cb19-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-61"><a href="#cb19-61" aria-hidden="true" tabindex="-1"></a><span class="fu">### Error de muestreo</span></span>
<span id="cb19-62"><a href="#cb19-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-63"><a href="#cb19-63" aria-hidden="true" tabindex="-1"></a>:::{#def-encuestas-error-muestreo}</span>
<span id="cb19-64"><a href="#cb19-64" aria-hidden="true" tabindex="-1"></a><span class="fu">## Error de muestreo</span></span>
<span id="cb19-65"><a href="#cb19-65" aria-hidden="true" tabindex="-1"></a>Dada una muestra aleatoria simple de tamaño $n$ en la que se ha observado una proporción muestral $\hat p$ de individuos que presentan una determinada característica, el _error de muestreo_ (o margen de error) de $\hat p$ para un nivel de confianza $1-\alpha$ se define como</span>
<span id="cb19-66"><a href="#cb19-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-67"><a href="#cb19-67" aria-hidden="true" tabindex="-1"></a>$$e = z_{\alpha/2}\sqrt{\frac{\hat p(1-\hat p)}{n}}$$</span>
<span id="cb19-68"><a href="#cb19-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-69"><a href="#cb19-69" aria-hidden="true" tabindex="-1"></a>donde $z_{\alpha/2}$ es el valor crítico de la distribución normal estándar que deja una probabilidad $\alpha/2$ a su derecha.</span>
<span id="cb19-70"><a href="#cb19-70" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-71"><a href="#cb19-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-72"><a href="#cb19-72" aria-hidden="true" tabindex="-1"></a>:::{.callout-important}</span>
<span id="cb19-73"><a href="#cb19-73" aria-hidden="true" tabindex="-1"></a>El error de muestreo es siempre un número no negativo,</span>
<span id="cb19-74"><a href="#cb19-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-75"><a href="#cb19-75" aria-hidden="true" tabindex="-1"></a>$$e \geq 0,$$</span>
<span id="cb19-76"><a href="#cb19-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-77"><a href="#cb19-77" aria-hidden="true" tabindex="-1"></a>y disminuye a medida que aumenta el tamaño de muestra $n$, concretamente en proporción a $1/\sqrt{n}$: para reducir el error a la mitad es necesario cuadruplicar el tamaño de muestra.</span>
<span id="cb19-78"><a href="#cb19-78" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-79"><a href="#cb19-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-80"><a href="#cb19-80" aria-hidden="true" tabindex="-1"></a>:::{.callout-note title=Interpretación}</span>
<span id="cb19-81"><a href="#cb19-81" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>El error de muestreo cuantifica cuánto puede diferir, con la confianza especificada, la proporción muestral $\hat p$ de la verdadera proporción poblacional $p$, exclusivamente por el hecho de trabajar con una muestra y no con toda la población.</span>
<span id="cb19-82"><a href="#cb19-82" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>El intervalo $(\hat p - e,\ \hat p + e)$ es precisamente el intervalo de confianza al nivel $1-\alpha$ para la proporción poblacional $p$.</span>
<span id="cb19-83"><a href="#cb19-83" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>El error de muestreo no recoge otras fuentes de error ajenas al azar, como el sesgo de no respuesta, el sesgo de cobertura del marco muestral o los errores de medición del cuestionario, que pueden ser tanto o más importantes que el propio error de muestreo.</span>
<span id="cb19-84"><a href="#cb19-84" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-85"><a href="#cb19-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-86"><a href="#cb19-86" aria-hidden="true" tabindex="-1"></a><span class="fu">### Tamaño muestral necesario</span></span>
<span id="cb19-87"><a href="#cb19-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-88"><a href="#cb19-88" aria-hidden="true" tabindex="-1"></a>En la práctica, la pregunta habitual no es "¿qué error tiene mi muestra?" sino la inversa: "¿qué tamaño de muestra necesito para que el error no supere un determinado valor?". Despejando $n$ de la fórmula del error de muestreo se obtiene la siguiente expresión.</span>
<span id="cb19-89"><a href="#cb19-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-90"><a href="#cb19-90" aria-hidden="true" tabindex="-1"></a>:::{#def-encuestas-tamano-muestral}</span>
<span id="cb19-91"><a href="#cb19-91" aria-hidden="true" tabindex="-1"></a><span class="fu">## Tamaño muestral necesario</span></span>
<span id="cb19-92"><a href="#cb19-92" aria-hidden="true" tabindex="-1"></a>Para estimar una proporción poblacional $p$ con un error de muestreo máximo $e$ y un nivel de confianza $1-\alpha$, el tamaño de muestra necesario, suponiendo muestreo aleatorio simple sobre una población de tamaño muy superior a la muestra, es</span>
<span id="cb19-93"><a href="#cb19-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-94"><a href="#cb19-94" aria-hidden="true" tabindex="-1"></a>$$n = \frac{z_{\alpha/2}^2\, p(1-p)}{e^2}$$</span>
<span id="cb19-95"><a href="#cb19-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-96"><a href="#cb19-96" aria-hidden="true" tabindex="-1"></a>donde $p$ es un valor aproximado (de un estudio previo o piloto) de la proporción que se quiere estimar; si no se dispone de tal valor, se toma $p=0.5$, ya que es el valor que maximiza $p(1-p)$ y por tanto produce el tamaño de muestra más conservador (el mayor posible).</span>
<span id="cb19-97"><a href="#cb19-97" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-98"><a href="#cb19-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-99"><a href="#cb19-99" aria-hidden="true" tabindex="-1"></a>:::{.callout-important}</span>
<span id="cb19-100"><a href="#cb19-100" aria-hidden="true" tabindex="-1"></a>Cuando la población tiene un tamaño finito y conocido $N$ que no es muy superior al tamaño de muestra calculado, puede aplicarse el _factor de corrección para poblaciones finitas_,</span>
<span id="cb19-101"><a href="#cb19-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-102"><a href="#cb19-102" aria-hidden="true" tabindex="-1"></a>$$n_{ajustado} = \frac{n}{1+\dfrac{n-1}{N}},$$</span>
<span id="cb19-103"><a href="#cb19-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-104"><a href="#cb19-104" aria-hidden="true" tabindex="-1"></a>que reduce ligeramente el tamaño de muestra necesario. En la práctica, cuando $N$ es grande frente a $n$ (por ejemplo, encuestas sobre la población de un país o una ciudad grande), esta corrección apenas tiene efecto y suele omitirse.</span>
<span id="cb19-105"><a href="#cb19-105" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-106"><a href="#cb19-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-107"><a href="#cb19-107" aria-hidden="true" tabindex="-1"></a>:::{.callout-note title=Interpretación}</span>
<span id="cb19-108"><a href="#cb19-108" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>El tamaño muestral necesario aumenta con el nivel de confianza exigido (mayor $z_{\alpha/2}$) y disminuye rápidamente al relajar la precisión exigida (mayor $e$), ya que $n$ depende del cuadrado de $e$ en el denominador.</span>
<span id="cb19-109"><a href="#cb19-109" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>El tamaño muestral necesario es máximo cuando $p=0.5$ y disminuye a medida que $p$ se aleja de $0.5$ hacia $0$ o hacia $1$, ya que fenómenos muy raros o muy comunes son, en cierto sentido, más fáciles de acotar con precisión.</span>
<span id="cb19-110"><a href="#cb19-110" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Esta fórmula corresponde al muestreo aleatorio simple; en diseños estratificados, por conglomerados o sistemáticos, el tamaño necesario puede ser menor o mayor, en función de si el diseño mejora o empeora la precisión respecto al muestreo aleatorio simple.</span>
<span id="cb19-111"><a href="#cb19-111" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-112"><a href="#cb19-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-113"><a href="#cb19-113" aria-hidden="true" tabindex="-1"></a>:::{#exm-encuestas-tamano-muestral}</span>
<span id="cb19-114"><a href="#cb19-114" aria-hidden="true" tabindex="-1"></a>Se quiere diseñar una encuesta para estimar la proporción de la población de una ciudad que está a favor de un determinado proyecto urbanístico, con un error de muestreo máximo de $e=0.03$ (tres puntos porcentuales) y un nivel de confianza del $95\%$ ($\alpha=0.05$, por lo que $z_{\alpha/2}=1.96$). Al no disponer de información previa sobre la proporción real, se toma el valor más conservador, $p=0.5$. El tamaño de muestra necesario es</span>
<span id="cb19-115"><a href="#cb19-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-116"><a href="#cb19-116" aria-hidden="true" tabindex="-1"></a>$$n = \frac{z_{\alpha/2}^2\, p(1-p)}{e^2} = \frac{1.96^2 \times 0.5 \times 0.5}{0.03^2} = \frac{0.9604}{0.0009} \approx 1067.1.$$</span>
<span id="cb19-117"><a href="#cb19-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-118"><a href="#cb19-118" aria-hidden="true" tabindex="-1"></a>Redondeando hacia arriba, se necesitaría una muestra de $n=1068$ individuos para garantizar, con una confianza del $95\%$, que la proporción estimada no se aleje de la verdadera proporción poblacional en más de tres puntos porcentuales.</span>
<span id="cb19-119"><a href="#cb19-119" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb19-120"><a href="#cb19-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-121"><a href="#cb19-121" aria-hidden="true" tabindex="-1"></a><span class="fu">## Realización con R</span></span>
<span id="cb19-122"><a href="#cb19-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-123"><a href="#cb19-123" aria-hidden="true" tabindex="-1"></a><span class="fu">### Cálculo del tamaño muestral necesario</span></span>
<span id="cb19-124"><a href="#cb19-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-125"><a href="#cb19-125" aria-hidden="true" tabindex="-1"></a>En primer lugar se reproduce en R el cálculo manual del @exm-encuestas-tamano-muestral, obteniendo el valor crítico $z_{\alpha/2}$ con <span class="in">`qnorm()`</span> y aplicando directamente la fórmula del tamaño muestral:</span>
<span id="cb19-126"><a href="#cb19-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-127"><a href="#cb19-127" aria-hidden="true" tabindex="-1"></a><span class="in">```{r tamano-muestral}</span></span>
<span id="cb19-128"><a href="#cb19-128" aria-hidden="true" tabindex="-1"></a>calcular_n <span class="ot">&lt;-</span> <span class="cf">function</span>(e, <span class="at">confianza =</span> <span class="fl">0.95</span>, <span class="at">p =</span> <span class="fl">0.5</span>) {</span>
<span id="cb19-129"><a href="#cb19-129" aria-hidden="true" tabindex="-1"></a>  alpha <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> confianza</span>
<span id="cb19-130"><a href="#cb19-130" aria-hidden="true" tabindex="-1"></a>  z <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(<span class="dv">1</span> <span class="sc">-</span> alpha <span class="sc">/</span> <span class="dv">2</span>)</span>
<span id="cb19-131"><a href="#cb19-131" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> (z<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> p <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> p)) <span class="sc">/</span> e<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb19-132"><a href="#cb19-132" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ceiling</span>(n)</span>
<span id="cb19-133"><a href="#cb19-133" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb19-134"><a href="#cb19-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-135"><a href="#cb19-135" aria-hidden="true" tabindex="-1"></a>n_necesario <span class="ot">&lt;-</span> <span class="fu">calcular_n</span>(<span class="at">e =</span> <span class="fl">0.03</span>, <span class="at">confianza =</span> <span class="fl">0.95</span>, <span class="at">p =</span> <span class="fl">0.5</span>)</span>
<span id="cb19-136"><a href="#cb19-136" aria-hidden="true" tabindex="-1"></a>n_necesario</span>
<span id="cb19-137"><a href="#cb19-137" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-138"><a href="#cb19-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-139"><a href="#cb19-139" aria-hidden="true" tabindex="-1"></a>El resultado, <span class="in">`r n_necesario`</span> individuos, coincide con el obtenido a mano. A continuación se representa cómo varía el tamaño de muestra necesario en función del error de muestreo admitido, para un nivel de confianza del 95%:</span>
<span id="cb19-140"><a href="#cb19-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-141"><a href="#cb19-141" aria-hidden="true" tabindex="-1"></a><span class="in">```{r grafico-tamano-muestral, fig.cap="Tamaño de muestra necesario en función del error de muestreo admitido (confianza del 95%, p = 0.5)."}</span></span>
<span id="cb19-142"><a href="#cb19-142" aria-hidden="true" tabindex="-1"></a>errores <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb19-143"><a href="#cb19-143" aria-hidden="true" tabindex="-1"></a>  <span class="at">e =</span> <span class="fu">seq</span>(<span class="fl">0.01</span>, <span class="fl">0.10</span>, <span class="at">by =</span> <span class="fl">0.005</span>)</span>
<span id="cb19-144"><a href="#cb19-144" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb19-145"><a href="#cb19-145" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">n =</span> <span class="fu">map_dbl</span>(e, <span class="sc">~</span> <span class="fu">calcular_n</span>(.x, <span class="at">confianza =</span> <span class="fl">0.95</span>, <span class="at">p =</span> <span class="fl">0.5</span>)))</span>
<span id="cb19-146"><a href="#cb19-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-147"><a href="#cb19-147" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(errores, <span class="fu">aes</span>(<span class="at">x =</span> e, <span class="at">y =</span> n)) <span class="sc">+</span></span>
<span id="cb19-148"><a href="#cb19-148" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb19-149"><a href="#cb19-149" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb19-150"><a href="#cb19-150" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>()) <span class="sc">+</span></span>
<span id="cb19-151"><a href="#cb19-151" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">comma_format</span>()) <span class="sc">+</span></span>
<span id="cb19-152"><a href="#cb19-152" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb19-153"><a href="#cb19-153" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Error de muestreo admitido"</span>,</span>
<span id="cb19-154"><a href="#cb19-154" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Tamaño de muestra necesario"</span>,</span>
<span id="cb19-155"><a href="#cb19-155" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Relación entre precisión exigida y tamaño de muestra"</span></span>
<span id="cb19-156"><a href="#cb19-156" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb19-157"><a href="#cb19-157" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb19-158"><a href="#cb19-158" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-159"><a href="#cb19-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-160"><a href="#cb19-160" aria-hidden="true" tabindex="-1"></a>Como cabía esperar, el tamaño de muestra necesario crece muy rápidamente a medida que se exige un error de muestreo menor, debido a la relación cuadrática entre ambas cantidades.</span>
<span id="cb19-161"><a href="#cb19-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-162"><a href="#cb19-162" aria-hidden="true" tabindex="-1"></a><span class="fu">### Comparación entre muestreo aleatorio simple y muestreo estratificado</span></span>
<span id="cb19-163"><a href="#cb19-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-164"><a href="#cb19-164" aria-hidden="true" tabindex="-1"></a>Para comparar la precisión del muestreo aleatorio simple (MAS) frente al muestreo estratificado, se simula una "población" de $N=4000$ personas repartidas en 4 regiones, con una opinión binaria (a favor / en contra de una medida) cuya prevalencia varía sustancialmente de una región a otra, de forma que la región constituye un buen criterio de estratificación:</span>
<span id="cb19-165"><a href="#cb19-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-166"><a href="#cb19-166" aria-hidden="true" tabindex="-1"></a><span class="in">```{r poblacion-simulada}</span></span>
<span id="cb19-167"><a href="#cb19-167" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb19-168"><a href="#cb19-168" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">4000</span></span>
<span id="cb19-169"><a href="#cb19-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-170"><a href="#cb19-170" aria-hidden="true" tabindex="-1"></a>poblacion <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb19-171"><a href="#cb19-171" aria-hidden="true" tabindex="-1"></a>  <span class="at">id =</span> <span class="dv">1</span><span class="sc">:</span>N,</span>
<span id="cb19-172"><a href="#cb19-172" aria-hidden="true" tabindex="-1"></a>  <span class="at">region =</span> <span class="fu">sample</span>(</span>
<span id="cb19-173"><a href="#cb19-173" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(<span class="st">"Norte"</span>, <span class="st">"Sur"</span>, <span class="st">"Este"</span>, <span class="st">"Oeste"</span>),</span>
<span id="cb19-174"><a href="#cb19-174" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> N,</span>
<span id="cb19-175"><a href="#cb19-175" aria-hidden="true" tabindex="-1"></a>    <span class="at">replace =</span> <span class="cn">TRUE</span>,</span>
<span id="cb19-176"><a href="#cb19-176" aria-hidden="true" tabindex="-1"></a>    <span class="at">prob =</span> <span class="fu">c</span>(<span class="fl">0.30</span>, <span class="fl">0.25</span>, <span class="fl">0.25</span>, <span class="fl">0.20</span>)</span>
<span id="cb19-177"><a href="#cb19-177" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb19-178"><a href="#cb19-178" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-179"><a href="#cb19-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-180"><a href="#cb19-180" aria-hidden="true" tabindex="-1"></a><span class="co"># La probabilidad de estar a favor depende fuertemente de la región</span></span>
<span id="cb19-181"><a href="#cb19-181" aria-hidden="true" tabindex="-1"></a>prob_favor <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">Norte =</span> <span class="fl">0.75</span>, <span class="at">Sur =</span> <span class="fl">0.30</span>, <span class="at">Este =</span> <span class="fl">0.55</span>, <span class="at">Oeste =</span> <span class="fl">0.40</span>)</span>
<span id="cb19-182"><a href="#cb19-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-183"><a href="#cb19-183" aria-hidden="true" tabindex="-1"></a>poblacion <span class="ot">&lt;-</span> poblacion <span class="sc">|&gt;</span></span>
<span id="cb19-184"><a href="#cb19-184" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb19-185"><a href="#cb19-185" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_favor =</span> prob_favor[region],</span>
<span id="cb19-186"><a href="#cb19-186" aria-hidden="true" tabindex="-1"></a>    <span class="at">opinion =</span> <span class="fu">rbinom</span>(N, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> p_favor),</span>
<span id="cb19-187"><a href="#cb19-187" aria-hidden="true" tabindex="-1"></a>    <span class="at">opinion =</span> <span class="fu">factor</span>(opinion, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"En contra"</span>, <span class="st">"A favor"</span>))</span>
<span id="cb19-188"><a href="#cb19-188" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb19-189"><a href="#cb19-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-190"><a href="#cb19-190" aria-hidden="true" tabindex="-1"></a>poblacion</span>
<span id="cb19-191"><a href="#cb19-191" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-192"><a href="#cb19-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-193"><a href="#cb19-193" aria-hidden="true" tabindex="-1"></a>La proporción real de personas a favor en el conjunto de la población (el parámetro que se desea estimar) es:</span>
<span id="cb19-194"><a href="#cb19-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-195"><a href="#cb19-195" aria-hidden="true" tabindex="-1"></a><span class="in">```{r proporcion-poblacional}</span></span>
<span id="cb19-196"><a href="#cb19-196" aria-hidden="true" tabindex="-1"></a>p_poblacional <span class="ot">&lt;-</span> <span class="fu">mean</span>(poblacion<span class="sc">$</span>opinion <span class="sc">==</span> <span class="st">"A favor"</span>)</span>
<span id="cb19-197"><a href="#cb19-197" aria-hidden="true" tabindex="-1"></a>p_poblacional</span>
<span id="cb19-198"><a href="#cb19-198" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-199"><a href="#cb19-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-200"><a href="#cb19-200" aria-hidden="true" tabindex="-1"></a>A partir de esta población se extrae, en primer lugar, una muestra aleatoria simple de $n=<span class="in">`r n_necesario`</span>$ individuos:</span>
<span id="cb19-201"><a href="#cb19-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-202"><a href="#cb19-202" aria-hidden="true" tabindex="-1"></a><span class="in">```{r muestra-mas}</span></span>
<span id="cb19-203"><a href="#cb19-203" aria-hidden="true" tabindex="-1"></a>muestra_mas <span class="ot">&lt;-</span> poblacion <span class="sc">|&gt;</span></span>
<span id="cb19-204"><a href="#cb19-204" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n =</span> n_necesario)</span>
<span id="cb19-205"><a href="#cb19-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-206"><a href="#cb19-206" aria-hidden="true" tabindex="-1"></a>p_mas <span class="ot">&lt;-</span> <span class="fu">mean</span>(muestra_mas<span class="sc">$</span>opinion <span class="sc">==</span> <span class="st">"A favor"</span>)</span>
<span id="cb19-207"><a href="#cb19-207" aria-hidden="true" tabindex="-1"></a>p_mas</span>
<span id="cb19-208"><a href="#cb19-208" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-209"><a href="#cb19-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-210"><a href="#cb19-210" aria-hidden="true" tabindex="-1"></a>A continuación se extrae una muestra estratificada por región, con afijación proporcional, del mismo tamaño total aproximado: se calcula la proporción que representa cada región en la población y se selecciona ese mismo porcentaje dentro de cada estrato:</span>
<span id="cb19-211"><a href="#cb19-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-212"><a href="#cb19-212" aria-hidden="true" tabindex="-1"></a><span class="in">```{r muestra-estratificada}</span></span>
<span id="cb19-213"><a href="#cb19-213" aria-hidden="true" tabindex="-1"></a>prop_muestral <span class="ot">&lt;-</span> n_necesario <span class="sc">/</span> N</span>
<span id="cb19-214"><a href="#cb19-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-215"><a href="#cb19-215" aria-hidden="true" tabindex="-1"></a>muestra_estratificada <span class="ot">&lt;-</span> poblacion <span class="sc">|&gt;</span></span>
<span id="cb19-216"><a href="#cb19-216" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(region) <span class="sc">|&gt;</span></span>
<span id="cb19-217"><a href="#cb19-217" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">prop =</span> prop_muestral) <span class="sc">|&gt;</span></span>
<span id="cb19-218"><a href="#cb19-218" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb19-219"><a href="#cb19-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-220"><a href="#cb19-220" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(muestra_estratificada)</span>
<span id="cb19-221"><a href="#cb19-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-222"><a href="#cb19-222" aria-hidden="true" tabindex="-1"></a>p_estratificado <span class="ot">&lt;-</span> <span class="fu">mean</span>(muestra_estratificada<span class="sc">$</span>opinion <span class="sc">==</span> <span class="st">"A favor"</span>)</span>
<span id="cb19-223"><a href="#cb19-223" aria-hidden="true" tabindex="-1"></a>p_estratificado</span>
<span id="cb19-224"><a href="#cb19-224" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-225"><a href="#cb19-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-226"><a href="#cb19-226" aria-hidden="true" tabindex="-1"></a>Se comprueba que la muestra estratificada respeta, aproximadamente, el peso de cada región en la población:</span>
<span id="cb19-227"><a href="#cb19-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-228"><a href="#cb19-228" aria-hidden="true" tabindex="-1"></a><span class="in">```{r comprobacion-estratos}</span></span>
<span id="cb19-229"><a href="#cb19-229" aria-hidden="true" tabindex="-1"></a>muestra_estratificada <span class="sc">|&gt;</span></span>
<span id="cb19-230"><a href="#cb19-230" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(region) <span class="sc">|&gt;</span></span>
<span id="cb19-231"><a href="#cb19-231" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">proporcion_muestra =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span>
<span id="cb19-232"><a href="#cb19-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-233"><a href="#cb19-233" aria-hidden="true" tabindex="-1"></a>poblacion <span class="sc">|&gt;</span></span>
<span id="cb19-234"><a href="#cb19-234" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(region) <span class="sc">|&gt;</span></span>
<span id="cb19-235"><a href="#cb19-235" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">proporcion_poblacion =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span>
<span id="cb19-236"><a href="#cb19-236" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-237"><a href="#cb19-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-238"><a href="#cb19-238" aria-hidden="true" tabindex="-1"></a>Por último, se comparan gráficamente las tres proporciones: la real de la población y las estimadas por cada uno de los dos métodos de muestreo.</span>
<span id="cb19-239"><a href="#cb19-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-240"><a href="#cb19-240" aria-hidden="true" tabindex="-1"></a><span class="in">```{r grafico-comparacion, fig.cap="Proporción de personas a favor de la medida: valor poblacional real frente a las estimaciones por muestreo aleatorio simple y por muestreo estratificado."}</span></span>
<span id="cb19-241"><a href="#cb19-241" aria-hidden="true" tabindex="-1"></a>comparacion <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb19-242"><a href="#cb19-242" aria-hidden="true" tabindex="-1"></a>  <span class="at">metodo =</span> <span class="fu">c</span>(<span class="st">"Población"</span>, <span class="st">"MAS"</span>, <span class="st">"Estratificado"</span>),</span>
<span id="cb19-243"><a href="#cb19-243" aria-hidden="true" tabindex="-1"></a>  <span class="at">proporcion =</span> <span class="fu">c</span>(p_poblacional, p_mas, p_estratificado)</span>
<span id="cb19-244"><a href="#cb19-244" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb19-245"><a href="#cb19-245" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">metodo =</span> <span class="fu">factor</span>(metodo, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Población"</span>, <span class="st">"MAS"</span>, <span class="st">"Estratificado"</span>)))</span>
<span id="cb19-246"><a href="#cb19-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-247"><a href="#cb19-247" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(comparacion, <span class="fu">aes</span>(<span class="at">x =</span> metodo, <span class="at">y =</span> proporcion, <span class="at">fill =</span> metodo)) <span class="sc">+</span></span>
<span id="cb19-248"><a href="#cb19-248" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb19-249"><a href="#cb19-249" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> p_poblacional, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"gray30"</span>) <span class="sc">+</span></span>
<span id="cb19-250"><a href="#cb19-250" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>()) <span class="sc">+</span></span>
<span id="cb19-251"><a href="#cb19-251" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set2"</span>) <span class="sc">+</span></span>
<span id="cb19-252"><a href="#cb19-252" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb19-253"><a href="#cb19-253" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb19-254"><a href="#cb19-254" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Proporción a favor"</span>,</span>
<span id="cb19-255"><a href="#cb19-255" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Estimación de la proporción según el diseño de muestreo"</span></span>
<span id="cb19-256"><a href="#cb19-256" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb19-257"><a href="#cb19-257" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb19-258"><a href="#cb19-258" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span>
<span id="cb19-259"><a href="#cb19-259" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb19-260"><a href="#cb19-260" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-261"><a href="#cb19-261" aria-hidden="true" tabindex="-1"></a>En esta simulación, la proporción real de personas a favor en la población es del <span class="in">`r scales::percent(p_poblacional, accuracy = 0.1)`</span>, mientras que la muestra aleatoria simple estima un <span class="in">`r scales::percent(p_mas, accuracy = 0.1)`</span> y la muestra estratificada un <span class="in">`r scales::percent(p_estratificado, accuracy = 0.1)`</span>. Dado que la región está fuertemente relacionada con la opinión (los estratos son internamente bastante homogéneos) y que la afijación proporcional garantiza que cada región esté representada en su peso exacto, cabe esperar que, en promedio y a lo largo de repeticiones del muestreo, la estimación estratificada se aproxime más a la proporción poblacional que la del muestreo aleatorio simple, cuya composición por regiones puede variar de una muestra a otra por puro azar. Este es precisamente el motivo por el que, siempre que se disponga de una variable de estratificación adecuada, el muestreo estratificado suele preferirse al muestreo aleatorio simple en las encuestas reales.</span>
<span id="cb19-262"><a href="#cb19-262" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-263"><a href="#cb19-263" aria-hidden="true" tabindex="-1"></a><span class="fu">## Cuándo utilizar este diseño</span></span>
<span id="cb19-264"><a href="#cb19-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-265"><a href="#cb19-265" aria-hidden="true" tabindex="-1"></a>El diseño de muestreo no es un tipo de estudio alternativo a los descritos en los capítulos anteriores, sino una dimensión transversal a todos ellos: tanto un <span class="co">[</span><span class="ot">estudio descriptivo</span><span class="co">](02-estudios-descriptivos.qmd)</span> como un <span class="co">[</span><span class="ot">estudio transversal</span><span class="co">](03-estudios-transversales.qmd)</span>, un <span class="co">[</span><span class="ot">estudio de cohortes</span><span class="co">](04-estudios-cohortes.qmd)</span> o un ensayo <span class="co">[</span><span class="ot">experimental</span><span class="co">](07-estudios-experimentales.qmd)</span> necesitan seleccionar en algún momento una muestra de la población, y la calidad de ese muestreo condiciona directamente la validez de las conclusiones que se extraigan. Conviene prestar especial atención al diseño muestral, y en particular optar por el muestreo estratificado o por conglomerados frente al muestreo aleatorio simple, cuando la población es muy heterogénea, cuando existen variables conocidas fuertemente relacionadas con el fenómeno de interés, o cuando el coste de acceder a los individuos varía mucho según su localización o su pertenencia a un determinado grupo. Un cálculo previo del tamaño muestral necesario, en función de la precisión exigida y de los recursos disponibles, es también un paso imprescindible en la planificación de cualquier estudio, se trate de una encuesta de opinión, un estudio epidemiológico o un ensayo clínico. En definitiva, ningún análisis estadístico posterior, por sofisticado que sea, puede compensar una muestra mal seleccionada: la calidad del diseño muestral es, junto con el propio diseño del estudio, uno de los pilares sobre los que se sostiene la validez de cualquier investigación estadística.</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/asalber/estadistica-tipos-estudios/edit/main/09-encuestas-muestreo.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li><li><a href="https://github.com/asalber/estadistica-tipos-estudios/issues/new" class="toc-action"><i class="bi empty"></i>Informar de un problema</a></li></ul></div></div></div></footer></body></html>