<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>14&nbsp; Contrastes para más de dos poblaciones independientes – Tipos de Estudios Estadísticos</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./15-contrastes-medidas-repetidas.html" rel="next">
<link href="./13-contrastes-dos-poblaciones-pareadas.html" rel="prev">
<link href="./img/logos/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-3419ea62b3ca2d77d3d547f86109e84e.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-eaeb381c6b7494c50009502241a4985c.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-b050db56f2b97c639b7ebc2cf71c06d7.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-5e50218c20039713403b52e69b91eb5d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="14&nbsp; Contrastes para más de dos poblaciones independientes – Tipos de Estudios Estadísticos">
<meta property="og:description" content="">
<meta property="og:image" content="14-contrastes-mas-dos-poblaciones-independientes_files/figure-html/boxplot-1.png">
<meta property="og:site_name" content="Tipos de Estudios Estadísticos">
<meta name="twitter:title" content="14&nbsp; Contrastes para más de dos poblaciones independientes – Tipos de Estudios Estadísticos">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="14-contrastes-mas-dos-poblaciones-independientes_files/figure-html/boxplot-1.png">
<meta name="twitter:site" content="@aprendeconalf">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating quarto-dark"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = true;
    const darkModeDefault = authorPrefersDark;
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./10-seleccion-contraste.html">Selección del contraste estadístico</a></li><li class="breadcrumb-item"><a href="./14-contrastes-mas-dos-poblaciones-independientes.html"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Contrastes para más de dos poblaciones independientes</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      <img src="./img/logos/aprendeconalf.png" alt="" class="sidebar-logo light-content py-0 d-lg-inline d-none">
      <img src="./img/logos/aprendeconalf.png" alt="" class="sidebar-logo dark-content py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Tipos de Estudios Estadísticos</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://aprendeconalf.es" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-house-fill"></i></a>
    <a href="https://github.com/asalber/estadistica-tipos-estudios" title="Ejecutar el código" class="quarto-navigation-tool px-1" aria-label="Ejecutar el código"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Download" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Download"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./estadistica-tipos-estudios.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Download PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./estadistica-tipos-estudios.epub">
              <i class="bi bi-journal pe-1"></i>
            Download ePub
            </a>
          </li>
      </ul>
    </div>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-1" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-1">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo oscuro"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-introduccion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción a los tipos de estudios estadísticos</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Diseños de estudio</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-estudios-descriptivos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Estudios descriptivos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-estudios-transversales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Estudios transversales</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-estudios-cohortes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Estudios de cohortes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-estudios-casos-controles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Estudios de casos y controles</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-estudios-ecologicos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Estudios ecológicos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-estudios-experimentales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Estudios experimentales</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-estudios-cuasiexperimentales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Estudios cuasiexperimentales</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-encuestas-muestreo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Encuestas y diseño de muestreo</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Selección del contraste estadístico</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-seleccion-contraste.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Selección del contraste estadístico</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-contrastes-una-poblacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Contrastes para una población</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-contrastes-dos-poblaciones-independientes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Contrastes para dos poblaciones independientes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-contrastes-dos-poblaciones-pareadas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Contrastes para dos poblaciones pareadas</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-contrastes-mas-dos-poblaciones-independientes.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Contrastes para más de dos poblaciones independientes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-contrastes-medidas-repetidas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Contrastes para más de dos poblaciones relacionadas (medidas repetidas)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-relacion-entre-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Relación y predicción entre dos variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Indice de contenidos</h2>
   
  <ul>
  <li><a href="#estadísticos-descriptivos-por-grupo" id="toc-estadísticos-descriptivos-por-grupo" class="nav-link active" data-scroll-target="#estadísticos-descriptivos-por-grupo"><span class="header-section-number">14.1</span> Estadísticos descriptivos por grupo</a>
  <ul class="collapse">
  <li><a href="#test-de-levene-de-comparación-de-varianzas" id="toc-test-de-levene-de-comparación-de-varianzas" class="nav-link" data-scroll-target="#test-de-levene-de-comparación-de-varianzas"><span class="header-section-number">14.1.1</span> Test de Levene de comparación de varianzas</a></li>
  <li><a href="#anova-de-un-factor" id="toc-anova-de-un-factor" class="nav-link" data-scroll-target="#anova-de-un-factor"><span class="header-section-number">14.1.2</span> ANOVA de un factor</a></li>
  <li><a href="#test-de-kruskal-wallis-no-paramétrico" id="toc-test-de-kruskal-wallis-no-paramétrico" class="nav-link" data-scroll-target="#test-de-kruskal-wallis-no-paramétrico"><span class="header-section-number">14.1.3</span> Test de Kruskal-Wallis (no paramétrico)</a></li>
  </ul></li>
  <li><a href="#variable-dependiente-cualitativa" id="toc-variable-dependiente-cualitativa" class="nav-link" data-scroll-target="#variable-dependiente-cualitativa"><span class="header-section-number">14.2</span> Variable dependiente cualitativa</a></li>
  <li><a href="#cierre" id="toc-cierre" class="nav-link" data-scroll-target="#cierre"><span class="header-section-number">14.3</span> Cierre</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/asalber/estadistica-tipos-estudios/edit/main/14-contrastes-mas-dos-poblaciones-independientes.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li><li><a href="https://github.com/asalber/estadistica-tipos-estudios/issues/new" class="toc-action"><i class="bi empty"></i>Informar de un problema</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./10-seleccion-contraste.html">Selección del contraste estadístico</a></li><li class="breadcrumb-item"><a href="./14-contrastes-mas-dos-poblaciones-independientes.html"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Contrastes para más de dos poblaciones independientes</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Contrastes para más de dos poblaciones independientes</span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Código</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Enseñar el código</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Esconder el código</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">Ver el código</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>El <a href="./12-contrastes-dos-poblaciones-independientes.html">capítulo anterior</a> trató el caso de dos poblaciones independientes. Sin embargo, en muchas ocasiones no se comparan dos grupos, sino tres o más, formados por individuos distintos entre sí. Este capítulo generaliza los contrastes anteriores a esa situación: cómo comparar una variable, cuantitativa o cualitativa, entre más de dos poblaciones independientes. En el conjunto de datos de ejemplo, la variable independiente natural para esta situación es <code>grupo</code>, que clasifica a los 120 alumnos en tres grupos de clase (A, B y C), formados por alumnos distintos: nadie pertenece a la vez a dos grupos, por lo que las tres poblaciones son independientes entre sí.</p>
<section id="estadísticos-descriptivos-por-grupo" class="level2" data-number="14.1">
<h2 data-number="14.1" class="anchored" data-anchor-id="estadísticos-descriptivos-por-grupo"><span class="header-section-number">14.1</span> Estadísticos descriptivos por grupo</h2>
<p>Antes de aplicar ningún contraste, conviene describir la variable cuantitativa de interés en cada uno de los grupos. Se utiliza aquí la variable <code>notaC</code>, que es la que muestra diferencias más claras entre los tres grupos de clase.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(moments)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>df <span class="sc">|&gt;</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(grupo) <span class="sc">|&gt;</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(notaC)),</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(notaC, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">de =</span> <span class="fu">sd</span>(notaC, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(notaC, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">q1 =</span> <span class="fu">quantile</span>(notaC, <span class="fl">0.25</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(notaC, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">q3 =</span> <span class="fu">quantile</span>(notaC, <span class="fl">0.75</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(notaC, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">asimetria =</span> <span class="fu">skewness</span>(notaC, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">apuntamiento =</span> <span class="fu">kurtosis</span>(notaC, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 11
  grupo     n media    de minimo    q1 mediana    q3 maximo asimetria
  &lt;chr&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;
1 A        38  5.52  1.51    2     4.6    5.55   6.5    9.5    0.0121
2 B        34  5.95  1.35    2.8   5.3    6      6.9    8.8   -0.473 
3 C        47  4.07  1.38    1.3   3.3    4      5.1    6.7   -0.0272
# ℹ 1 more variable: apuntamiento &lt;dbl&gt;</code></pre>
</div>
</div>
<p>El grupo C presenta la media más baja (4.07) y los grupos A y B medias parecidas y más altas (5.52 y 5.95, respectivamente), lo que ya sugiere que podría existir una diferencia real entre C y los otros dos grupos. Las tres distribuciones tienen una asimetría cercana a 0 y un apuntamiento próximo a 3, lo que es compatible con una distribución aproximadamente normal en los tres grupos.</p>
<p><strong>Gráficos.</strong> Un diagrama de cajas y bigotes y un diagrama de violín permiten visualizar de un vistazo estas diferencias:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> grupo, <span class="at">y =</span> notaC, <span class="at">fill =</span> grupo)) <span class="sc">+</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Grupo"</span>, <span class="at">y =</span> <span class="st">"Nota C"</span>) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="14-contrastes-mas-dos-poblaciones-independientes_files/figure-html/boxplot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Diagrama de cajas y bigotes de la nota C por grupo.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> grupo, <span class="at">y =</span> notaC, <span class="at">fill =</span> grupo)) <span class="sc">+</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>() <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Grupo"</span>, <span class="at">y =</span> <span class="st">"Nota C"</span>) <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="14-contrastes-mas-dos-poblaciones-independientes_files/figure-html/violin-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Diagrama de violín de la nota C por grupo.</figcaption>
</figure>
</div>
</div>
</div>
<p>En ambos gráficos se aprecia que el grupo C tiene una posición más baja que A y B, y que las cajas de A y B se solapan bastante, mientras que la de C apenas se solapa con ellas.</p>
<p><strong>Normalidad por grupo.</strong> Antes de decidir qué contraste aplicar (paramétrico o no paramétrico), es necesario comprobar si <code>notaC</code> sigue una distribución normal en cada uno de los tres grupos, mediante el test de Shapiro-Wilk:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(notaC)) <span class="sc">|&gt;</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(grupo) <span class="sc">|&gt;</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">estadistico =</span> <span class="fu">shapiro.test</span>(notaC)<span class="sc">$</span>statistic,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">p.valor =</span> <span class="fu">shapiro.test</span>(notaC)<span class="sc">$</span>p.value</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  grupo estadistico p.valor
  &lt;chr&gt;       &lt;dbl&gt;   &lt;dbl&gt;
1 A           0.989   0.961
2 B           0.965   0.343
3 C           0.976   0.442</code></pre>
</div>
</div>
<p>En los tres grupos el p-valor es muy superior a 0.05 (0.9614 en A, 0.3432 en B y 0.4420 en C), por lo que no hay evidencia para rechazar la normalidad de <code>notaC</code> en ninguno de ellos. Se cumple, por tanto, el requisito de normalidad necesario para aplicar los contrastes paramétricos que siguen.</p>
<section id="test-de-levene-de-comparación-de-varianzas" class="level3" data-number="14.1.1">
<h3 data-number="14.1.1" class="anchored" data-anchor-id="test-de-levene-de-comparación-de-varianzas"><span class="header-section-number">14.1.1</span> Test de Levene de comparación de varianzas</h3>
<div id="def-masdosindep-levene" class="theorem definition">
<p><span class="theorem-title"><strong>Definición 14.1 (Test de Levene de comparación de varianzas)</strong></span> El <em>test de Levene</em> tiene como objetivo contrastar si las varianzas de una variable cuantitativa son iguales en más de dos poblaciones independientes. Es la generalización a más de dos grupos del test F de Fisher visto en el capítulo anterior. Las hipótesis del contraste son</p>
<p><span class="math display">\[H_0: \sigma_1^2=\sigma_2^2=\cdots=\sigma_k^2 \quad \text{frente a} \quad H_1: \text{algún } \sigma_i^2 \text{ es distinto de los demás},\]</span></p>
<p>donde <span class="math inline">\(k\)</span> es el número de poblaciones comparadas.</p>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Interpretación">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Interpretación
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Si el p-valor del contraste es mayor que el nivel de significación (habitualmente 0.05), no se rechaza <span class="math inline">\(H_0\)</span> y se concluye que las varianzas de los <span class="math inline">\(k\)</span> grupos pueden considerarse homogéneas.</li>
<li>Si el p-valor es menor que el nivel de significación, se rechaza <span class="math inline">\(H_0\)</span> y se concluye que al menos uno de los grupos tiene una varianza distinta de las demás.</li>
<li>Comprobar la homogeneidad de varianzas es un paso previo necesario para poder aplicar después el ANOVA de un factor, ya que este último asume que las varianzas de los grupos son iguales.</li>
</ul>
</div>
</div>
<p><strong>Requisitos</strong>:</p>
<ul>
<li>La variable comparada debe ser cuantitativa.</li>
<li>Las poblaciones comparadas deben ser independientes entre sí (individuos distintos en cada grupo).</li>
<li>La variable debe seguir una distribución normal en todos los grupos, o bien el tamaño de cada grupo debe ser igual o superior a 30 (en cuyo caso el teorema central del límite garantiza una aproximación razonable).</li>
</ul>
<p>Comprobada la normalidad de <code>notaC</code> en los tres grupos, se puede aplicar el test de Levene con la función <code>leveneTest()</code> del paquete <code>car</code> para contrastar si las tres poblaciones tienen la misma varianza.</p>
<div id="exm-masdosindep-levene" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 14.1</strong></span> &nbsp;</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">grupo =</span> <span class="fu">factor</span>(grupo))</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(notaC <span class="sc">~</span> grupo, <span class="at">data =</span> df)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
       Df F value Pr(&gt;F)
group   2  0.3186 0.7278
      116               </code></pre>
</div>
</div>
<p>El p-valor del contraste es 0.7278, muy superior a 0.05, por lo que no se rechaza <span class="math inline">\(H_0\)</span>: no hay evidencia de que las varianzas de <code>notaC</code> difieran entre los tres grupos de clase. Se cumple, por tanto, el requisito de homogeneidad de varianzas necesario para aplicar el ANOVA de un factor.</p>
</div>
</section>
<section id="anova-de-un-factor" class="level3" data-number="14.1.2">
<h3 data-number="14.1.2" class="anchored" data-anchor-id="anova-de-un-factor"><span class="header-section-number">14.1.2</span> ANOVA de un factor</h3>
<div id="def-masdosindep-anova" class="theorem definition">
<p><span class="theorem-title"><strong>Definición 14.2 (ANOVA de un factor)</strong></span> El <em>análisis de varianza (ANOVA) de un factor</em> tiene como objetivo contrastar si existen diferencias entre las medias de una variable cuantitativa en más de dos poblaciones independientes. Las hipótesis del contraste son</p>
<p><span class="math display">\[H_0: \mu_1=\mu_2=\cdots=\mu_k \quad \text{frente a} \quad H_1: \text{alguna } \mu_i \text{ es distinta de las demás},\]</span></p>
<p>donde <span class="math inline">\(k\)</span> es el número de poblaciones comparadas.</p>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Interpretación">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Interpretación
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Si el p-valor del contraste es mayor que 0.05, no se rechaza <span class="math inline">\(H_0\)</span> y se concluye que no hay evidencia de diferencias entre las medias de los <span class="math inline">\(k\)</span> grupos.</li>
<li>Si el p-valor es menor que 0.05, se rechaza <span class="math inline">\(H_0\)</span> y se concluye que al menos una de las medias difiere de las demás, aunque el ANOVA por sí solo no indica cuál o cuáles.</li>
<li>El ANOVA de un factor es la generalización a más de dos grupos del test t de comparación de medias visto en el capítulo anterior: de hecho, cuando <span class="math inline">\(k=2\)</span>, ambos contrastes son equivalentes.</li>
</ul>
</div>
</div>
<p><strong>Requisitos</strong>:</p>
<ul>
<li>La variable dependiente debe ser cuantitativa.</li>
<li>Las poblaciones comparadas deben ser independientes entre sí.</li>
<li>La variable debe seguir una distribución normal en cada uno de los grupos, o los grupos deben tener un tamaño igual o superior a 30.</li>
<li>Las varianzas de los grupos deben ser homogéneas, requisito que se comprueba previamente con el test de Levene.</li>
</ul>
<p>Como se cumplen los requisitos de normalidad y homogeneidad de varianzas, se puede aplicar el ANOVA de un factor con la función <code>aov()</code> para contrastar si existen diferencias entre las medias de <code>notaC</code> en los tres grupos.</p>
<div id="exm-masdosindep-anova" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 14.2</strong></span> &nbsp;</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>modelo_anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(notaC <span class="sc">~</span> grupo, <span class="at">data =</span> df)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_anova)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
grupo         2  80.69   40.34   20.05 3.32e-08 ***
Residuals   116 233.41    2.01                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
1 observation deleted due to missingness</code></pre>
</div>
</div>
<p>El p-valor del contraste (<code>Pr(&gt;F)</code>) es 3.32e-08, muy inferior a 0.05, por lo que se rechaza <span class="math inline">\(H_0\)</span>: existen diferencias significativas entre las medias de <code>notaC</code> en al menos dos de los tres grupos de clase.</p>
</div>
<p>Cuando, como en este caso, el ANOVA resulta significativo, este solo informa de que existe alguna diferencia entre los grupos, pero no indica entre cuáles. Es necesario entonces aplicar un <strong>test de comparación múltiple por pares</strong> que compare las medias de los grupos dos a dos, controlando el error global de realizar varias comparaciones simultáneas. El más habitual es el <strong>test de Tukey</strong> (<code>TukeyHSD()</code>), aunque también se utiliza, de forma algo más conservadora, la corrección de <strong>Bonferroni</strong>, que simplemente divide el nivel de significación entre el número de comparaciones realizadas.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(modelo_anova)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = notaC ~ grupo, data = df)

$grupo
          diff        lwr        upr     p adj
B-A  0.4312693 -0.3637573  1.2262960 0.4048482
C-A -1.4455767 -2.1802858 -0.7108676 0.0000241
C-B -1.8768461 -2.6350758 -1.1186163 0.0000001</code></pre>
</div>
</div>
<p>Los resultados muestran que la diferencia entre B y A no es significativa (p-valor 0.4048), mientras que las diferencias entre C y A (p-valor 0.0000241) y entre C y B (p-valor 0.0000001) sí lo son. Es decir, el grupo C tiene una nota media en <code>notaC</code> significativamente inferior a la de los otros dos grupos, mientras que A y B no difieren significativamente entre sí.</p>
<p>Un diagrama de medias con sus intervalos de confianza al 95% permite visualizar estas mismas conclusiones:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>mean_ci <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> x[<span class="sc">!</span><span class="fu">is.na</span>(x)]</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  m <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  se <span class="ot">&lt;-</span> <span class="fu">sd</span>(x) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">length</span>(x))</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  ic <span class="ot">&lt;-</span> se <span class="sc">*</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="fu">length</span>(x) <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">y =</span> m, <span class="at">ymin =</span> m <span class="sc">-</span> ic, <span class="at">ymax =</span> m <span class="sc">+</span> ic)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> grupo, <span class="at">y =</span> notaC, <span class="at">color =</span> grupo)) <span class="sc">+</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_ci, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Grupo"</span>, <span class="at">y =</span> <span class="st">"Nota C media"</span>) <span class="sc">+</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="14-contrastes-mas-dos-poblaciones-independientes_files/figure-html/medias-ic-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Medias de la nota C por grupo con intervalos de confianza al 95%.</figcaption>
</figure>
</div>
</div>
</div>
<p>En el gráfico se aprecia que los intervalos de confianza de A y B se solapan ampliamente, mientras que el de C queda claramente por debajo y no se solapa con los de los otros dos grupos, en consonancia con el resultado del test de Tukey.</p>
</section>
<section id="test-de-kruskal-wallis-no-paramétrico" class="level3" data-number="14.1.3">
<h3 data-number="14.1.3" class="anchored" data-anchor-id="test-de-kruskal-wallis-no-paramétrico"><span class="header-section-number">14.1.3</span> Test de Kruskal-Wallis (no paramétrico)</h3>
<div id="def-masdosindep-kruskal" class="theorem definition">
<p><span class="theorem-title"><strong>Definición 14.3 (Test de Kruskal-Wallis)</strong></span> El <em>test de Kruskal-Wallis</em> es la alternativa no paramétrica al ANOVA de un factor. Tiene como objetivo contrastar si las distribuciones de una variable cuantitativa u ordinal son iguales en más de dos poblaciones independientes, sin necesidad de asumir normalidad. Las hipótesis del contraste son</p>
<p><span class="math display">\[H_0: \text{las distribuciones (medianas) son iguales en las } k \text{ poblaciones} \quad \text{frente a} \quad H_1: \text{alguna difiere de las demás}.\]</span></p>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Interpretación">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Interpretación
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Si el p-valor del contraste es mayor que 0.05, no se rechaza <span class="math inline">\(H_0\)</span> y se concluye que no hay evidencia de diferencias entre las distribuciones de los <span class="math inline">\(k\)</span> grupos.</li>
<li>Si el p-valor es menor que 0.05, se rechaza <span class="math inline">\(H_0\)</span> y se concluye que al menos una de las distribuciones difiere de las demás.</li>
<li>El test de Kruskal-Wallis es la generalización a más de dos grupos del test U de Mann-Whitney visto en el capítulo anterior, del mismo modo que el ANOVA generaliza al test t.</li>
</ul>
</div>
</div>
<p><strong>Requisitos</strong>:</p>
<ul>
<li>La variable comparada debe ser, al menos, ordinal (cuantitativa o cualitativa ordinal).</li>
<li>Las poblaciones comparadas deben ser independientes entre sí.</li>
<li>A diferencia del ANOVA, no exige que la variable siga una distribución normal en los grupos, lo que lo convierte en la alternativa natural cuando no se cumple ese requisito o cuando la variable es solo ordinal.</li>
</ul>
<p>Cuando no se cumple el requisito de normalidad del ANOVA (o directamente se quiere evitar esa suposición), se recurre al test de Kruskal-Wallis. A modo de ejemplo, se aplica ahora a la variable <code>notaA</code>, que no se ha comprobado que sea normal en los tres grupos:</p>
<div id="exm-masdosindep-kruskal" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 14.3</strong></span> &nbsp;</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(notaA <span class="sc">~</span> grupo, <span class="at">data =</span> df)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  notaA by grupo
Kruskal-Wallis chi-squared = 62.218, df = 2, p-value = 3.087e-14</code></pre>
</div>
</div>
<p>El p-valor del contraste es 3.087e-14, muy inferior a 0.05, por lo que se rechaza <span class="math inline">\(H_0\)</span>: existen diferencias significativas entre las distribuciones de <code>notaA</code> en al menos dos de los tres grupos.</p>
</div>
<p>Igual que ocurre con el ANOVA, un resultado significativo en el test de Kruskal-Wallis no indica entre qué grupos concretos hay diferencias. El test de comparación múltiple por pares equivalente es el <strong>test de Wilcoxon por pares</strong>, aplicando una corrección (aquí, el método de Benjamini-Hochberg, <code>"BH"</code>) para controlar el error acumulado al hacer varias comparaciones:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.wilcox.test</span>(df<span class="sc">$</span>notaA, df<span class="sc">$</span>grupo, <span class="at">p.adjust.method =</span> <span class="st">"BH"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using Wilcoxon rank sum test with continuity correction 

data:  df$notaA and df$grupo 

  A       B      
B 0.19    -      
C 4.2e-10 1.3e-11

P value adjustment method: BH </code></pre>
</div>
</div>
<p>La diferencia entre A y B no es significativa (p-valor 0.19), mientras que las diferencias entre A y C (p-valor 4.2e-10) y entre B y C (p-valor 1.3e-11) sí lo son. La conclusión es, por tanto, coherente con la obtenida antes para <code>notaC</code>: el grupo C se diferencia claramente de los otros dos, que no difieren significativamente entre sí.</p>
</section>
</section>
<section id="variable-dependiente-cualitativa" class="level2" data-number="14.2">
<h2 data-number="14.2" class="anchored" data-anchor-id="variable-dependiente-cualitativa"><span class="header-section-number">14.2</span> Variable dependiente cualitativa</h2>
<p>Cuando la variable dependiente es cualitativa y se compara entre más de dos poblaciones independientes, el contraste apropiado sigue siendo el <strong>test Chi-cuadrado de independencia</strong>, ya presentado en el capítulo de <a href="./12-contrastes-dos-poblaciones-independientes.html">Contrastes para dos poblaciones independientes</a>. Allí se aplicaba a una tabla de contingencia <span class="math inline">\(2\times2\)</span>, construida cruzando una variable independiente con dos categorías y una variable dependiente también con dos categorías; aquí la única diferencia es que la tabla de contingencia tiene más de dos filas (o más de dos columnas), al tener <code>grupo</code> tres categorías en lugar de dos.</p>
<p>Así, para contrastar si existe relación entre el grupo de clase y el resultado (aprobado o suspenso) en la asignatura A, bastaría con construir la tabla de contingencia <code>table(df$grupo, df$calificacionA)</code>, de dimensión <span class="math inline">\(3\times2\)</span>, y aplicar sobre ella <code>chisq.test()</code> exactamente igual que en el caso de dos grupos. El estadístico de contraste, sus grados de libertad (que ahora dependen del número de filas y columnas de la tabla) y la interpretación del p-valor obtenido no cambian en absoluto respecto al procedimiento ya descrito para dos poblaciones independientes.</p>
</section>
<section id="cierre" class="level2" data-number="14.3">
<h2 data-number="14.3" class="anchored" data-anchor-id="cierre"><span class="header-section-number">14.3</span> Cierre</h2>
<p>Este capítulo ha mostrado cómo comparar más de dos poblaciones independientes, tanto cuando la variable dependiente es cuantitativa (Levene, ANOVA y Tukey, o su alternativa no paramétrica, Kruskal-Wallis con comparaciones de Wilcoxon por pares) como cuando es cualitativa (Chi-cuadrado de independencia). El siguiente capítulo, <a href="./15-contrastes-medidas-repetidas.html">Contrastes para más de dos poblaciones relacionadas</a>, trata la situación análoga pero cuando los más de dos grupos comparados no están formados por individuos distintos, sino que son medidas repetidas tomadas sobre los mismos sujetos.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./13-contrastes-dos-poblaciones-pareadas.html" class="pagination-link" aria-label="Contrastes para dos poblaciones pareadas">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Contrastes para dos poblaciones pareadas</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./15-contrastes-medidas-repetidas.html" class="pagination-link" aria-label="Contrastes para más de dos poblaciones relacionadas (medidas repetidas)">
        <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Contrastes para más de dos poblaciones relacionadas (medidas repetidas)</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Ejecutar el código</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> Contrastes para más de dos poblaciones independientes</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="an">lang:</span><span class="co"> es</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="in">```{r setup, include=FALSE}</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">message =</span> <span class="cn">FALSE</span>, <span class="at">warning =</span> <span class="cn">FALSE</span>)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"datos/datos-curso.csv"</span>)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>El <span class="co">[</span><span class="ot">capítulo anterior</span><span class="co">](12-contrastes-dos-poblaciones-independientes.qmd)</span> trató el caso de dos poblaciones independientes. Sin embargo, en muchas ocasiones no se comparan dos grupos, sino tres o más, formados por individuos distintos entre sí. Este capítulo generaliza los contrastes anteriores a esa situación: cómo comparar una variable, cuantitativa o cualitativa, entre más de dos poblaciones independientes. En el conjunto de datos de ejemplo, la variable independiente natural para esta situación es <span class="in">`grupo`</span>, que clasifica a los 120 alumnos en tres grupos de clase (A, B y C), formados por alumnos distintos: nadie pertenece a la vez a dos grupos, por lo que las tres poblaciones son independientes entre sí.</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a><span class="fu">## Estadísticos descriptivos por grupo</span></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>Antes de aplicar ningún contraste, conviene describir la variable cuantitativa de interés en cada uno de los grupos. Se utiliza aquí la variable <span class="in">`notaC`</span>, que es la que muestra diferencias más claras entre los tres grupos de clase.</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a><span class="in">```{r descriptivos}</span></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(moments)</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>df <span class="sc">|&gt;</span></span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(grupo) <span class="sc">|&gt;</span></span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(notaC)),</span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(notaC, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">de =</span> <span class="fu">sd</span>(notaC, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(notaC, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">q1 =</span> <span class="fu">quantile</span>(notaC, <span class="fl">0.25</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(notaC, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">q3 =</span> <span class="fu">quantile</span>(notaC, <span class="fl">0.75</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(notaC, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-32"><a href="#cb18-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">asimetria =</span> <span class="fu">skewness</span>(notaC, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-33"><a href="#cb18-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">apuntamiento =</span> <span class="fu">kurtosis</span>(notaC, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb18-34"><a href="#cb18-34" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-35"><a href="#cb18-35" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-36"><a href="#cb18-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-37"><a href="#cb18-37" aria-hidden="true" tabindex="-1"></a>El grupo C presenta la media más baja (4.07) y los grupos A y B medias parecidas y más altas (5.52 y 5.95, respectivamente), lo que ya sugiere que podría existir una diferencia real entre C y los otros dos grupos. Las tres distribuciones tienen una asimetría cercana a 0 y un apuntamiento próximo a 3, lo que es compatible con una distribución aproximadamente normal en los tres grupos.</span>
<span id="cb18-38"><a href="#cb18-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-39"><a href="#cb18-39" aria-hidden="true" tabindex="-1"></a>**Gráficos.** Un diagrama de cajas y bigotes y un diagrama de violín permiten visualizar de un vistazo estas diferencias:</span>
<span id="cb18-40"><a href="#cb18-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-41"><a href="#cb18-41" aria-hidden="true" tabindex="-1"></a><span class="in">```{r boxplot, fig.cap="Diagrama de cajas y bigotes de la nota C por grupo."}</span></span>
<span id="cb18-42"><a href="#cb18-42" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> grupo, <span class="at">y =</span> notaC, <span class="at">fill =</span> grupo)) <span class="sc">+</span></span>
<span id="cb18-43"><a href="#cb18-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb18-44"><a href="#cb18-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Grupo"</span>, <span class="at">y =</span> <span class="st">"Nota C"</span>) <span class="sc">+</span></span>
<span id="cb18-45"><a href="#cb18-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb18-46"><a href="#cb18-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span>
<span id="cb18-47"><a href="#cb18-47" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-48"><a href="#cb18-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-49"><a href="#cb18-49" aria-hidden="true" tabindex="-1"></a><span class="in">```{r violin, fig.cap="Diagrama de violín de la nota C por grupo."}</span></span>
<span id="cb18-50"><a href="#cb18-50" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> grupo, <span class="at">y =</span> notaC, <span class="at">fill =</span> grupo)) <span class="sc">+</span></span>
<span id="cb18-51"><a href="#cb18-51" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>() <span class="sc">+</span></span>
<span id="cb18-52"><a href="#cb18-52" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Grupo"</span>, <span class="at">y =</span> <span class="st">"Nota C"</span>) <span class="sc">+</span></span>
<span id="cb18-53"><a href="#cb18-53" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb18-54"><a href="#cb18-54" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span>
<span id="cb18-55"><a href="#cb18-55" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-56"><a href="#cb18-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-57"><a href="#cb18-57" aria-hidden="true" tabindex="-1"></a>En ambos gráficos se aprecia que el grupo C tiene una posición más baja que A y B, y que las cajas de A y B se solapan bastante, mientras que la de C apenas se solapa con ellas.</span>
<span id="cb18-58"><a href="#cb18-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-59"><a href="#cb18-59" aria-hidden="true" tabindex="-1"></a>**Normalidad por grupo.** Antes de decidir qué contraste aplicar (paramétrico o no paramétrico), es necesario comprobar si <span class="in">`notaC`</span> sigue una distribución normal en cada uno de los tres grupos, mediante el test de Shapiro-Wilk:</span>
<span id="cb18-60"><a href="#cb18-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-61"><a href="#cb18-61" aria-hidden="true" tabindex="-1"></a><span class="in">```{r shapiro-grupo}</span></span>
<span id="cb18-62"><a href="#cb18-62" aria-hidden="true" tabindex="-1"></a>df <span class="sc">|&gt;</span></span>
<span id="cb18-63"><a href="#cb18-63" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(notaC)) <span class="sc">|&gt;</span></span>
<span id="cb18-64"><a href="#cb18-64" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(grupo) <span class="sc">|&gt;</span></span>
<span id="cb18-65"><a href="#cb18-65" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb18-66"><a href="#cb18-66" aria-hidden="true" tabindex="-1"></a>    <span class="at">estadistico =</span> <span class="fu">shapiro.test</span>(notaC)<span class="sc">$</span>statistic,</span>
<span id="cb18-67"><a href="#cb18-67" aria-hidden="true" tabindex="-1"></a>    <span class="at">p.valor =</span> <span class="fu">shapiro.test</span>(notaC)<span class="sc">$</span>p.value</span>
<span id="cb18-68"><a href="#cb18-68" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-69"><a href="#cb18-69" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-70"><a href="#cb18-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-71"><a href="#cb18-71" aria-hidden="true" tabindex="-1"></a>En los tres grupos el p-valor es muy superior a 0.05 (0.9614 en A, 0.3432 en B y 0.4420 en C), por lo que no hay evidencia para rechazar la normalidad de <span class="in">`notaC`</span> en ninguno de ellos. Se cumple, por tanto, el requisito de normalidad necesario para aplicar los contrastes paramétricos que siguen.</span>
<span id="cb18-72"><a href="#cb18-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-73"><a href="#cb18-73" aria-hidden="true" tabindex="-1"></a><span class="fu">### Test de Levene de comparación de varianzas</span></span>
<span id="cb18-74"><a href="#cb18-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-75"><a href="#cb18-75" aria-hidden="true" tabindex="-1"></a>:::{#def-masdosindep-levene}</span>
<span id="cb18-76"><a href="#cb18-76" aria-hidden="true" tabindex="-1"></a><span class="fu">## Test de Levene de comparación de varianzas</span></span>
<span id="cb18-77"><a href="#cb18-77" aria-hidden="true" tabindex="-1"></a>El _test de Levene_ tiene como objetivo contrastar si las varianzas de una variable cuantitativa son iguales en más de dos poblaciones independientes. Es la generalización a más de dos grupos del test F de Fisher visto en el capítulo anterior. Las hipótesis del contraste son</span>
<span id="cb18-78"><a href="#cb18-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-79"><a href="#cb18-79" aria-hidden="true" tabindex="-1"></a>$$H_0: \sigma_1^2=\sigma_2^2=\cdots=\sigma_k^2 \quad \text{frente a} \quad H_1: \text{algún } \sigma_i^2 \text{ es distinto de los demás},$$</span>
<span id="cb18-80"><a href="#cb18-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-81"><a href="#cb18-81" aria-hidden="true" tabindex="-1"></a>donde $k$ es el número de poblaciones comparadas.</span>
<span id="cb18-82"><a href="#cb18-82" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb18-83"><a href="#cb18-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-84"><a href="#cb18-84" aria-hidden="true" tabindex="-1"></a>:::{.callout-note title=Interpretación}</span>
<span id="cb18-85"><a href="#cb18-85" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Si el p-valor del contraste es mayor que el nivel de significación (habitualmente 0.05), no se rechaza $H_0$ y se concluye que las varianzas de los $k$ grupos pueden considerarse homogéneas.</span>
<span id="cb18-86"><a href="#cb18-86" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Si el p-valor es menor que el nivel de significación, se rechaza $H_0$ y se concluye que al menos uno de los grupos tiene una varianza distinta de las demás.</span>
<span id="cb18-87"><a href="#cb18-87" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Comprobar la homogeneidad de varianzas es un paso previo necesario para poder aplicar después el ANOVA de un factor, ya que este último asume que las varianzas de los grupos son iguales.</span>
<span id="cb18-88"><a href="#cb18-88" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb18-89"><a href="#cb18-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-90"><a href="#cb18-90" aria-hidden="true" tabindex="-1"></a>**Requisitos**:</span>
<span id="cb18-91"><a href="#cb18-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-92"><a href="#cb18-92" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>La variable comparada debe ser cuantitativa.</span>
<span id="cb18-93"><a href="#cb18-93" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Las poblaciones comparadas deben ser independientes entre sí (individuos distintos en cada grupo).</span>
<span id="cb18-94"><a href="#cb18-94" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>La variable debe seguir una distribución normal en todos los grupos, o bien el tamaño de cada grupo debe ser igual o superior a 30 (en cuyo caso el teorema central del límite garantiza una aproximación razonable).</span>
<span id="cb18-95"><a href="#cb18-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-96"><a href="#cb18-96" aria-hidden="true" tabindex="-1"></a>Comprobada la normalidad de <span class="in">`notaC`</span> en los tres grupos, se puede aplicar el test de Levene con la función <span class="in">`leveneTest()`</span> del paquete <span class="in">`car`</span> para contrastar si las tres poblaciones tienen la misma varianza.</span>
<span id="cb18-97"><a href="#cb18-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-98"><a href="#cb18-98" aria-hidden="true" tabindex="-1"></a>:::{#exm-masdosindep-levene}</span>
<span id="cb18-99"><a href="#cb18-99" aria-hidden="true" tabindex="-1"></a><span class="in">```{r levene}</span></span>
<span id="cb18-100"><a href="#cb18-100" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb18-101"><a href="#cb18-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-102"><a href="#cb18-102" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">grupo =</span> <span class="fu">factor</span>(grupo))</span>
<span id="cb18-103"><a href="#cb18-103" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(notaC <span class="sc">~</span> grupo, <span class="at">data =</span> df)</span>
<span id="cb18-104"><a href="#cb18-104" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-105"><a href="#cb18-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-106"><a href="#cb18-106" aria-hidden="true" tabindex="-1"></a>El p-valor del contraste es 0.7278, muy superior a 0.05, por lo que no se rechaza $H_0$: no hay evidencia de que las varianzas de <span class="in">`notaC`</span> difieran entre los tres grupos de clase. Se cumple, por tanto, el requisito de homogeneidad de varianzas necesario para aplicar el ANOVA de un factor.</span>
<span id="cb18-107"><a href="#cb18-107" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb18-108"><a href="#cb18-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-109"><a href="#cb18-109" aria-hidden="true" tabindex="-1"></a><span class="fu">### ANOVA de un factor</span></span>
<span id="cb18-110"><a href="#cb18-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-111"><a href="#cb18-111" aria-hidden="true" tabindex="-1"></a>:::{#def-masdosindep-anova}</span>
<span id="cb18-112"><a href="#cb18-112" aria-hidden="true" tabindex="-1"></a><span class="fu">## ANOVA de un factor</span></span>
<span id="cb18-113"><a href="#cb18-113" aria-hidden="true" tabindex="-1"></a>El _análisis de varianza (ANOVA) de un factor_ tiene como objetivo contrastar si existen diferencias entre las medias de una variable cuantitativa en más de dos poblaciones independientes. Las hipótesis del contraste son</span>
<span id="cb18-114"><a href="#cb18-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-115"><a href="#cb18-115" aria-hidden="true" tabindex="-1"></a>$$H_0: \mu_1=\mu_2=\cdots=\mu_k \quad \text{frente a} \quad H_1: \text{alguna } \mu_i \text{ es distinta de las demás},$$</span>
<span id="cb18-116"><a href="#cb18-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-117"><a href="#cb18-117" aria-hidden="true" tabindex="-1"></a>donde $k$ es el número de poblaciones comparadas.</span>
<span id="cb18-118"><a href="#cb18-118" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb18-119"><a href="#cb18-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-120"><a href="#cb18-120" aria-hidden="true" tabindex="-1"></a>:::{.callout-note title=Interpretación}</span>
<span id="cb18-121"><a href="#cb18-121" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Si el p-valor del contraste es mayor que 0.05, no se rechaza $H_0$ y se concluye que no hay evidencia de diferencias entre las medias de los $k$ grupos.</span>
<span id="cb18-122"><a href="#cb18-122" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Si el p-valor es menor que 0.05, se rechaza $H_0$ y se concluye que al menos una de las medias difiere de las demás, aunque el ANOVA por sí solo no indica cuál o cuáles.</span>
<span id="cb18-123"><a href="#cb18-123" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>El ANOVA de un factor es la generalización a más de dos grupos del test t de comparación de medias visto en el capítulo anterior: de hecho, cuando $k=2$, ambos contrastes son equivalentes.</span>
<span id="cb18-124"><a href="#cb18-124" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb18-125"><a href="#cb18-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-126"><a href="#cb18-126" aria-hidden="true" tabindex="-1"></a>**Requisitos**:</span>
<span id="cb18-127"><a href="#cb18-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-128"><a href="#cb18-128" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>La variable dependiente debe ser cuantitativa.</span>
<span id="cb18-129"><a href="#cb18-129" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Las poblaciones comparadas deben ser independientes entre sí.</span>
<span id="cb18-130"><a href="#cb18-130" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>La variable debe seguir una distribución normal en cada uno de los grupos, o los grupos deben tener un tamaño igual o superior a 30.</span>
<span id="cb18-131"><a href="#cb18-131" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Las varianzas de los grupos deben ser homogéneas, requisito que se comprueba previamente con el test de Levene.</span>
<span id="cb18-132"><a href="#cb18-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-133"><a href="#cb18-133" aria-hidden="true" tabindex="-1"></a>Como se cumplen los requisitos de normalidad y homogeneidad de varianzas, se puede aplicar el ANOVA de un factor con la función <span class="in">`aov()`</span> para contrastar si existen diferencias entre las medias de <span class="in">`notaC`</span> en los tres grupos.</span>
<span id="cb18-134"><a href="#cb18-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-135"><a href="#cb18-135" aria-hidden="true" tabindex="-1"></a>:::{#exm-masdosindep-anova}</span>
<span id="cb18-136"><a href="#cb18-136" aria-hidden="true" tabindex="-1"></a><span class="in">```{r anova}</span></span>
<span id="cb18-137"><a href="#cb18-137" aria-hidden="true" tabindex="-1"></a>modelo_anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(notaC <span class="sc">~</span> grupo, <span class="at">data =</span> df)</span>
<span id="cb18-138"><a href="#cb18-138" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_anova)</span>
<span id="cb18-139"><a href="#cb18-139" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-140"><a href="#cb18-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-141"><a href="#cb18-141" aria-hidden="true" tabindex="-1"></a>El p-valor del contraste (<span class="in">`Pr(&gt;F)`</span>) es 3.32e-08, muy inferior a 0.05, por lo que se rechaza $H_0$: existen diferencias significativas entre las medias de <span class="in">`notaC`</span> en al menos dos de los tres grupos de clase.</span>
<span id="cb18-142"><a href="#cb18-142" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb18-143"><a href="#cb18-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-144"><a href="#cb18-144" aria-hidden="true" tabindex="-1"></a>Cuando, como en este caso, el ANOVA resulta significativo, este solo informa de que existe alguna diferencia entre los grupos, pero no indica entre cuáles. Es necesario entonces aplicar un **test de comparación múltiple por pares** que compare las medias de los grupos dos a dos, controlando el error global de realizar varias comparaciones simultáneas. El más habitual es el **test de Tukey** (`TukeyHSD()`), aunque también se utiliza, de forma algo más conservadora, la corrección de **Bonferroni**, que simplemente divide el nivel de significación entre el número de comparaciones realizadas.</span>
<span id="cb18-145"><a href="#cb18-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-146"><a href="#cb18-146" aria-hidden="true" tabindex="-1"></a><span class="in">```{r tukey}</span></span>
<span id="cb18-147"><a href="#cb18-147" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(modelo_anova)</span>
<span id="cb18-148"><a href="#cb18-148" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-149"><a href="#cb18-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-150"><a href="#cb18-150" aria-hidden="true" tabindex="-1"></a>Los resultados muestran que la diferencia entre B y A no es significativa (p-valor 0.4048), mientras que las diferencias entre C y A (p-valor 0.0000241) y entre C y B (p-valor 0.0000001) sí lo son. Es decir, el grupo C tiene una nota media en <span class="in">`notaC`</span> significativamente inferior a la de los otros dos grupos, mientras que A y B no difieren significativamente entre sí.</span>
<span id="cb18-151"><a href="#cb18-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-152"><a href="#cb18-152" aria-hidden="true" tabindex="-1"></a>Un diagrama de medias con sus intervalos de confianza al 95% permite visualizar estas mismas conclusiones:</span>
<span id="cb18-153"><a href="#cb18-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-154"><a href="#cb18-154" aria-hidden="true" tabindex="-1"></a><span class="in">```{r medias-ic, fig.cap="Medias de la nota C por grupo con intervalos de confianza al 95%."}</span></span>
<span id="cb18-155"><a href="#cb18-155" aria-hidden="true" tabindex="-1"></a>mean_ci <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb18-156"><a href="#cb18-156" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> x[<span class="sc">!</span><span class="fu">is.na</span>(x)]</span>
<span id="cb18-157"><a href="#cb18-157" aria-hidden="true" tabindex="-1"></a>  m <span class="ot">&lt;-</span> <span class="fu">mean</span>(x)</span>
<span id="cb18-158"><a href="#cb18-158" aria-hidden="true" tabindex="-1"></a>  se <span class="ot">&lt;-</span> <span class="fu">sd</span>(x) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">length</span>(x))</span>
<span id="cb18-159"><a href="#cb18-159" aria-hidden="true" tabindex="-1"></a>  ic <span class="ot">&lt;-</span> se <span class="sc">*</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="fu">length</span>(x) <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb18-160"><a href="#cb18-160" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">y =</span> m, <span class="at">ymin =</span> m <span class="sc">-</span> ic, <span class="at">ymax =</span> m <span class="sc">+</span> ic)</span>
<span id="cb18-161"><a href="#cb18-161" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb18-162"><a href="#cb18-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-163"><a href="#cb18-163" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> grupo, <span class="at">y =</span> notaC, <span class="at">color =</span> grupo)) <span class="sc">+</span></span>
<span id="cb18-164"><a href="#cb18-164" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_ci, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb18-165"><a href="#cb18-165" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb18-166"><a href="#cb18-166" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Grupo"</span>, <span class="at">y =</span> <span class="st">"Nota C media"</span>) <span class="sc">+</span></span>
<span id="cb18-167"><a href="#cb18-167" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb18-168"><a href="#cb18-168" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span>
<span id="cb18-169"><a href="#cb18-169" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-170"><a href="#cb18-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-171"><a href="#cb18-171" aria-hidden="true" tabindex="-1"></a>En el gráfico se aprecia que los intervalos de confianza de A y B se solapan ampliamente, mientras que el de C queda claramente por debajo y no se solapa con los de los otros dos grupos, en consonancia con el resultado del test de Tukey.</span>
<span id="cb18-172"><a href="#cb18-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-173"><a href="#cb18-173" aria-hidden="true" tabindex="-1"></a><span class="fu">### Test de Kruskal-Wallis (no paramétrico)</span></span>
<span id="cb18-174"><a href="#cb18-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-175"><a href="#cb18-175" aria-hidden="true" tabindex="-1"></a>:::{#def-masdosindep-kruskal}</span>
<span id="cb18-176"><a href="#cb18-176" aria-hidden="true" tabindex="-1"></a><span class="fu">## Test de Kruskal-Wallis</span></span>
<span id="cb18-177"><a href="#cb18-177" aria-hidden="true" tabindex="-1"></a>El _test de Kruskal-Wallis_ es la alternativa no paramétrica al ANOVA de un factor. Tiene como objetivo contrastar si las distribuciones de una variable cuantitativa u ordinal son iguales en más de dos poblaciones independientes, sin necesidad de asumir normalidad. Las hipótesis del contraste son</span>
<span id="cb18-178"><a href="#cb18-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-179"><a href="#cb18-179" aria-hidden="true" tabindex="-1"></a>$$H_0: \text{las distribuciones (medianas) son iguales en las } k \text{ poblaciones} \quad \text{frente a} \quad H_1: \text{alguna difiere de las demás}.$$</span>
<span id="cb18-180"><a href="#cb18-180" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb18-181"><a href="#cb18-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-182"><a href="#cb18-182" aria-hidden="true" tabindex="-1"></a>:::{.callout-note title=Interpretación}</span>
<span id="cb18-183"><a href="#cb18-183" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Si el p-valor del contraste es mayor que 0.05, no se rechaza $H_0$ y se concluye que no hay evidencia de diferencias entre las distribuciones de los $k$ grupos.</span>
<span id="cb18-184"><a href="#cb18-184" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Si el p-valor es menor que 0.05, se rechaza $H_0$ y se concluye que al menos una de las distribuciones difiere de las demás.</span>
<span id="cb18-185"><a href="#cb18-185" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>El test de Kruskal-Wallis es la generalización a más de dos grupos del test U de Mann-Whitney visto en el capítulo anterior, del mismo modo que el ANOVA generaliza al test t.</span>
<span id="cb18-186"><a href="#cb18-186" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb18-187"><a href="#cb18-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-188"><a href="#cb18-188" aria-hidden="true" tabindex="-1"></a>**Requisitos**:</span>
<span id="cb18-189"><a href="#cb18-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-190"><a href="#cb18-190" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>La variable comparada debe ser, al menos, ordinal (cuantitativa o cualitativa ordinal).</span>
<span id="cb18-191"><a href="#cb18-191" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Las poblaciones comparadas deben ser independientes entre sí.</span>
<span id="cb18-192"><a href="#cb18-192" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>A diferencia del ANOVA, no exige que la variable siga una distribución normal en los grupos, lo que lo convierte en la alternativa natural cuando no se cumple ese requisito o cuando la variable es solo ordinal.</span>
<span id="cb18-193"><a href="#cb18-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-194"><a href="#cb18-194" aria-hidden="true" tabindex="-1"></a>Cuando no se cumple el requisito de normalidad del ANOVA (o directamente se quiere evitar esa suposición), se recurre al test de Kruskal-Wallis. A modo de ejemplo, se aplica ahora a la variable <span class="in">`notaA`</span>, que no se ha comprobado que sea normal en los tres grupos:</span>
<span id="cb18-195"><a href="#cb18-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-196"><a href="#cb18-196" aria-hidden="true" tabindex="-1"></a>:::{#exm-masdosindep-kruskal}</span>
<span id="cb18-197"><a href="#cb18-197" aria-hidden="true" tabindex="-1"></a><span class="in">```{r kruskal}</span></span>
<span id="cb18-198"><a href="#cb18-198" aria-hidden="true" tabindex="-1"></a><span class="fu">kruskal.test</span>(notaA <span class="sc">~</span> grupo, <span class="at">data =</span> df)</span>
<span id="cb18-199"><a href="#cb18-199" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-200"><a href="#cb18-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-201"><a href="#cb18-201" aria-hidden="true" tabindex="-1"></a>El p-valor del contraste es 3.087e-14, muy inferior a 0.05, por lo que se rechaza $H_0$: existen diferencias significativas entre las distribuciones de <span class="in">`notaA`</span> en al menos dos de los tres grupos.</span>
<span id="cb18-202"><a href="#cb18-202" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb18-203"><a href="#cb18-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-204"><a href="#cb18-204" aria-hidden="true" tabindex="-1"></a>Igual que ocurre con el ANOVA, un resultado significativo en el test de Kruskal-Wallis no indica entre qué grupos concretos hay diferencias. El test de comparación múltiple por pares equivalente es el **test de Wilcoxon por pares**, aplicando una corrección (aquí, el método de Benjamini-Hochberg, <span class="in">`"BH"`</span>) para controlar el error acumulado al hacer varias comparaciones:</span>
<span id="cb18-205"><a href="#cb18-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-206"><a href="#cb18-206" aria-hidden="true" tabindex="-1"></a><span class="in">```{r wilcox-pares}</span></span>
<span id="cb18-207"><a href="#cb18-207" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.wilcox.test</span>(df<span class="sc">$</span>notaA, df<span class="sc">$</span>grupo, <span class="at">p.adjust.method =</span> <span class="st">"BH"</span>)</span>
<span id="cb18-208"><a href="#cb18-208" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb18-209"><a href="#cb18-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-210"><a href="#cb18-210" aria-hidden="true" tabindex="-1"></a>La diferencia entre A y B no es significativa (p-valor 0.19), mientras que las diferencias entre A y C (p-valor 4.2e-10) y entre B y C (p-valor 1.3e-11) sí lo son. La conclusión es, por tanto, coherente con la obtenida antes para <span class="in">`notaC`</span>: el grupo C se diferencia claramente de los otros dos, que no difieren significativamente entre sí.</span>
<span id="cb18-211"><a href="#cb18-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-212"><a href="#cb18-212" aria-hidden="true" tabindex="-1"></a><span class="fu">## Variable dependiente cualitativa</span></span>
<span id="cb18-213"><a href="#cb18-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-214"><a href="#cb18-214" aria-hidden="true" tabindex="-1"></a>Cuando la variable dependiente es cualitativa y se compara entre más de dos poblaciones independientes, el contraste apropiado sigue siendo el **test Chi-cuadrado de independencia**, ya presentado en el capítulo de <span class="co">[</span><span class="ot">Contrastes para dos poblaciones independientes</span><span class="co">](12-contrastes-dos-poblaciones-independientes.qmd)</span>. Allí se aplicaba a una tabla de contingencia $2\times2$, construida cruzando una variable independiente con dos categorías y una variable dependiente también con dos categorías; aquí la única diferencia es que la tabla de contingencia tiene más de dos filas (o más de dos columnas), al tener <span class="in">`grupo`</span> tres categorías en lugar de dos.</span>
<span id="cb18-215"><a href="#cb18-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-216"><a href="#cb18-216" aria-hidden="true" tabindex="-1"></a>Así, para contrastar si existe relación entre el grupo de clase y el resultado (aprobado o suspenso) en la asignatura A, bastaría con construir la tabla de contingencia <span class="in">`table(df$grupo, df$calificacionA)`</span>, de dimensión $3\times2$, y aplicar sobre ella <span class="in">`chisq.test()`</span> exactamente igual que en el caso de dos grupos. El estadístico de contraste, sus grados de libertad (que ahora dependen del número de filas y columnas de la tabla) y la interpretación del p-valor obtenido no cambian en absoluto respecto al procedimiento ya descrito para dos poblaciones independientes.</span>
<span id="cb18-217"><a href="#cb18-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-218"><a href="#cb18-218" aria-hidden="true" tabindex="-1"></a><span class="fu">## Cierre</span></span>
<span id="cb18-219"><a href="#cb18-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-220"><a href="#cb18-220" aria-hidden="true" tabindex="-1"></a>Este capítulo ha mostrado cómo comparar más de dos poblaciones independientes, tanto cuando la variable dependiente es cuantitativa (Levene, ANOVA y Tukey, o su alternativa no paramétrica, Kruskal-Wallis con comparaciones de Wilcoxon por pares) como cuando es cualitativa (Chi-cuadrado de independencia). El siguiente capítulo, <span class="co">[</span><span class="ot">Contrastes para más de dos poblaciones relacionadas</span><span class="co">](15-contrastes-medidas-repetidas.qmd)</span>, trata la situación análoga pero cuando los más de dos grupos comparados no están formados por individuos distintos, sino que son medidas repetidas tomadas sobre los mismos sujetos.</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/asalber/estadistica-tipos-estudios/edit/main/14-contrastes-mas-dos-poblaciones-independientes.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li><li><a href="https://github.com/asalber/estadistica-tipos-estudios/issues/new" class="toc-action"><i class="bi empty"></i>Informar de un problema</a></li></ul></div></div></div></footer></body></html>