<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>15&nbsp; Contrastes para más de dos poblaciones relacionadas (medidas repetidas) – Tipos de Estudios Estadísticos</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./16-relacion-entre-variables.html" rel="next">
<link href="./14-contrastes-mas-dos-poblaciones-independientes.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-33269adcf1721b81efc5ea7fcfe7f0ee.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-5a2acb6f4ed5aeb23a104ba421924b87.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-b050db56f2b97c639b7ebc2cf71c06d7.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-5e50218c20039713403b52e69b91eb5d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="15&nbsp; Contrastes para más de dos poblaciones relacionadas (medidas repetidas) – Tipos de Estudios Estadísticos">
<meta property="og:description" content="">
<meta property="og:image" content="15-contrastes-medidas-repetidas_files/figure-html/boxplot-pruebas-1.png">
<meta property="og:site_name" content="Tipos de Estudios Estadísticos">
<meta name="twitter:title" content="15&nbsp; Contrastes para más de dos poblaciones relacionadas (medidas repetidas) – Tipos de Estudios Estadísticos">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="15-contrastes-medidas-repetidas_files/figure-html/boxplot-pruebas-1.png">
<meta name="twitter:site" content="@aprendeconalf">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar floating quarto-dark"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = true;
    const darkModeDefault = authorPrefersDark;
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./10-seleccion-contraste.html">Selección del contraste estadístico</a></li><li class="breadcrumb-item"><a href="./15-contrastes-medidas-repetidas.html"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Contrastes para más de dos poblaciones relacionadas (medidas repetidas)</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Tipos de Estudios Estadísticos</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://aprendeconalf.es" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-house-fill"></i></a>
    <a href="https://github.com/asalber/estadistica-tipos-estudios" title="Ejecutar el código" class="quarto-navigation-tool px-1" aria-label="Ejecutar el código"><i class="bi bi-github"></i></a>
    <a href="./estadistica-tipos-estudios.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo oscuro"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-introduccion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción a los tipos de estudios estadísticos</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Diseños de estudio</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-estudios-descriptivos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Estudios descriptivos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-estudios-transversales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Estudios transversales</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-estudios-cohortes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Estudios de cohortes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-estudios-casos-controles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Estudios de casos y controles</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-estudios-ecologicos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Estudios ecológicos</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-estudios-experimentales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Estudios experimentales</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-estudios-cuasiexperimentales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Estudios cuasiexperimentales</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-encuestas-muestreo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Encuestas y diseño de muestreo</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Selección del contraste estadístico</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-seleccion-contraste.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Selección del contraste estadístico</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-contrastes-una-poblacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Contrastes para una población</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-contrastes-dos-poblaciones-independientes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Contrastes para dos poblaciones independientes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-contrastes-dos-poblaciones-pareadas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Contrastes para dos poblaciones pareadas</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-contrastes-mas-dos-poblaciones-independientes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Contrastes para más de dos poblaciones independientes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-contrastes-medidas-repetidas.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Contrastes para más de dos poblaciones relacionadas (medidas repetidas)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-relacion-entre-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Relación y predicción entre dos variables</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Indice de contenidos</h2>
   
  <ul>
  <li><a href="#preparación-de-los-datos-de-formato-ancho-a-formato-largo" id="toc-preparación-de-los-datos-de-formato-ancho-a-formato-largo" class="nav-link active" data-scroll-target="#preparación-de-los-datos-de-formato-ancho-a-formato-largo"><span class="header-section-number">15.1</span> Preparación de los datos: de formato ancho a formato largo</a></li>
  <li><a href="#comparación-de-las-medidas-repetidas" id="toc-comparación-de-las-medidas-repetidas" class="nav-link" data-scroll-target="#comparación-de-las-medidas-repetidas"><span class="header-section-number">15.2</span> Comparación de las medidas repetidas</a>
  <ul class="collapse">
  <li><a href="#anova-de-medidas-repetidas-de-un-factor" id="toc-anova-de-medidas-repetidas-de-un-factor" class="nav-link" data-scroll-target="#anova-de-medidas-repetidas-de-un-factor"><span class="header-section-number">15.2.1</span> ANOVA de medidas repetidas de un factor</a></li>
  <li><a href="#test-de-friedman" id="toc-test-de-friedman" class="nav-link" data-scroll-target="#test-de-friedman"><span class="header-section-number">15.2.2</span> Test de Friedman</a></li>
  </ul></li>
  <li><a href="#resumen" id="toc-resumen" class="nav-link" data-scroll-target="#resumen"><span class="header-section-number">15.3</span> Resumen</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/asalber/estadistica-tipos-estudios/edit/main/15-contrastes-medidas-repetidas.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li><li><a href="https://github.com/asalber/estadistica-tipos-estudios/issues/new" class="toc-action"><i class="bi empty"></i>Informar de un problema</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./10-seleccion-contraste.html">Selección del contraste estadístico</a></li><li class="breadcrumb-item"><a href="./15-contrastes-medidas-repetidas.html"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Contrastes para más de dos poblaciones relacionadas (medidas repetidas)</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Contrastes para más de dos poblaciones relacionadas (medidas repetidas)</span></h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Código</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Enseñar el código</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Esconder el código</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">Ver el código</a></li></ul></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Este capítulo generaliza el <a href="./13-contrastes-dos-poblaciones-pareadas.html">capítulo anterior</a>, dedicado a dos poblaciones pareadas, al caso de <strong>más de dos</strong> medidas relacionadas tomadas sobre los mismos individuos. Corresponde a la fila de la <a href="./10-seleccion-contraste.html">tabla de decisión</a> en la que la variable independiente es cualitativa con más de dos categorías, pero, a diferencia del <a href="./14-contrastes-mas-dos-poblaciones-independientes.html">capítulo dedicado a poblaciones independientes</a>, esas categorías no distinguen grupos de individuos distintos, sino ocasiones de medida repetidas sobre los mismos individuos. El conjunto de datos del curso dispone de cinco calificaciones distintas, <code>notaA</code>, <code>notaB</code>, <code>notaC</code>, <code>notaD</code> y <code>notaE</code>, obtenidas por los <strong>mismos</strong> 120 alumnos (pueden interpretarse como cinco pruebas o exámenes distintos realizados por cada alumno a lo largo del curso). Estas cinco notas no son, por tanto, cinco poblaciones independientes, sino cinco <strong>medidas repetidas</strong> por individuo, y esa dependencia entre ellas es la que obliga a utilizar contrastes distintos de los vistos en el capítulo anterior sobre poblaciones independientes: ignorarla y tratar las cinco notas como si procedieran de alumnos distintos infravaloraría la precisión real de las comparaciones y podría llevar a conclusiones erróneas.</p>
<section id="preparación-de-los-datos-de-formato-ancho-a-formato-largo" class="level2" data-number="15.1">
<h2 data-number="15.1" class="anchored" data-anchor-id="preparación-de-los-datos-de-formato-ancho-a-formato-largo"><span class="header-section-number">15.1</span> Preparación de los datos: de formato ancho a formato largo</h2>
<p>En <code>df</code>, cada alumno ocupa una única fila y cada una de sus cinco notas ocupa una columna distinta (<code>notaA</code>, …, <code>notaE</code>): es el llamado <strong>formato ancho</strong>. Los contrastes de este capítulo, sin embargo, necesitan el <strong>formato largo</strong>, en el que cada fila representa una única combinación de alumno y prueba. Para pasar de un formato a otro se crea primero un identificador de alumno (el número de fila) y después se reorganizan las cinco columnas de notas en dos columnas nuevas, <code>prueba</code> (con el nombre de la prueba) y <code>nota</code> (con la calificación), usando <code>tidyr::pivot_longer()</code>:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>df_largo <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">alumno =</span> <span class="fu">row_number</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(alumno, notaA, notaB, notaC, notaD, notaE) <span class="sc">%&gt;%</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">"nota"</span>), <span class="at">names_to =</span> <span class="st">"prueba"</span>, <span class="at">values_to =</span> <span class="st">"nota"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prueba =</span> <span class="fu">factor</span>(prueba))</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_largo, <span class="dv">10</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
   alumno prueba  nota
    &lt;int&gt; &lt;fct&gt;  &lt;dbl&gt;
 1      1 notaA    5.2
 2      1 notaB    6.3
 3      1 notaC    3.4
 4      1 notaD    2.3
 5      1 notaE    2  
 6      2 notaA    5.7
 7      2 notaB    5.7
 8      2 notaC    4.2
 9      2 notaD    3.5
10      2 notaE    2.7</code></pre>
</div>
</div>
<p>Cada alumno pasa de ocupar una fila a ocupar cinco (una por prueba), de modo que <code>df_largo</code> tiene <span class="math inline">\(120 \times 5 = 600\)</span> filas. Algunas notas son valores perdidos (10 en total, repartidos entre <code>notaB</code>, <code>notaC</code>, <code>notaD</code> y <code>notaE</code>), que se mantienen en <code>df_largo</code> y se tratarán más adelante según lo exija cada contraste.</p>
<p><strong>Estadísticos descriptivos por prueba</strong></p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>df_largo <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(prueba) <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(nota)),</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(nota, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">dt =</span> <span class="fu">sd</span>(nota, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 4
  prueba     n media    dt
  &lt;fct&gt;  &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;
1 notaA    120  6.03  1.34
2 notaB    115  6.81  1.54
3 notaC    119  5.07  1.63
4 notaD    118  4.12  1.68
5 notaE    118  2.70  1.80</code></pre>
</div>
</div>
<p>La nota media desciende de forma bastante regular a lo largo del curso, de <span class="math inline">\(\bar{x}=6.03\)</span> en la prueba A a <span class="math inline">\(\bar{x}=2.70\)</span> en la prueba E, con desviaciones típicas parecidas entre sí (entre 1.34 y 1.80). Esta caída progresiva de la media ya sugiere que las cinco pruebas no tienen el mismo nivel de dificultad o de exigencia, algo que los contrastes de este capítulo permitirán confirmar formalmente.</p>
<p><strong>Gráficos</strong></p>
<p>El diagrama de cajas y bigotes de <code>nota</code> según <code>prueba</code> permite comparar de un vistazo la posición y la dispersión de las cinco pruebas:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_largo, <span class="fu">aes</span>(<span class="at">x =</span> prueba, <span class="at">y =</span> nota, <span class="at">fill =</span> prueba)) <span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set2"</span>) <span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Prueba"</span>, <span class="at">y =</span> <span class="st">"Nota"</span>) <span class="sc">+</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="15-contrastes-medidas-repetidas_files/figure-html/boxplot-pruebas-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Diagrama de cajas y bigotes de la nota en cada una de las cinco pruebas.</figcaption>
</figure>
</div>
</div>
</div>
<p>Como el interés de este capítulo está en las medidas repetidas sobre los mismos individuos, conviene también visualizar la trayectoria de cada alumno a través de las cinco pruebas. Para no saturar el gráfico se representan solo los 10 primeros alumnos, junto con la trayectoria de la media general (en rojo) calculada sobre todos los alumnos:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_largo <span class="sc">%&gt;%</span> <span class="fu">filter</span>(alumno <span class="sc">&lt;=</span> <span class="dv">10</span>), <span class="fu">aes</span>(<span class="at">x =</span> prueba, <span class="at">y =</span> nota)) <span class="sc">+</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> alumno), <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">data =</span> df_largo, <span class="fu">aes</span>(<span class="at">group =</span> <span class="dv">1</span>), <span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"line"</span>, <span class="at">color =</span> <span class="st">"firebrick"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Prueba"</span>, <span class="at">y =</span> <span class="st">"Nota"</span>) <span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="15-contrastes-medidas-repetidas_files/figure-html/lineas-trayectoria-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Trayectoria de las notas de los 10 primeros alumnos a través de las cinco pruebas, con la media general superpuesta en rojo.</figcaption>
</figure>
</div>
</div>
</div>
<p>Tanto las cajas como las trayectorias individuales confirman la tendencia descendente ya apuntada por las medias: la mayoría de los alumnos obtiene notas cada vez más bajas a medida que avanzan las pruebas, aunque con un orden entre alumnos que se mantiene razonablemente estable (quien saca más nota en la prueba A tiende también a sacar más nota en las siguientes).</p>
<p><strong>Comprobación de la normalidad</strong></p>
<p>El ANOVA de medidas repetidas que se presenta en la sección siguiente exige que la variable sea normal en cada una de las medidas repetidas. Antes de aplicarlo conviene comprobarlo, con el test de Shapiro-Wilk visto en el capítulo de <a href="./11-contrastes-una-poblacion.html">contrastes para una población</a>, en cada una de las cinco pruebas por separado:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>df_largo <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(prueba) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(nota)),</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">p-valor</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">shapiro.test</span>(nota[<span class="sc">!</span><span class="fu">is.na</span>(nota)])<span class="sc">$</span>p.value</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 3
  prueba     n  `p-valor`
  &lt;fct&gt;  &lt;int&gt;      &lt;dbl&gt;
1 notaA    120 0.907     
2 notaB    115 0.0675    
3 notaC    119 0.412     
4 notaD    118 0.575     
5 notaE    118 0.00000407</code></pre>
</div>
</div>
<p>En <code>notaA</code>, <code>notaB</code>, <code>notaC</code> y <code>notaD</code> el p-valor del test de Shapiro-Wilk es superior a 0.05 (0.907, 0.068, 0.412 y 0.575, respectivamente), por lo que no hay evidencia para rechazar la normalidad en ninguna de ellas. En <code>notaE</code>, en cambio, el p-valor es <span class="math inline">\(4.07\times10^{-6}\)</span>, muy inferior a 0.05, por lo que se rechaza la normalidad: esta última prueba tiene una distribución claramente no normal (coherente con concentrar más alumnos suspensos en valores bajos, lo que genera asimetría). El requisito de normalidad del ANOVA de medidas repetidas no se cumple, por tanto, de forma estricta en las cinco pruebas a la vez, lo que hace especialmente pertinente comprobar también el resultado con la alternativa no paramétrica, el test de Friedman, que se presenta a continuación.</p>
</section>
<section id="comparación-de-las-medidas-repetidas" class="level2" data-number="15.2">
<h2 data-number="15.2" class="anchored" data-anchor-id="comparación-de-las-medidas-repetidas"><span class="header-section-number">15.2</span> Comparación de las medidas repetidas</h2>
<p>Con los datos ya en formato largo, el objetivo es contrastar si existen diferencias entre las medias (o las distribuciones) de las cinco pruebas. Según pueda asumirse o no la normalidad de las notas, se dispone de una versión paramétrica (el ANOVA de medidas repetidas) y de una alternativa no paramétrica (el test de Friedman).</p>
<section id="anova-de-medidas-repetidas-de-un-factor" class="level3" data-number="15.2.1">
<h3 data-number="15.2.1" class="anchored" data-anchor-id="anova-de-medidas-repetidas-de-un-factor"><span class="header-section-number">15.2.1</span> ANOVA de medidas repetidas de un factor</h3>
<div id="def-medidasrepetidas-anova" class="theorem definition">
<p><span class="theorem-title"><strong>Definición 15.1 (ANOVA de medidas repetidas de un factor)</strong></span> El <em>ANOVA de medidas repetidas de un factor</em> contrasta si las medias de una variable cuantitativa son iguales en más de dos medidas relacionadas (tomadas sobre los mismos individuos). La hipótesis nula es</p>
<p><span class="math display">\[H_0: \mu_1 = \mu_2 = \dots = \mu_k,\]</span></p>
<p>donde <span class="math inline">\(\mu_1, \dots, \mu_k\)</span> son las medias poblacionales de las <span class="math inline">\(k\)</span> medidas repetidas, frente a la alternativa de que al menos una de esas medias difiere de las demás.</p>
</div>
<p><strong>Requisitos</strong>: la variable dependiente debe ser cuantitativa y seguir una distribución normal en cada una de las medidas repetidas (o un tamaño muestral suficientemente grande en cada una). Además debe cumplirse el supuesto de <strong>esfericidad</strong>, que exige que las varianzas de las diferencias entre todos los pares posibles de medidas repetidas sean aproximadamente iguales; cuando no se cumple, el contraste se vuelve demasiado liberal (rechaza <span class="math inline">\(H_0\)</span> con más facilidad de la debida) y conviene corregirlo o recurrir a la alternativa no paramétrica de la sección siguiente. Su comprobación formal (con el test de esfericidad de Mauchly y correcciones como la de Greenhouse-Geisser) queda fuera del alcance de este capítulo introductorio.</p>
<p>En R, el ANOVA de medidas repetidas se ajusta con la función <code>aov()</code> habitual, pero añadiendo un término <code>Error()</code> que identifica al alumno como la unidad sobre la que se repiten las medidas: <code>Error(alumno/prueba)</code> indica que <code>prueba</code> varía dentro de cada <code>alumno</code>. Este contraste exige que todos los individuos tengan las cinco medidas completas, así que primero se eliminan de <code>df_largo</code> los alumnos con alguna nota perdida.</p>
<div id="exm-medidasrepetidas-anova" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 15.1</strong></span> &nbsp;</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>df_largo_completo <span class="ot">&lt;-</span> df_largo <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(alumno) <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">any</span>(<span class="fu">is.na</span>(nota))) <span class="sc">%&gt;%</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">alumno =</span> <span class="fu">factor</span>(alumno))</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="fu">n_distinct</span>(df_largo_completo<span class="sc">$</span>alumno)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 111</code></pre>
</div>
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">aov</span>(nota <span class="sc">~</span> prueba <span class="sc">+</span> <span class="fu">Error</span>(alumno<span class="sc">/</span>prueba), <span class="at">data =</span> df_largo_completo)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Error: alumno
           Df Sum Sq Mean Sq F value Pr(&gt;F)
Residuals 110  688.9   6.262               

Error: alumno:prueba
           Df Sum Sq Mean Sq F value Pr(&gt;F)    
prueba      4 1122.2  280.56   192.5 &lt;2e-16 ***
Residuals 440  641.4    1.46                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>De los 120 alumnos, 111 tienen las cinco notas completas y son los que entran en el análisis (los 9 restantes se descartan por tener algún valor perdido). El resultado se organiza en dos estratos: el primero (<code>Error: alumno</code>) recoge la variabilidad debida a las diferencias globales entre alumnos, y el segundo (<code>Error: alumno:prueba</code>) es el que contiene el contraste de interés, sobre <code>prueba</code>. El estadístico es <span class="math inline">\(F=192.5\)</span> con 4 y 440 grados de libertad, y un p-valor inferior a <span class="math inline">\(2\times10^{-16}\)</span>, muy por debajo de 0.05, por lo que se rechaza <span class="math inline">\(H_0\)</span>: existen diferencias significativas entre las medias de las cinco pruebas. A la vista de las medias descendentes ya observadas (de 6.03 en la prueba A a 2.70 en la prueba E), la conclusión es que el nivel de exigencia (o el rendimiento medio) no se mantiene constante a lo largo del curso.</p>
</div>
<p>El ANOVA de medidas repetidas solo informa de que <strong>alguna</strong> de las cinco medias difiere de las demás, pero no de <strong>cuáles</strong>. Para averiguarlo se puede completar el análisis con comparaciones por pares (una versión del test t pareado para cada par de pruebas), corrigiendo el nivel de significación de cada comparación individual con el método de Bonferroni para controlar la probabilidad de cometer al menos un error de tipo I al hacer varias comparaciones a la vez:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.t.test</span>(df_largo_completo<span class="sc">$</span>nota, df_largo_completo<span class="sc">$</span>prueba,</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">paired =</span> <span class="cn">TRUE</span>, <span class="at">p.adjust.method =</span> <span class="st">"bonferroni"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using paired t tests 

data:  df_largo_completo$nota and df_largo_completo$prueba 

      notaA   notaB   notaC   notaD  
notaB &lt; 2e-16 -       -       -      
notaC 2.1e-14 &lt; 2e-16 -       -      
notaD &lt; 2e-16 &lt; 2e-16 &lt; 2e-16 -      
notaE &lt; 2e-16 &lt; 2e-16 &lt; 2e-16 7.9e-07

P value adjustment method: bonferroni </code></pre>
</div>
</div>
<p>Los diez p-valores de la tabla son inferiores a 0.05 (el mayor, entre <code>notaD</code> y <code>notaE</code>, es <span class="math inline">\(7.9\times10^{-7}\)</span>), por lo que las cinco pruebas difieren significativamente entre sí dos a dos: no se trata de que una única prueba se aparte de las demás, sino de un descenso generalizado y progresivo del rendimiento a lo largo de las cinco pruebas.</p>
</section>
<section id="test-de-friedman" class="level3" data-number="15.2.2">
<h3 data-number="15.2.2" class="anchored" data-anchor-id="test-de-friedman"><span class="header-section-number">15.2.2</span> Test de Friedman</h3>
<div id="def-medidasrepetidas-friedman" class="theorem definition">
<p><span class="theorem-title"><strong>Definición 15.2 (Test de Friedman)</strong></span> El <em>test de Friedman</em> es la alternativa no paramétrica al ANOVA de medidas repetidas: contrasta si existen diferencias entre más de dos medidas relacionadas sin necesidad de asumir que la variable sigue una distribución normal. La hipótesis nula es</p>
<p><span class="math display">\[H_0: \mbox{no hay diferencias entre las medidas repetidas.}\]</span></p>
<p>El contraste se basa en los rangos que ocupa cada medida dentro de cada individuo, en lugar de en los valores originales de la variable.</p>
</div>
<p><strong>Requisitos</strong>: la variable dependiente debe ser, al menos, cualitativa ordinal (o cuantitativa), y las medidas deben proceder de los mismos individuos. No exige normalidad, por lo que es la opción adecuada cuando no puede garantizarse el requisito de normalidad (o de esfericidad) del ANOVA de medidas repetidas.</p>
<p>En R, <code>friedman.test()</code> no trabaja sobre el formato largo, sino que espera una matriz con los individuos en las filas y las medidas repetidas en las columnas (es decir, prácticamente el formato ancho original), y no admite valores perdidos, por lo que hay que eliminarlos antes con <code>na.omit()</code>.</p>
<div id="exm-medidasrepetidas-friedman" class="theorem example">
<p><span class="theorem-title"><strong>Ejemplo 15.2</strong></span> &nbsp;</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>mat_notas <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(notaA, notaB, notaC, notaD, notaE) <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.matrix</span>() <span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(mat_notas)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 111</code></pre>
</div>
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">friedman.test</span>(mat_notas)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Friedman rank sum test

data:  mat_notas
Friedman chi-squared = 316.59, df = 4, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Tras eliminar los valores perdidos quedan, de nuevo, 111 alumnos con las cinco notas completas (los mismos que en el ANOVA anterior). El estadístico del contraste es <span class="math inline">\(\chi^2=316.59\)</span> con 4 grados de libertad y un p-valor inferior a <span class="math inline">\(2.2\times10^{-16}\)</span>, muy inferior a 0.05, por lo que también se rechaza <span class="math inline">\(H_0\)</span>: hay diferencias significativas entre las cinco pruebas. La conclusión coincide plenamente con la del ANOVA de medidas repetidas, lo cual es tranquilizador dado que, como se vio antes, <code>notaE</code> no cumplía estrictamente el requisito de normalidad: al no depender de ese supuesto, el resultado del test de Friedman es, en este caso concreto, la referencia más fiable de las dos, y el hecho de que ambos contrastes coincidan en su conclusión refuerza la confianza en el resultado.</p>
</div>
<p>Al igual que con el ANOVA, el test de Friedman solo indica que existen diferencias globales, no entre qué pares de pruebas concretas. La versión no paramétrica de las comparaciones por pares, con la misma corrección de Bonferroni, se obtiene con <code>pairwise.wilcox.test()</code>:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.wilcox.test</span>(df_largo_completo<span class="sc">$</span>nota, df_largo_completo<span class="sc">$</span>prueba,</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">paired =</span> <span class="cn">TRUE</span>, <span class="at">p.adjust.method =</span> <span class="st">"bonferroni"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using Wilcoxon signed rank test with continuity correction 

data:  df_largo_completo$nota and df_largo_completo$prueba 

      notaA   notaB   notaC   notaD  
notaB 1.3e-13 -       -       -      
notaC 8.8e-12 5.2e-16 -       -      
notaD &lt; 2e-16 &lt; 2e-16 &lt; 2e-16 -      
notaE &lt; 2e-16 &lt; 2e-16 9.1e-13 8.8e-07

P value adjustment method: bonferroni </code></pre>
</div>
</div>
<p>De nuevo los diez p-valores son inferiores a 0.05 (el mayor, <span class="math inline">\(8.8\times10^{-7}\)</span>, vuelve a corresponder al par <code>notaD</code>-<code>notaE</code>), confirmando con un método que no depende de la normalidad la misma conclusión obtenida con las comparaciones paramétricas: cada una de las cinco pruebas difiere significativamente de las demás.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ante datos de medidas repetidas conviene aplicar primero el test de Shapiro-Wilk (u otro contraste de normalidad) en cada una de las medidas por separado. Si todas son razonablemente normales, el ANOVA de medidas repetidas es la opción más potente; si alguna se aparta claramente de la normalidad, como ocurre aquí con <code>notaE</code>, el test de Friedman es la alternativa más segura. Cuando, como en este ejemplo, ambos contrastes coinciden en su conclusión, puede reportarse cualquiera de los dos con tranquilidad. La comprobación formal del supuesto adicional de esfericidad que exige el ANOVA de medidas repetidas (con el test de Mauchly y las correcciones de Greenhouse-Geisser o Huynh-Feldt) se desarrolla con detalle en el <a href="https://aprendeconalf.es/estadistica-manual/">Manual de Estadística</a>.</p>
</div>
</div>
</section>
</section>
<section id="resumen" class="level2" data-number="15.3">
<h2 data-number="15.3" class="anchored" data-anchor-id="resumen"><span class="header-section-number">15.3</span> Resumen</h2>
<p>Los dos contrastes de este capítulo llegan a la misma conclusión: el rendimiento de los alumnos no es constante a lo largo de las cinco pruebas del curso, sino que desciende de forma significativa y, según muestran las comparaciones por pares, de forma generalizada entre todas ellas. Un resultado así, obtenido sobre datos de medidas repetidas, sugiere una pregunta que el contraste estadístico por sí solo no puede responder: si el descenso se debe a que las pruebas son cada vez más difíciles, a que la materia se acumula y exige más al alumno conforme avanza el curso, o a otra causa distinta (por ejemplo, cansancio o pérdida de motivación); dar respuesta a esa pregunta exigiría un diseño adicional, no solo un contraste de hipótesis.</p>
<p>Ambos contrastes son, además, la generalización, a más de dos medidas repetidas, del contraste paramétrico visto en <a href="./13-contrastes-dos-poblaciones-pareadas.html">Contrastes para dos poblaciones pareadas</a> para el caso particular de solo dos medidas: de hecho, cuando solo hay dos medidas repetidas, el estadístico F del ANOVA de medidas repetidas coincide con el cuadrado del estadístico t del test t pareado, y ambos contrastes dan exactamente el mismo p-valor. El test de Friedman, en cambio, no se reduce al test de Wilcoxon para datos pareados cuando solo hay dos medidas, porque Friedman se basa únicamente en el orden (el rango) que ocupa cada medida dentro de cada individuo, mientras que Wilcoxon tiene en cuenta también la magnitud de las diferencias; con dos medidas, la generalización natural del test de Friedman es más bien el test de los signos.</p>
<p>Con esto se cierra la parte de la tabla de decisión dedicada a comparar medias o distribuciones entre dos o más poblaciones, ya sean independientes o relacionadas; el <a href="./16-relacion-entre-variables.html">último capítulo de esta parte</a> aborda una cuestión distinta: la relación y la predicción entre dos variables cuantitativas.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./14-contrastes-mas-dos-poblaciones-independientes.html" class="pagination-link" aria-label="Contrastes para más de dos poblaciones independientes">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Contrastes para más de dos poblaciones independientes</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./16-relacion-entre-variables.html" class="pagination-link" aria-label="Relación y predicción entre dos variables">
        <span class="nav-page-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Relación y predicción entre dos variables</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Ejecutar el código</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb21" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> Contrastes para más de dos poblaciones relacionadas (medidas repetidas)</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="an">lang:</span><span class="co"> es</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="in">```{r setup, include=FALSE}</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span>opts_chunk<span class="sc">$</span><span class="fu">set</span>(<span class="at">echo =</span> <span class="cn">TRUE</span>, <span class="at">message =</span> <span class="cn">FALSE</span>, <span class="at">warning =</span> <span class="cn">FALSE</span>)</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"datos/datos-curso.csv"</span>)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>Este capítulo generaliza el <span class="co">[</span><span class="ot">capítulo anterior</span><span class="co">](13-contrastes-dos-poblaciones-pareadas.qmd)</span>, dedicado a dos poblaciones pareadas, al caso de **más de dos** medidas relacionadas tomadas sobre los mismos individuos. Corresponde a la fila de la [tabla de decisión](10-seleccion-contraste.qmd) en la que la variable independiente es cualitativa con más de dos categorías, pero, a diferencia del [capítulo dedicado a poblaciones independientes](14-contrastes-mas-dos-poblaciones-independientes.qmd), esas categorías no distinguen grupos de individuos distintos, sino ocasiones de medida repetidas sobre los mismos individuos. El conjunto de datos del curso dispone de cinco calificaciones distintas, `notaA`, `notaB`, `notaC`, `notaD` y `notaE`, obtenidas por los **mismos** 120 alumnos (pueden interpretarse como cinco pruebas o exámenes distintos realizados por cada alumno a lo largo del curso). Estas cinco notas no son, por tanto, cinco poblaciones independientes, sino cinco **medidas repetidas** por individuo, y esa dependencia entre ellas es la que obliga a utilizar contrastes distintos de los vistos en el capítulo anterior sobre poblaciones independientes: ignorarla y tratar las cinco notas como si procedieran de alumnos distintos infravaloraría la precisión real de las comparaciones y podría llevar a conclusiones erróneas.</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a><span class="fu">## Preparación de los datos: de formato ancho a formato largo</span></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>En <span class="in">`df`</span>, cada alumno ocupa una única fila y cada una de sus cinco notas ocupa una columna distinta (<span class="in">`notaA`</span>, ..., <span class="in">`notaE`</span>): es el llamado **formato ancho**. Los contrastes de este capítulo, sin embargo, necesitan el **formato largo**, en el que cada fila representa una única combinación de alumno y prueba. Para pasar de un formato a otro se crea primero un identificador de alumno (el número de fila) y después se reorganizan las cinco columnas de notas en dos columnas nuevas, <span class="in">`prueba`</span> (con el nombre de la prueba) y <span class="in">`nota`</span> (con la calificación), usando <span class="in">`tidyr::pivot_longer()`</span>:</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a><span class="in">```{r pivot-largo}</span></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>df_largo <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">alumno =</span> <span class="fu">row_number</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(alumno, notaA, notaB, notaC, notaD, notaE) <span class="sc">%&gt;%</span></span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">"nota"</span>), <span class="at">names_to =</span> <span class="st">"prueba"</span>, <span class="at">values_to =</span> <span class="st">"nota"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prueba =</span> <span class="fu">factor</span>(prueba))</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_largo, <span class="dv">10</span>)</span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>Cada alumno pasa de ocupar una fila a ocupar cinco (una por prueba), de modo que <span class="in">`df_largo`</span> tiene $120 \times 5 = 600$ filas. Algunas notas son valores perdidos (10 en total, repartidos entre <span class="in">`notaB`</span>, <span class="in">`notaC`</span>, <span class="in">`notaD`</span> y <span class="in">`notaE`</span>), que se mantienen en <span class="in">`df_largo`</span> y se tratarán más adelante según lo exija cada contraste.</span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a>**Estadísticos descriptivos por prueba**</span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a><span class="in">```{r descriptivos-prueba}</span></span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a>df_largo <span class="sc">%&gt;%</span></span>
<span id="cb21-34"><a href="#cb21-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(prueba) <span class="sc">%&gt;%</span></span>
<span id="cb21-35"><a href="#cb21-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb21-36"><a href="#cb21-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(nota)),</span>
<span id="cb21-37"><a href="#cb21-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(nota, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb21-38"><a href="#cb21-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">dt =</span> <span class="fu">sd</span>(nota, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb21-39"><a href="#cb21-39" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb21-40"><a href="#cb21-40" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-41"><a href="#cb21-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-42"><a href="#cb21-42" aria-hidden="true" tabindex="-1"></a>La nota media desciende de forma bastante regular a lo largo del curso, de $\bar{x}=6.03$ en la prueba A a $\bar{x}=2.70$ en la prueba E, con desviaciones típicas parecidas entre sí (entre 1.34 y 1.80). Esta caída progresiva de la media ya sugiere que las cinco pruebas no tienen el mismo nivel de dificultad o de exigencia, algo que los contrastes de este capítulo permitirán confirmar formalmente.</span>
<span id="cb21-43"><a href="#cb21-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-44"><a href="#cb21-44" aria-hidden="true" tabindex="-1"></a>**Gráficos**</span>
<span id="cb21-45"><a href="#cb21-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-46"><a href="#cb21-46" aria-hidden="true" tabindex="-1"></a>El diagrama de cajas y bigotes de <span class="in">`nota`</span> según <span class="in">`prueba`</span> permite comparar de un vistazo la posición y la dispersión de las cinco pruebas:</span>
<span id="cb21-47"><a href="#cb21-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-48"><a href="#cb21-48" aria-hidden="true" tabindex="-1"></a><span class="in">```{r boxplot-pruebas, fig.cap="Diagrama de cajas y bigotes de la nota en cada una de las cinco pruebas."}</span></span>
<span id="cb21-49"><a href="#cb21-49" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_largo, <span class="fu">aes</span>(<span class="at">x =</span> prueba, <span class="at">y =</span> nota, <span class="at">fill =</span> prueba)) <span class="sc">+</span></span>
<span id="cb21-50"><a href="#cb21-50" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb21-51"><a href="#cb21-51" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set2"</span>) <span class="sc">+</span></span>
<span id="cb21-52"><a href="#cb21-52" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Prueba"</span>, <span class="at">y =</span> <span class="st">"Nota"</span>) <span class="sc">+</span></span>
<span id="cb21-53"><a href="#cb21-53" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb21-54"><a href="#cb21-54" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span>
<span id="cb21-55"><a href="#cb21-55" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-56"><a href="#cb21-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-57"><a href="#cb21-57" aria-hidden="true" tabindex="-1"></a>Como el interés de este capítulo está en las medidas repetidas sobre los mismos individuos, conviene también visualizar la trayectoria de cada alumno a través de las cinco pruebas. Para no saturar el gráfico se representan solo los 10 primeros alumnos, junto con la trayectoria de la media general (en rojo) calculada sobre todos los alumnos:</span>
<span id="cb21-58"><a href="#cb21-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-59"><a href="#cb21-59" aria-hidden="true" tabindex="-1"></a><span class="in">```{r lineas-trayectoria, fig.cap="Trayectoria de las notas de los 10 primeros alumnos a través de las cinco pruebas, con la media general superpuesta en rojo."}</span></span>
<span id="cb21-60"><a href="#cb21-60" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_largo <span class="sc">%&gt;%</span> <span class="fu">filter</span>(alumno <span class="sc">&lt;=</span> <span class="dv">10</span>), <span class="fu">aes</span>(<span class="at">x =</span> prueba, <span class="at">y =</span> nota)) <span class="sc">+</span></span>
<span id="cb21-61"><a href="#cb21-61" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> alumno), <span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb21-62"><a href="#cb21-62" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">data =</span> df_largo, <span class="fu">aes</span>(<span class="at">group =</span> <span class="dv">1</span>), <span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"line"</span>, <span class="at">color =</span> <span class="st">"firebrick"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb21-63"><a href="#cb21-63" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Prueba"</span>, <span class="at">y =</span> <span class="st">"Nota"</span>) <span class="sc">+</span></span>
<span id="cb21-64"><a href="#cb21-64" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb21-65"><a href="#cb21-65" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-66"><a href="#cb21-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-67"><a href="#cb21-67" aria-hidden="true" tabindex="-1"></a>Tanto las cajas como las trayectorias individuales confirman la tendencia descendente ya apuntada por las medias: la mayoría de los alumnos obtiene notas cada vez más bajas a medida que avanzan las pruebas, aunque con un orden entre alumnos que se mantiene razonablemente estable (quien saca más nota en la prueba A tiende también a sacar más nota en las siguientes).</span>
<span id="cb21-68"><a href="#cb21-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-69"><a href="#cb21-69" aria-hidden="true" tabindex="-1"></a>**Comprobación de la normalidad**</span>
<span id="cb21-70"><a href="#cb21-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-71"><a href="#cb21-71" aria-hidden="true" tabindex="-1"></a>El ANOVA de medidas repetidas que se presenta en la sección siguiente exige que la variable sea normal en cada una de las medidas repetidas. Antes de aplicarlo conviene comprobarlo, con el test de Shapiro-Wilk visto en el capítulo de <span class="co">[</span><span class="ot">contrastes para una población</span><span class="co">](11-contrastes-una-poblacion.qmd)</span>, en cada una de las cinco pruebas por separado:</span>
<span id="cb21-72"><a href="#cb21-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-73"><a href="#cb21-73" aria-hidden="true" tabindex="-1"></a><span class="in">```{r shapiro-pruebas}</span></span>
<span id="cb21-74"><a href="#cb21-74" aria-hidden="true" tabindex="-1"></a>df_largo <span class="sc">%&gt;%</span></span>
<span id="cb21-75"><a href="#cb21-75" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(prueba) <span class="sc">%&gt;%</span></span>
<span id="cb21-76"><a href="#cb21-76" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb21-77"><a href="#cb21-77" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(nota)),</span>
<span id="cb21-78"><a href="#cb21-78" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">p-valor</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">shapiro.test</span>(nota[<span class="sc">!</span><span class="fu">is.na</span>(nota)])<span class="sc">$</span>p.value</span>
<span id="cb21-79"><a href="#cb21-79" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb21-80"><a href="#cb21-80" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-81"><a href="#cb21-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-82"><a href="#cb21-82" aria-hidden="true" tabindex="-1"></a>En <span class="in">`notaA`</span>, <span class="in">`notaB`</span>, <span class="in">`notaC`</span> y <span class="in">`notaD`</span> el p-valor del test de Shapiro-Wilk es superior a 0.05 (0.907, 0.068, 0.412 y 0.575, respectivamente), por lo que no hay evidencia para rechazar la normalidad en ninguna de ellas. En <span class="in">`notaE`</span>, en cambio, el p-valor es $4.07\times10^{-6}$, muy inferior a 0.05, por lo que se rechaza la normalidad: esta última prueba tiene una distribución claramente no normal (coherente con concentrar más alumnos suspensos en valores bajos, lo que genera asimetría). El requisito de normalidad del ANOVA de medidas repetidas no se cumple, por tanto, de forma estricta en las cinco pruebas a la vez, lo que hace especialmente pertinente comprobar también el resultado con la alternativa no paramétrica, el test de Friedman, que se presenta a continuación.</span>
<span id="cb21-83"><a href="#cb21-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-84"><a href="#cb21-84" aria-hidden="true" tabindex="-1"></a><span class="fu">## Comparación de las medidas repetidas</span></span>
<span id="cb21-85"><a href="#cb21-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-86"><a href="#cb21-86" aria-hidden="true" tabindex="-1"></a>Con los datos ya en formato largo, el objetivo es contrastar si existen diferencias entre las medias (o las distribuciones) de las cinco pruebas. Según pueda asumirse o no la normalidad de las notas, se dispone de una versión paramétrica (el ANOVA de medidas repetidas) y de una alternativa no paramétrica (el test de Friedman).</span>
<span id="cb21-87"><a href="#cb21-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-88"><a href="#cb21-88" aria-hidden="true" tabindex="-1"></a><span class="fu">### ANOVA de medidas repetidas de un factor</span></span>
<span id="cb21-89"><a href="#cb21-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-90"><a href="#cb21-90" aria-hidden="true" tabindex="-1"></a>:::{#def-medidasrepetidas-anova}</span>
<span id="cb21-91"><a href="#cb21-91" aria-hidden="true" tabindex="-1"></a><span class="fu">## ANOVA de medidas repetidas de un factor</span></span>
<span id="cb21-92"><a href="#cb21-92" aria-hidden="true" tabindex="-1"></a>El _ANOVA de medidas repetidas de un factor_ contrasta si las medias de una variable cuantitativa son iguales en más de dos medidas relacionadas (tomadas sobre los mismos individuos). La hipótesis nula es</span>
<span id="cb21-93"><a href="#cb21-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-94"><a href="#cb21-94" aria-hidden="true" tabindex="-1"></a>$$H_0: \mu_1 = \mu_2 = \dots = \mu_k,$$</span>
<span id="cb21-95"><a href="#cb21-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-96"><a href="#cb21-96" aria-hidden="true" tabindex="-1"></a>donde $\mu_1, \dots, \mu_k$ son las medias poblacionales de las $k$ medidas repetidas, frente a la alternativa de que al menos una de esas medias difiere de las demás.</span>
<span id="cb21-97"><a href="#cb21-97" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb21-98"><a href="#cb21-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-99"><a href="#cb21-99" aria-hidden="true" tabindex="-1"></a>**Requisitos**: la variable dependiente debe ser cuantitativa y seguir una distribución normal en cada una de las medidas repetidas (o un tamaño muestral suficientemente grande en cada una). Además debe cumplirse el supuesto de **esfericidad**, que exige que las varianzas de las diferencias entre todos los pares posibles de medidas repetidas sean aproximadamente iguales; cuando no se cumple, el contraste se vuelve demasiado liberal (rechaza $H_0$ con más facilidad de la debida) y conviene corregirlo o recurrir a la alternativa no paramétrica de la sección siguiente. Su comprobación formal (con el test de esfericidad de Mauchly y correcciones como la de Greenhouse-Geisser) queda fuera del alcance de este capítulo introductorio.</span>
<span id="cb21-100"><a href="#cb21-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-101"><a href="#cb21-101" aria-hidden="true" tabindex="-1"></a>En R, el ANOVA de medidas repetidas se ajusta con la función <span class="in">`aov()`</span> habitual, pero añadiendo un término <span class="in">`Error()`</span> que identifica al alumno como la unidad sobre la que se repiten las medidas: <span class="in">`Error(alumno/prueba)`</span> indica que <span class="in">`prueba`</span> varía dentro de cada <span class="in">`alumno`</span>. Este contraste exige que todos los individuos tengan las cinco medidas completas, así que primero se eliminan de <span class="in">`df_largo`</span> los alumnos con alguna nota perdida.</span>
<span id="cb21-102"><a href="#cb21-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-103"><a href="#cb21-103" aria-hidden="true" tabindex="-1"></a>:::{#exm-medidasrepetidas-anova}</span>
<span id="cb21-104"><a href="#cb21-104" aria-hidden="true" tabindex="-1"></a><span class="in">```{r anova-medidas-repetidas}</span></span>
<span id="cb21-105"><a href="#cb21-105" aria-hidden="true" tabindex="-1"></a>df_largo_completo <span class="ot">&lt;-</span> df_largo <span class="sc">%&gt;%</span></span>
<span id="cb21-106"><a href="#cb21-106" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(alumno) <span class="sc">%&gt;%</span></span>
<span id="cb21-107"><a href="#cb21-107" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">any</span>(<span class="fu">is.na</span>(nota))) <span class="sc">%&gt;%</span></span>
<span id="cb21-108"><a href="#cb21-108" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb21-109"><a href="#cb21-109" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">alumno =</span> <span class="fu">factor</span>(alumno))</span>
<span id="cb21-110"><a href="#cb21-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-111"><a href="#cb21-111" aria-hidden="true" tabindex="-1"></a><span class="fu">n_distinct</span>(df_largo_completo<span class="sc">$</span>alumno)</span>
<span id="cb21-112"><a href="#cb21-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-113"><a href="#cb21-113" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">aov</span>(nota <span class="sc">~</span> prueba <span class="sc">+</span> <span class="fu">Error</span>(alumno<span class="sc">/</span>prueba), <span class="at">data =</span> df_largo_completo)</span>
<span id="cb21-114"><a href="#cb21-114" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)</span>
<span id="cb21-115"><a href="#cb21-115" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-116"><a href="#cb21-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-117"><a href="#cb21-117" aria-hidden="true" tabindex="-1"></a>De los 120 alumnos, 111 tienen las cinco notas completas y son los que entran en el análisis (los 9 restantes se descartan por tener algún valor perdido). El resultado se organiza en dos estratos: el primero (<span class="in">`Error: alumno`</span>) recoge la variabilidad debida a las diferencias globales entre alumnos, y el segundo (<span class="in">`Error: alumno:prueba`</span>) es el que contiene el contraste de interés, sobre <span class="in">`prueba`</span>. El estadístico es $F=192.5$ con 4 y 440 grados de libertad, y un p-valor inferior a $2\times10^{-16}$, muy por debajo de 0.05, por lo que se rechaza $H_0$: existen diferencias significativas entre las medias de las cinco pruebas. A la vista de las medias descendentes ya observadas (de 6.03 en la prueba A a 2.70 en la prueba E), la conclusión es que el nivel de exigencia (o el rendimiento medio) no se mantiene constante a lo largo del curso.</span>
<span id="cb21-118"><a href="#cb21-118" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb21-119"><a href="#cb21-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-120"><a href="#cb21-120" aria-hidden="true" tabindex="-1"></a>El ANOVA de medidas repetidas solo informa de que **alguna** de las cinco medias difiere de las demás, pero no de **cuáles**. Para averiguarlo se puede completar el análisis con comparaciones por pares (una versión del test t pareado para cada par de pruebas), corrigiendo el nivel de significación de cada comparación individual con el método de Bonferroni para controlar la probabilidad de cometer al menos un error de tipo I al hacer varias comparaciones a la vez:</span>
<span id="cb21-121"><a href="#cb21-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-122"><a href="#cb21-122" aria-hidden="true" tabindex="-1"></a><span class="in">```{r pairwise-anova}</span></span>
<span id="cb21-123"><a href="#cb21-123" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.t.test</span>(df_largo_completo<span class="sc">$</span>nota, df_largo_completo<span class="sc">$</span>prueba,</span>
<span id="cb21-124"><a href="#cb21-124" aria-hidden="true" tabindex="-1"></a>                 <span class="at">paired =</span> <span class="cn">TRUE</span>, <span class="at">p.adjust.method =</span> <span class="st">"bonferroni"</span>)</span>
<span id="cb21-125"><a href="#cb21-125" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-126"><a href="#cb21-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-127"><a href="#cb21-127" aria-hidden="true" tabindex="-1"></a>Los diez p-valores de la tabla son inferiores a 0.05 (el mayor, entre <span class="in">`notaD`</span> y <span class="in">`notaE`</span>, es $7.9\times10^{-7}$), por lo que las cinco pruebas difieren significativamente entre sí dos a dos: no se trata de que una única prueba se aparte de las demás, sino de un descenso generalizado y progresivo del rendimiento a lo largo de las cinco pruebas.</span>
<span id="cb21-128"><a href="#cb21-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-129"><a href="#cb21-129" aria-hidden="true" tabindex="-1"></a><span class="fu">### Test de Friedman</span></span>
<span id="cb21-130"><a href="#cb21-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-131"><a href="#cb21-131" aria-hidden="true" tabindex="-1"></a>:::{#def-medidasrepetidas-friedman}</span>
<span id="cb21-132"><a href="#cb21-132" aria-hidden="true" tabindex="-1"></a><span class="fu">## Test de Friedman</span></span>
<span id="cb21-133"><a href="#cb21-133" aria-hidden="true" tabindex="-1"></a>El _test de Friedman_ es la alternativa no paramétrica al ANOVA de medidas repetidas: contrasta si existen diferencias entre más de dos medidas relacionadas sin necesidad de asumir que la variable sigue una distribución normal. La hipótesis nula es</span>
<span id="cb21-134"><a href="#cb21-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-135"><a href="#cb21-135" aria-hidden="true" tabindex="-1"></a>$$H_0: \mbox{no hay diferencias entre las medidas repetidas.}$$</span>
<span id="cb21-136"><a href="#cb21-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-137"><a href="#cb21-137" aria-hidden="true" tabindex="-1"></a>El contraste se basa en los rangos que ocupa cada medida dentro de cada individuo, en lugar de en los valores originales de la variable.</span>
<span id="cb21-138"><a href="#cb21-138" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb21-139"><a href="#cb21-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-140"><a href="#cb21-140" aria-hidden="true" tabindex="-1"></a>**Requisitos**: la variable dependiente debe ser, al menos, cualitativa ordinal (o cuantitativa), y las medidas deben proceder de los mismos individuos. No exige normalidad, por lo que es la opción adecuada cuando no puede garantizarse el requisito de normalidad (o de esfericidad) del ANOVA de medidas repetidas.</span>
<span id="cb21-141"><a href="#cb21-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-142"><a href="#cb21-142" aria-hidden="true" tabindex="-1"></a>En R, <span class="in">`friedman.test()`</span> no trabaja sobre el formato largo, sino que espera una matriz con los individuos en las filas y las medidas repetidas en las columnas (es decir, prácticamente el formato ancho original), y no admite valores perdidos, por lo que hay que eliminarlos antes con <span class="in">`na.omit()`</span>.</span>
<span id="cb21-143"><a href="#cb21-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-144"><a href="#cb21-144" aria-hidden="true" tabindex="-1"></a>:::{#exm-medidasrepetidas-friedman}</span>
<span id="cb21-145"><a href="#cb21-145" aria-hidden="true" tabindex="-1"></a><span class="in">```{r friedman-medidas-repetidas}</span></span>
<span id="cb21-146"><a href="#cb21-146" aria-hidden="true" tabindex="-1"></a>mat_notas <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb21-147"><a href="#cb21-147" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(notaA, notaB, notaC, notaD, notaE) <span class="sc">%&gt;%</span></span>
<span id="cb21-148"><a href="#cb21-148" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.matrix</span>() <span class="sc">%&gt;%</span></span>
<span id="cb21-149"><a href="#cb21-149" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span>
<span id="cb21-150"><a href="#cb21-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-151"><a href="#cb21-151" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(mat_notas)</span>
<span id="cb21-152"><a href="#cb21-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-153"><a href="#cb21-153" aria-hidden="true" tabindex="-1"></a><span class="fu">friedman.test</span>(mat_notas)</span>
<span id="cb21-154"><a href="#cb21-154" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-155"><a href="#cb21-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-156"><a href="#cb21-156" aria-hidden="true" tabindex="-1"></a>Tras eliminar los valores perdidos quedan, de nuevo, 111 alumnos con las cinco notas completas (los mismos que en el ANOVA anterior). El estadístico del contraste es $\chi^2=316.59$ con 4 grados de libertad y un p-valor inferior a $2.2\times10^{-16}$, muy inferior a 0.05, por lo que también se rechaza $H_0$: hay diferencias significativas entre las cinco pruebas. La conclusión coincide plenamente con la del ANOVA de medidas repetidas, lo cual es tranquilizador dado que, como se vio antes, <span class="in">`notaE`</span> no cumplía estrictamente el requisito de normalidad: al no depender de ese supuesto, el resultado del test de Friedman es, en este caso concreto, la referencia más fiable de las dos, y el hecho de que ambos contrastes coincidan en su conclusión refuerza la confianza en el resultado.</span>
<span id="cb21-157"><a href="#cb21-157" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb21-158"><a href="#cb21-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-159"><a href="#cb21-159" aria-hidden="true" tabindex="-1"></a>Al igual que con el ANOVA, el test de Friedman solo indica que existen diferencias globales, no entre qué pares de pruebas concretas. La versión no paramétrica de las comparaciones por pares, con la misma corrección de Bonferroni, se obtiene con <span class="in">`pairwise.wilcox.test()`</span>:</span>
<span id="cb21-160"><a href="#cb21-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-161"><a href="#cb21-161" aria-hidden="true" tabindex="-1"></a><span class="in">```{r pairwise-friedman}</span></span>
<span id="cb21-162"><a href="#cb21-162" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.wilcox.test</span>(df_largo_completo<span class="sc">$</span>nota, df_largo_completo<span class="sc">$</span>prueba,</span>
<span id="cb21-163"><a href="#cb21-163" aria-hidden="true" tabindex="-1"></a>                      <span class="at">paired =</span> <span class="cn">TRUE</span>, <span class="at">p.adjust.method =</span> <span class="st">"bonferroni"</span>)</span>
<span id="cb21-164"><a href="#cb21-164" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb21-165"><a href="#cb21-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-166"><a href="#cb21-166" aria-hidden="true" tabindex="-1"></a>De nuevo los diez p-valores son inferiores a 0.05 (el mayor, $8.8\times10^{-7}$, vuelve a corresponder al par <span class="in">`notaD`</span>-<span class="in">`notaE`</span>), confirmando con un método que no depende de la normalidad la misma conclusión obtenida con las comparaciones paramétricas: cada una de las cinco pruebas difiere significativamente de las demás.</span>
<span id="cb21-167"><a href="#cb21-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-168"><a href="#cb21-168" aria-hidden="true" tabindex="-1"></a>:::{.callout-tip}</span>
<span id="cb21-169"><a href="#cb21-169" aria-hidden="true" tabindex="-1"></a>Ante datos de medidas repetidas conviene aplicar primero el test de Shapiro-Wilk (u otro contraste de normalidad) en cada una de las medidas por separado. Si todas son razonablemente normales, el ANOVA de medidas repetidas es la opción más potente; si alguna se aparta claramente de la normalidad, como ocurre aquí con <span class="in">`notaE`</span>, el test de Friedman es la alternativa más segura. Cuando, como en este ejemplo, ambos contrastes coinciden en su conclusión, puede reportarse cualquiera de los dos con tranquilidad. La comprobación formal del supuesto adicional de esfericidad que exige el ANOVA de medidas repetidas (con el test de Mauchly y las correcciones de Greenhouse-Geisser o Huynh-Feldt) se desarrolla con detalle en el <span class="co">[</span><span class="ot">Manual de Estadística</span><span class="co">](https://aprendeconalf.es/estadistica-manual/)</span>.</span>
<span id="cb21-170"><a href="#cb21-170" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb21-171"><a href="#cb21-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-172"><a href="#cb21-172" aria-hidden="true" tabindex="-1"></a><span class="fu">## Resumen</span></span>
<span id="cb21-173"><a href="#cb21-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-174"><a href="#cb21-174" aria-hidden="true" tabindex="-1"></a>Los dos contrastes de este capítulo llegan a la misma conclusión: el rendimiento de los alumnos no es constante a lo largo de las cinco pruebas del curso, sino que desciende de forma significativa y, según muestran las comparaciones por pares, de forma generalizada entre todas ellas. Un resultado así, obtenido sobre datos de medidas repetidas, sugiere una pregunta que el contraste estadístico por sí solo no puede responder: si el descenso se debe a que las pruebas son cada vez más difíciles, a que la materia se acumula y exige más al alumno conforme avanza el curso, o a otra causa distinta (por ejemplo, cansancio o pérdida de motivación); dar respuesta a esa pregunta exigiría un diseño adicional, no solo un contraste de hipótesis.</span>
<span id="cb21-175"><a href="#cb21-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-176"><a href="#cb21-176" aria-hidden="true" tabindex="-1"></a>Ambos contrastes son, además, la generalización, a más de dos medidas repetidas, del contraste paramétrico visto en <span class="co">[</span><span class="ot">Contrastes para dos poblaciones pareadas</span><span class="co">](13-contrastes-dos-poblaciones-pareadas.qmd)</span> para el caso particular de solo dos medidas: de hecho, cuando solo hay dos medidas repetidas, el estadístico F del ANOVA de medidas repetidas coincide con el cuadrado del estadístico t del test t pareado, y ambos contrastes dan exactamente el mismo p-valor. El test de Friedman, en cambio, no se reduce al test de Wilcoxon para datos pareados cuando solo hay dos medidas, porque Friedman se basa únicamente en el orden (el rango) que ocupa cada medida dentro de cada individuo, mientras que Wilcoxon tiene en cuenta también la magnitud de las diferencias; con dos medidas, la generalización natural del test de Friedman es más bien el test de los signos.</span>
<span id="cb21-177"><a href="#cb21-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-178"><a href="#cb21-178" aria-hidden="true" tabindex="-1"></a>Con esto se cierra la parte de la tabla de decisión dedicada a comparar medias o distribuciones entre dos o más poblaciones, ya sean independientes o relacionadas; el <span class="co">[</span><span class="ot">último capítulo de esta parte</span><span class="co">](16-relacion-entre-variables.qmd)</span> aborda una cuestión distinta: la relación y la predicción entre dos variables cuantitativas.</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/asalber/estadistica-tipos-estudios/edit/main/15-contrastes-medidas-repetidas.qmd" class="toc-action"><i class="bi bi-github"></i>Editar esta página</a></li><li><a href="https://github.com/asalber/estadistica-tipos-estudios/issues/new" class="toc-action"><i class="bi empty"></i>Informar de un problema</a></li></ul></div></div></div></footer></body></html>